import type { Decklist } from '../decks.ts';

/**
 * Lorwyn Eclipsed decks (18c), part 1: the allied tribal pairs G/W Kithkin and W/U Merfolk. Built from the Selesnya Kithkin
 * and Azorius Merfolk skeletons in scripts/data/ecl-human-decks.md, scaled to 60 cards. See docs/lorwyn-eclipsed-plan.md.
 */
export const ECL_DECKS_1: Decklist[] = [
  {
    id: 'ecl-clachan-banner',
    name: 'Clachan Banner',
    colors: ['G', 'W'],
    face: "Brigid, Clachan's Heart",
    source: 'custom',
    series: 'starter',
    set: 'ecl',
    cards: [
      ['Figure of Fable', 2],
      ['Kinsbaile Aspirant', 2],
      ['Surly Farrier', 3],
      ['Dundoolin Weaver', 2],
      ['Eclipsed Kithkin', 2],
      ['Timid Shieldbearer', 3],
      ['Thoughtweft Lieutenant', 2],
      ['Wary Farmer', 3],
      ['Crossroads Watcher', 3],
      ['Gallant Fowlknight', 3],
      ['Mistmeadow Council', 3],
      ['Assert Perfection', 2],
      ["Brigid's Command", 1],
      ['Clachan Festival', 2],
      ['Liminal Hold', 2],
      ["Brigid, Clachan's Heart", 1],
      ['Plains', 10],
      ['Forest', 10],
      ['Hushwood Verge', 1],
      ['Selesnya Guildgate', 2],
      ['Evolving Wilds', 1],
    ],
  },
  {
    id: 'ecl-wanderwine-tide',
    name: 'Wanderwine Tide',
    colors: ['W', 'U'],
    face: 'Sygg, Wanderwine Wisdom',
    source: 'custom',
    series: 'starter',
    set: 'ecl',
    cards: [
      ['Wanderbrine Trapper', 2],
      ['Wanderbrine Preacher', 3],
      ['Deepchannel Duelist', 2],
      ['Silvergill Mentor', 2],
      ['Deepway Navigator', 1],
      ['Silvergill Peddler', 3],
      ['Meanders Guide', 2],
      ['Eclipsed Merrow', 2],
      ['Wanderwine Distracter', 3],
      ['Merrow Skyswimmer', 3],
      ["Sygg's Command", 1],
      ['Temporal Cleansing', 2],
      ['Spiral into Solitude', 3],
      ['Liminal Hold', 2],
      ['Adept Watershaper', 1],
      ['Champions of the Shoal', 1],
      ['Disruptor of Currents', 1],
      ['Sygg, Wanderwine Wisdom', 1],
      ['Tributary Vaulter', 1],
      ['Plains', 10],
      ['Island', 10],
      ['Azorius Guildgate', 1],
      ['Thriving Isle', 1],
      ['Eclipsed Realms', 1],
      ['Evolving Wilds', 1],
    ],
  },
];
