import type { Decklist } from '../decks.ts';

/** Lorwyn Eclipsed decks (18c), part 3: the enemy pairs, built around their signpost uncommons. See docs/lorwyn-eclipsed-plan.md. */
export const ECL_DECKS_3: Decklist[] = [
  {
    // W/B: -1/-1 counters on big cheap bodies, Reaping Willow and Slumbering Walker bringing things back, Emptiness.
    id: 'ecl-willows-reprieve',
    name: "Willow's Reprieve",
    colors: ['W', 'B'],
    face: 'Emptiness',
    source: 'custom',
    series: 'starter',
    set: 'ecl',
    cards: [
      ['Burdened Stoneback', 3],
      ['Reluctant Dounguard', 3],
      ['Moonlit Lamenter', 2],
      ['Heirloom Auntie', 3],
      ['Gnarlbark Elm', 3],
      ['Reaping Willow', 4],
      ['Prideful Feastling', 2],
      ['Abigale, Eloquent First-Year', 1],
      ['Slumbering Walker', 1],
      ['Emptiness', 1],
      ['Blighted Blackthorn', 2],
      ['Nightmare Sower', 1],
      ['Dream Seizer', 1],
      ['Blight Rot', 2],
      ["Bogslither's Embrace", 2],
      ['Requiting Hex', 1],
      ['Nameless Inversion', 2],
      ['Liminal Hold', 1],
      ['Unbury', 1],
      ['Plains', 12],
      ['Swamp', 12],
    ],
  },
  {
    // R/W: Giants that start with -1/-1 counters, Hovel Hurler handing out flying and +1/+0, Bre and Kirol.
    id: 'ecl-hurlers-and-giants',
    name: 'Hurlers and Giants',
    colors: ['R', 'W'],
    face: 'Bre of Clan Stoutarm',
    source: 'custom',
    series: 'starter',
    set: 'ecl',
    cards: [
      ['Burdened Stoneback', 3],
      ['Reluctant Dounguard', 3],
      ['Brambleback Brute', 3],
      ['Hovel Hurler', 3],
      ['Feisty Spikeling', 3],
      ['Kirol, Attentive First-Year', 1],
      ['Bre of Clan Stoutarm', 1],
      ['Slumbering Walker', 1],
      ['Moonlit Lamenter', 1],
      ['Boldwyr Aggressor', 1],
      ['Catharsis', 1],
      ['Flamekin Gildweaver', 2],
      ['Cinder Strike', 2],
      ['Giantfall', 2],
      ['Sear', 2],
      ['Keep Out', 1],
      ["Riverguard's Reflexes", 2],
      ['Feed the Flames', 1],
      ['Tweeze', 1],
      ['Boulder Dash', 1],
      ['Liminal Hold', 1],
      ['Mountain', 12],
      ['Plains', 12],
    ],
  },
  {
    // R/G: Noggle Robber and friends making Treasure, then big creatures (Vibrance, Aurora Awakener).
    id: 'ecl-treasure-trove-titans',
    name: 'Treasure Trove Titans',
    colors: ['R', 'G'],
    face: 'Aurora Awakener',
    source: 'custom',
    series: 'starter',
    set: 'ecl',
    cards: [
      ['Noggle Robber', 4],
      ['Gangly Stompling', 3],
      ['Flamekin Gildweaver', 3],
      ['Great Forest Druid', 2],
      ['Brambleback Brute', 2],
      ['Pummeler for Hire', 2],
      ['Wildvine Pummeler', 2],
      ['Kulrath Zealot', 2],
      ['Bristlebane Outrider', 2],
      ['Scuzzback Scrounger', 1],
      ['Prismabasher', 1],
      ['Vibrance', 1],
      ['Aurora Awakener', 1],
      ['Sear', 2],
      ['Feed the Flames', 2],
      ['Giantfall', 2],
      ['Reckless Ransacking', 1],
      ['Tend the Sprigs', 2],
      ['Boulder Dash', 1],
      ['Mountain', 12],
      ['Forest', 12],
    ],
  },
  {
    // G/U: vivid. Glister Bairn, Luminollusk, Shinestriker and Prismabasher grow with the colours among permanents.
    id: 'ecl-prismatic-wilds',
    name: 'Prismatic Wilds',
    colors: ['G', 'U'],
    face: 'Wistfulness',
    source: 'custom',
    series: 'starter',
    set: 'ecl',
    cards: [
      ['Glister Bairn', 4],
      ['Chitinous Graspling', 3],
      ['Wistfulness', 1],
      ['Aurora Awakener', 1],
      ['Wildvine Pummeler', 2],
      ['Luminollusk', 2],
      ['Shinestriker', 2],
      ['Prismabasher', 1],
      ['Great Forest Druid', 3],
      ['Pummeler for Hire', 2],
      ['Crossroads Watcher', 2],
      ['Safewright Cavalry', 2],
      ['Bristlebane Outrider', 2],
      ['Stratosoarer', 2],
      ['Rimekin Recluse', 1],
      ['Pitiless Fists', 2],
      ['Assert Perfection', 1],
      ['Prismatic Undercurrents', 1],
      ['Unforgiving Aim', 1],
      ['Rime Chill', 1],
      ['Forest', 12],
      ['Island', 12],
    ],
  },
  {
    // U/B: flash creatures and spells on the opponent's turn (Tome-Skimmer, Nightmare Sower, Unwelcome Sprite).
    id: 'ecl-twilight-ambush',
    name: 'Twilight Ambush',
    colors: ['U', 'B'],
    face: 'Bitterbloom Bearer',
    source: 'custom',
    series: 'starter',
    set: 'ecl',
    cards: [
      ['Voracious Tome-Skimmer', 4],
      ['Mischievous Sneakling', 2],
      ['Glamermite', 2],
      ['Unwelcome Sprite', 1],
      ['Glen Elendra Guardian', 1],
      ['Nightmare Sower', 3],
      ['Bitterbloom Bearer', 1],
      ['Deceit', 1],
      ['Illusion Spinners', 2],
      ['Dream Seizer', 2],
      ['Stratosoarer', 1],
      ['Shimmercreep', 2],
      ['Rooftop Percher', 2],
      ['Rimekin Recluse', 1],
      ['Heirloom Auntie', 2],
      ['Blighted Blackthorn', 2],
      ['Nameless Inversion', 3],
      ['Blight Rot', 2],
      ['Requiting Hex', 1],
      ["Bogslither's Embrace", 1],
      ['Island', 12],
      ['Swamp', 12],
    ],
  },
];
