import type { Decklist } from '../decks.ts';

/**
 * Lorwyn Eclipsed decks (18c), part 2: Goblins, Elves and Elementals. Our own two-colour 60-card decks, scaled up
 * from MTGAZone's Rakdos Goblins, Golgari Elves and Izzet Elementals skeletons (docs/lorwyn-eclipsed-plan.md).
 */
export const ECL_DECKS_2: Decklist[] = [
  {
    id: 'ecl-boggart-rampage',
    name: 'Boggart Rampage',
    colors: ['B', 'R'],
    face: 'Grub, Storied Matriarch',
    source: 'custom',
    series: 'starter',
    set: 'ecl',
    cards: [
      ['Mudbutton Cursetosser', 2],
      ['Bile-Vial Boggart', 2],
      ['Boggart Prankster', 3],
      ['Boggart Cursecrafter', 2],
      ['Eclipsed Boggart', 2],
      ['Sourbread Auntie', 1],
      ['Heirloom Auntie', 3],
      ['Elder Auntie', 3],
      ['Grub, Storied Matriarch', 1],
      ['Taster of Wares', 1],
      ['Chaos Spewer', 3],
      ['Boneclub Berserker', 3],
      ['Sting-Slinger', 1],
      ['Graveshifter', 1],
      ['Tweeze', 3],
      ["Auntie's Sentence", 2],
      ['Feed the Flames', 1],
      ['Boggart Mischief', 1],
      ["Grub's Command", 1],
      ['Blood Crypt', 1],
      ['Eclipsed Realms', 1],
      ['Evolving Wilds', 1],
      ['Swamp', 10],
      ['Mountain', 11],
    ],
  },
  {
    id: 'ecl-gilt-leaf-hunt',
    name: 'Gilt-Leaf Hunt',
    colors: ['B', 'G'],
    face: 'High Perfect Morcant',
    source: 'custom',
    series: 'starter',
    set: 'ecl',
    cards: [
      ['Lys Alana Dignitary', 2],
      ['Scarblade Scout', 3],
      ['Lys Alana Informant', 3],
      ['Creakwood Safewright', 1],
      ['Iron-Shield Elf', 2],
      ['Eclipsed Elf', 2],
      ['Moonglove Extractor', 3],
      ["Morcant's Loyalist", 2],
      ['Safewright Cavalry', 2],
      ["Dawn's Light Archer", 2],
      ['Stoic Grove-Guide', 3],
      ['High Perfect Morcant', 1],
      ['Dawnhand Eulogist', 2],
      ['Great Forest Druid', 1],
      ['Blight Rot', 2],
      ["Bogslither's Embrace", 2],
      ['Assert Perfection', 1],
      ['Midnight Tilling', 1],
      ["Trystan's Command", 1],
      ['Overgrown Tomb', 1],
      ['Eclipsed Realms', 1],
      ['Evolving Wilds', 1],
      ['Swamp', 10],
      ['Forest', 11],
    ],
  },
  {
    id: 'ecl-kulrath-tempest',
    name: 'Kulrath Tempest',
    colors: ['U', 'R'],
    face: 'Ashling, Rekindled',
    source: 'custom',
    series: 'starter',
    set: 'ecl',
    cards: [
      ['Flamebraider', 2],
      ['Summit Sentinel', 3],
      ['Flame-Chain Mauler', 3],
      ['Soulbright Seeker', 1],
      ['Eclipsed Flamekin', 2],
      ['Flaring Cinder', 3],
      ['Ashling, Rekindled', 1],
      ['Rimekin Recluse', 2],
      ['Kulrath Mystic', 1],
      ['Twinflame Travelers', 2],
      ['Stratosoarer', 3],
      ['Kulrath Zealot', 2],
      ['Sunderflock', 1],
      ['Sear', 2],
      ['Tweeze', 3],
      ['Feed the Flames', 2],
      ["Ashling's Command", 1],
      ['Temporal Cleansing', 2],
      ['Steam Vents', 1],
      ['Eclipsed Realms', 1],
      ['Evolving Wilds', 1],
      ['Island', 10],
      ['Mountain', 11],
    ],
  },
];
