import type { Color } from '@mtg/engine';

export interface Decklist {
  /** Stable key, e.g. for saved preferences. */
  id: string;
  name: string;
  colors: Color[];
  /** Card shown on the deck box. */
  face: string;
  /** Where the list comes from ('arena': MTG Arena; 'custom': ours, like the Jump In packets). */
  source: 'arena' | 'custom';
  /**
   * 'starter': two-colour Starter Deck Duel decks; 'colorChallenge': the
   * mono-colour decks Sparky plays; 'jumpIn': two Jump In packets together;
   * 'season': a deck built in Season mode, taken on an expedition.
   */
  series: 'starter' | 'colorChallenge' | 'jumpIn' | 'season' | 'brawl';
  /** A deck from another set than Foundations (shown in its own section). */
  set?: 'blb' | 'msh' | 'msc' | 'fin' | 'stx' | 'sos';
  cards: [name: string, count: number][];
  /** Brawl: the commander (not in `cards`, which hold the other 99). */
  commander?: string;
  /** Strixhaven (13a): cards outside the game that Learn can fetch (the deck's Lessons). */
  sideboard?: [name: string, count: number][];
}

/**
 * MTG Arena's Foundations Starter Decks (Starter Deck Duel, March 2025), from
 * https://mtg.wiki/page/Foundations_Starter_Decks. Face cards are our pick.
 */
export const ARENA_DECKS: Decklist[] = [
  {
    id: 'arcane-aerialists',
    name: 'Arcane Aerialists',
    colors: ['W', 'U'],
    face: 'Giada, Font of Hope',
    source: 'arena',
    series: 'starter',
    cards: [
      ['Aegis Turtle', 2],
      ['Cloudblazer', 2],
      ['Curator of Destinies', 1],
      ['Dazzling Angel', 2],
      ['Empyrean Eagle', 3],
      ['Fog Bank', 2],
      ['Giada, Font of Hope', 1],
      ["Healer's Hawk", 2],
      ['High Fae Trickster', 1],
      ['Inspiring Overseer', 2],
      ['Lyra Dawnbringer', 1],
      ['Serra Angel', 2],
      ['Spectral Sailor', 2],
      ['Vanguard Seraph', 2],
      ['Youthful Valkyrie', 2],
      ['Faebloom Trick', 2],
      ['Chart a Course', 2],
      ['Goldvein Pick', 2],
      ['Stasis Snare', 3],
      ['Plains', 8],
      ['Island', 7],
      ['Azorius Guildgate', 4],
      ['Temple of Enlightenment', 1],
      ['Tranquil Cove', 4],
    ],
  },
  {
    id: 'cat-attack',
    name: 'Cat Attack',
    colors: ['G', 'W'],
    face: 'Arahbo, the First Fang',
    source: 'arena',
    series: 'starter',
    cards: [
      ['Arahbo, the First Fang', 1],
      ['Dawnwing Marshal', 2],
      ['Felidar Savior', 2],
      ['Good-Fortune Unicorn', 3],
      ['Helpful Hunter', 4],
      ['Leonin Vanguard', 3],
      ['Regal Caracal', 1],
      ['Savannah Lions', 3],
      ['Wary Thespian', 4],
      ['Claws Out', 4],
      ['Giant Growth', 2],
      ['Felling Blow', 2],
      ['Angelic Destiny', 1],
      ['Anthem of Champions', 1],
      ['Banishing Light', 2],
      ['Unflinching Courage', 1],
      ['Blossoming Sands', 4],
      ['Forest', 6],
      ['Plains', 9],
      ['Selesnya Guildgate', 4],
      ['Temple of Plenty', 1],
    ],
  },
  {
    id: 'graveyard-gifts',
    name: 'Graveyard Gifts',
    colors: ['U', 'B'],
    face: 'Kiora, the Rising Tide',
    source: 'arena',
    series: 'starter',
    cards: [
      ['Abyssal Harvester', 1],
      ['Arbiter of Woe', 2],
      ['Arcanis the Omnipotent', 1],
      ['Billowing Shriekmass', 2],
      ['Brineborn Cutthroat', 2],
      ['Crow of Dark Tidings', 2],
      ['Dreadwing Scavenger', 4],
      ['Gleaming Barrier', 3],
      ['Kiora, the Rising Tide', 1],
      ['Bake into a Pie', 2],
      ['Essence Scatter', 2],
      ['Opt', 4],
      ['Stab', 4],
      ['Inspiration from Beyond', 2],
      ['Rise of the Dark Realms', 1],
      ['Zombify', 3],
      ['Dimir Guildgate', 4],
      ['Dismal Backwater', 4],
      ['Island', 7],
      ['Swamp', 8],
      ['Temple of Deceit', 1],
    ],
  },
  {
    id: 'learn-from-the-land',
    name: 'Learn From the Land',
    colors: ['G', 'U'],
    face: 'Tatyova, Benthic Druid',
    source: 'arena',
    series: 'starter',
    cards: [
      ['Apothecary Stomper', 2],
      ['Bigfin Bouncer', 2],
      ['Druid of the Cowl', 4],
      ['Elfsworn Giant', 2],
      ['Exclusion Mage', 3],
      ['Llanowar Elves', 3],
      ['Loot, Exuberant Explorer', 1],
      ['Magnigoth Sentry', 2],
      ['Mild-Mannered Librarian', 2],
      ['Mischievous Mystic', 2],
      ['Mossborn Hydra', 1],
      ['Rampaging Baloths', 1],
      ['Spectral Sailor', 2],
      ['Tatyova, Benthic Druid', 2],
      ['Quick Study', 2],
      ['Circuitous Route', 2],
      ['Felling Blow', 2],
      ['Primeval Bounty', 1],
      ['Forest', 10],
      ['Island', 5],
      ['Simic Guildgate', 4],
      ['Temple of Mystery', 1],
      ['Thornwood Falls', 4],
    ],
  },
  {
    id: 'might-of-the-legion',
    name: 'Might of the Legion',
    colors: ['R', 'W'],
    face: 'Aurelia, the Warleader',
    source: 'arena',
    series: 'starter',
    cards: [
      ['Aurelia, the Warleader', 1],
      ['Axgard Cavalry', 2],
      ['Crusader of Odric', 3],
      ['Dauntless Veteran', 2],
      ['Dawnwing Marshal', 2],
      ['Fanatical Firebrand', 3],
      ['Frenzied Goblin', 2],
      ['Krenko, Mob Boss', 1],
      ['Resolute Reinforcements', 2],
      ['Searslicer Goblin', 1],
      ['Serra Angel', 2],
      ['Burst Lightning', 2],
      ['Goblin Surprise', 2],
      ['Valorous Stance', 2],
      ['Dragon Fodder', 2],
      ['Heroic Reinforcements', 2],
      ['Release the Dogs', 2],
      ['Celestial Armor', 1],
      ['Goldvein Pick', 2],
      ['Boros Guildgate', 2],
      ['Mountain', 8],
      ['Plains', 9],
      ['Temple of Triumph', 1],
      ['Wind-Scarred Crag', 4],
    ],
  },
  {
    id: 'morbid-machinations',
    name: 'Morbid Machinations',
    colors: ['B', 'G'],
    face: 'Spinner of Souls',
    source: 'arena',
    series: 'starter',
    cards: [
      ['Cackling Prowler', 2],
      ['Eager Trufflesnout', 2],
      ['Infernal Vessel', 2],
      ['Infestation Sage', 2],
      ['Llanowar Elves', 3],
      ['Midnight Reaper', 1],
      ['Needletooth Pack', 2],
      ['Quilled Greatwurm', 1],
      ['Reassembling Skeleton', 2],
      ['Scavenging Ooze', 1],
      ['Spinner of Souls', 1],
      ['Tragic Banshee', 2],
      ['Vampire Gourmand', 2],
      ['Wardens of the Cycle', 3],
      ['Wary Thespian', 2],
      ['Undying Malice', 2],
      ['Eaten Alive', 2],
      ['Felling Blow', 2],
      ['Vampiric Rites', 2],
      ['Forest', 8],
      ['Golgari Guildgate', 4],
      ['Jungle Hollow', 4],
      ['Swamp', 7],
      ['Temple of Malady', 1],
    ],
  },
  {
    id: 'path-of-power',
    name: 'Path of Power',
    colors: ['R', 'G'],
    face: 'Halana and Alena, Partners',
    source: 'arena',
    series: 'starter',
    cards: [
      ['Ashroot Animist', 1],
      ['Axgard Cavalry', 2],
      ['Beast-Kin Ranger', 2],
      ['Courageous Goblin', 2],
      ['Eager Trufflesnout', 2],
      ['Giant Cindermaw', 2],
      ['Halana and Alena, Partners', 1],
      ['Llanowar Elves', 3],
      ['Mild-Mannered Librarian', 2],
      ['Nessian Hornbeetle', 3],
      ['Ruby, Daring Tracker', 2],
      ['Skyraker Giant', 2],
      ['Spinner of Souls', 1],
      ['Vizier of the Menagerie', 1],
      ['Bulk Up', 1],
      ['Scorching Dragonfire', 2],
      ['Snakeskin Veil', 2],
      ['Bushwhack', 2],
      ['Felling Blow', 2],
      ["Garruk's Uprising", 1],
      ['Forest', 8],
      ['Gruul Guildgate', 4],
      ['Mountain', 7],
      ['Rugged Highlands', 4],
      ['Temple of Abandon', 1],
    ],
  },
  {
    id: 'reckless-raid',
    name: 'Reckless Raid',
    colors: ['B', 'R'],
    face: 'Alesha, Who Laughs at Fate',
    source: 'arena',
    series: 'starter',
    cards: [
      ['Alesha, Who Laughs at Fate', 1],
      ['Battlesong Berserker', 2],
      ['Diregraf Ghoul', 4],
      ['Goblin Boarders', 3],
      ['High-Society Hunter', 1],
      ['Infestation Sage', 3],
      ['Massacre Wurm', 1],
      ['Perforating Artist', 3],
      ['Searslicer Goblin', 1],
      ['Slumbering Cerberus', 3],
      ['Strongbox Raider', 2],
      ['Vampire Gourmand', 3],
      ['Abrade', 3],
      ['Burst Lightning', 2],
      ['Fake Your Own Death', 2],
      ["Hero's Downfall", 2],
      ['Bloodfell Caves', 4],
      ['Mountain', 7],
      ['Rakdos Guildgate', 4],
      ['Swamp', 8],
      ['Temple of Malice', 1],
    ],
  },
  {
    id: 'vampiric-hunger',
    name: 'Vampiric Hunger',
    colors: ['W', 'B'],
    face: 'Elenda, Saint of Dusk',
    source: 'arena',
    series: 'starter',
    cards: [
      ["Ajani's Pridemate", 3],
      ['Cat Collector', 2],
      ['Dazzling Angel', 2],
      ['Elenda, Saint of Dusk', 1],
      ['Fiendish Panda', 2],
      ["Healer's Hawk", 2],
      ['Hinterland Sanctifier', 2],
      ['Inspiring Overseer', 2],
      ['Sanguine Syphoner', 2],
      ['Sun-Blessed Healer', 2],
      ['Twinblade Paladin', 2],
      ['Vampire Nighthawk', 2],
      ['Vengeful Bloodwitch', 2],
      ['Moment of Craving', 2],
      ['Moment of Triumph', 2],
      ['Mortify', 2],
      ['Tribute to Hunger', 2],
      ['Angelic Destiny', 1],
      ['Phyrexian Arena', 1],
      ['Orzhov Guildgate', 4],
      ['Plains', 8],
      ['Scoured Barrens', 4],
      ['Swamp', 7],
      ['Temple of Silence', 1],
    ],
  },
  {
    id: 'wondrous-wizardry',
    name: 'Wondrous Wizardry',
    colors: ['U', 'R'],
    face: 'Niv-Mizzet, Visionary',
    source: 'arena',
    series: 'starter',
    cards: [
      ['Archmage of Runes', 1],
      ['Balmor, Battlemage Captain', 1],
      ['Drake Hatcher', 1],
      ['Enigma Drake', 2],
      ['Ghitu Lavarunner', 4],
      ['Heartfire Immolator', 2],
      ['Mischievous Mystic', 2],
      ['Niv-Mizzet, Visionary', 1],
      ['Ovika, Enigma Goliath', 1],
      ['Tolarian Terror', 3],
      ['Arcane Epiphany', 2],
      ['Burst Lightning', 4],
      ['Dive Down', 3],
      ['Fiery Annihilation', 2],
      ['Opt', 4],
      ['Chart a Course', 3],
      ['Island', 8],
      ['Mountain', 7],
      ['Izzet Guildgate', 4],
      ['Swiftwater Cliffs', 4],
      ['Temple of Epiphany', 1],
    ],
  },
];

/**
 * MTG Arena's Color Challenge decks (August 2020): the five mono-colour decks
 * new players unlock and Sparky plays. From https://mtg.wiki/page/Color_Challenge_decks
 * (upgraded lists; the sideboards are left out). Face cards are our pick.
 */
export const COLOR_CHALLENGE_DECKS: Decklist[] = [
  {
    id: 'keep-the-peace',
    name: 'Keep the Peace',
    colors: ['W'],
    face: 'Angel of Vitality',
    source: 'arena',
    series: 'colorChallenge',
    cards: [
      ['Charmed Stray', 4],
      ['Fencing Ace', 2],
      ['Hallowed Priest', 4],
      ['Impassioned Orator', 3],
      ['Moorland Inquisitor', 2],
      ['Angel of Vitality', 2],
      ['Leonin Warleader', 2],
      ['Serra Angel', 1],
      ['Spiritual Guardian', 1],
      ['Angelic Guardian', 1],
      ['Inspiring Commander', 2],
      ['Goring Ceratops', 1],
      ['Pacifism', 3],
      ['Angelic Reward', 1],
      ['Tactical Advantage', 4],
      ['Confront the Assault', 1],
      ['Bond of Discipline', 1],
      ['Plains', 25],
    ],
  },
  {
    id: 'aerial-domination',
    name: 'Aerial Domination',
    colors: ['U'],
    face: 'Windreader Sphinx',
    source: 'arena',
    series: 'colorChallenge',
    cards: [
      ['Wall of Runes', 2],
      ['Sworn Guardian', 2],
      ['Waterkin Shaman', 3],
      ['Cloudkin Seer', 3],
      ['Warden of Evos Isle', 3],
      ['Octoprophet', 2],
      ['Soulblade Djinn', 2],
      ['Windstorm Drake', 2],
      ['Frilled Sea Serpent', 1],
      ['Riddlemaster Sphinx', 2],
      ['Windreader Sphinx', 1],
      ['Waterknot', 3],
      ['Unsummon', 3],
      ['Glint', 2],
      ['Winged Words', 2],
      ['Sleep', 1],
      ['Overflowing Insight', 1],
      ['Island', 25],
    ],
  },
  {
    id: 'cold-blooded-killers',
    name: 'Cold-Blooded Killers',
    colors: ['B'],
    face: 'Demon of Loathing',
    source: 'arena',
    series: 'colorChallenge',
    cards: [
      ['Sanitarium Skeleton', 2],
      ['Typhoid Rats', 2],
      ['Malakir Cullblade', 3],
      ['Vampire Opportunist', 2],
      ['Mardu Outrider', 2],
      ['Savage Gorger', 3],
      ['Skeleton Archer', 2],
      ['Sengir Vampire', 2],
      ['Soulhunter Rakshasa', 1],
      ['Nightmare', 1],
      ['Demon of Loathing', 2],
      ['Eternal Thirst', 1],
      ['Compound Fracture', 4],
      ['Cruel Cut', 1],
      ['Unlikely Aid', 3],
      ['Murder', 3],
      ['Bad Deal', 1],
      ['Swamp', 25],
    ],
  },
  {
    id: 'goblins-everywhere',
    name: 'Goblins Everywhere!',
    colors: ['R'],
    face: 'Goblin Gang Leader',
    source: 'arena',
    series: 'colorChallenge',
    cards: [
      ['Tin Street Cadet', 3],
      ['Goblin Tunneler', 2],
      ['Nest Robber', 4],
      ['Molten Ravager', 2],
      ['Goblin Gang Leader', 2],
      ['Goblin Trashmaster', 1],
      ['Ogre Battledriver', 2],
      ['Immortal Phoenix', 1],
      ['Volcanic Dragon', 1],
      ['Siege Dragon', 2],
      ['Raid Bombardment', 2],
      ['Shock', 3],
      ['Storm Strike', 2],
      ['Burn Bright', 2],
      ['Inescapable Blaze', 2],
      ['Goblin Gathering', 4],
      ['Mountain', 25],
    ],
  },
  {
    id: 'large-and-in-charge',
    name: 'Large and in Charge',
    colors: ['G'],
    face: 'Gigantosaurus',
    source: 'arena',
    series: 'colorChallenge',
    cards: [
      ['Jungle Delver', 3],
      ['Ilysian Caryatid', 4],
      ['Woodland Mystic', 2],
      ['Wildwood Patrol', 2],
      ['Baloth Packhunter', 4],
      ['Prized Unicorn', 1],
      ['Rumbling Baloth', 2],
      ['World Shaper', 1],
      ['Gigantosaurus', 2],
      ['Sentinel Spider', 2],
      ['Affectionate Indrik', 2],
      ['Rampaging Brontodon', 2],
      ['Colossal Majesty', 2],
      ['Epic Proportions', 1],
      ['Stony Strength', 2],
      ['Rabid Bite', 3],
      ['Forest', 25],
    ],
  },
];

/**
 * Our Bloomburrow decks, built like the Foundations starter decks (two
 * colours, 36 spells and 24 lands) so they play against them.
 */
export const BLOOMBURROW_DECKS: Decklist[] = [
  {
    id: 'blb-forage-and-feast',
    name: 'Forage and Feast',
    colors: ['B', 'G'],
    face: 'Camellia, the Seedmiser',
    source: 'custom',
    series: 'starter',
    set: 'blb',
    cards: [
      ['Agate-Blade Assassin', 2],
      ['Bakersbane Duo', 3],
      ['Vinereap Mentor', 3],
      ['Bonebind Orator', 2],
      ['Bushy Bodyguard', 2],
      ['Daggerfang Duo', 3],
      ['Curious Forager', 2],
      ['Honored Dreyleader', 2],
      ['Camellia, the Seedmiser', 1],
      ['Treetop Sentries', 2],
      ['Thornplate Intimidator', 2],
      ["Wick's Patrol", 1],
      ['Feed the Cycle', 2],
      ['Savor', 3],
      ['Nocturnal Hunger', 2],
      ['Longstalk Brawl', 2],
      ['Consumed by Greed', 1],
      ["Hazel's Nocturne", 1],
      ['Forest', 8],
      ['Swamp', 7],
      ['Golgari Guildgate', 4],
      ['Jungle Hollow', 4],
      ['Temple of Malady', 1],
    ],
  },
  {
    id: 'blb-warren-rally',
    name: 'Warren Rally',
    colors: ['G', 'W'],
    face: 'Warren Warleader',
    source: 'custom',
    series: 'starter',
    set: 'blb',
    cards: [
      ['Seasoned Warrenguard', 3],
      ['Brave-Kin Duo', 2],
      ['Nettle Guard', 2],
      ['Warren Elder', 2],
      ['Burrowguard Mentor', 2],
      ['Finneas, Ace Archer', 1],
      ['Intrepid Rabbit', 3],
      ['Harvestrite Host', 2],
      ['Druid of the Spade', 2],
      ['Hazardroot Herbalist', 2],
      ['Warren Warleader', 1],
      ['Treeguard Duo', 2],
      ['Carrot Cake', 2],
      ['Hop to It', 2],
      ['Crumb and Get It', 2],
      ["Mabel's Mettle", 2],
      ['Rabbit Response', 1],
      ['Repel Calamity', 2],
      ['Banishing Light', 1],
      ['Plains', 8],
      ['Forest', 7],
      ['Selesnya Guildgate', 4],
      ['Blossoming Sands', 4],
      ['Temple of Plenty', 1],
    ],
  },
  {
    id: 'blb-night-flight',
    name: 'Night Flight',
    colors: ['W', 'B'],
    face: 'Zoraline, Cosmos Caller',
    source: 'custom',
    series: 'starter',
    set: 'blb',
    cards: [
      ['Lifecreed Duo', 3],
      ['Starscape Cleric', 3],
      ['Brightblade Stoat', 2],
      ['Essence Channeler', 1],
      ['Moonrise Cleric', 3],
      ['Moonstone Harbinger', 2],
      ['Starlit Soothsayer', 3],
      ['Zoraline, Cosmos Caller', 1],
      ['Wax-Wane Witness', 2],
      ['Star Charter', 2],
      ['Starseer Mentor', 2],
      ['Glidedive Duo', 2],
      ['Sonar Strike', 2],
      ['Fell', 2],
      ['Diresight', 2],
      ['Sinister Monolith', 2],
      ['Lunar Convocation', 1],
      ['Starfall Invocation', 1],
      ['Plains', 8],
      ['Swamp', 7],
      ['Orzhov Guildgate', 4],
      ['Scoured Barrens', 4],
      ['Temple of Silence', 1],
    ],
  },
  {
    id: 'blb-valiant-squeak',
    name: 'Valiant Squeak',
    colors: ['R', 'W'],
    face: 'Mabel, Heir to Cragflame',
    source: 'custom',
    series: 'starter',
    set: 'blb',
    cards: [
      ['Heartfire Hero', 4],
      ['Flowerfoot Swordmaster', 2],
      ['Emberheart Challenger', 1],
      ['Whiskerquill Scribe', 2],
      ['Manifold Mouse', 1],
      ['Nettle Guard', 2],
      ['Seedglaive Mentor', 3],
      ['Mabel, Heir to Cragflame', 1],
      ['Mouse Trapper', 2],
      ['Thistledown Players', 2],
      ['Brambleguard Captain', 2],
      ['Whiskervale Forerunner', 1],
      ['Veteran Guardmouse', 2],
      ['Might of the Meek', 3],
      ['Rabid Gnaw', 2],
      ["Mabel's Mettle", 2],
      ['War Squeak', 2],
      ['Blooming Blast', 2],
      ['Mountain', 8],
      ['Plains', 7],
      ['Boros Guildgate', 4],
      ['Wind-Scarred Crag', 4],
      ['Temple of Triumph', 1],
    ],
  },
  {
    id: 'blb-scorching-scales',
    name: 'Scorching Scales',
    colors: ['B', 'R'],
    face: 'Gev, Scaled Scorch',
    source: 'custom',
    series: 'starter',
    set: 'blb',
    cards: [
      ['Iridescent Vinelasher', 2],
      ['Ravine Raider', 2],
      ['Hired Claw', 2],
      ['Agate-Blade Assassin', 3],
      ['Steampath Charger', 3],
      ['Fireglass Mentor', 2],
      ['Gev, Scaled Scorch', 1],
      ['Cindering Cutthroat', 2],
      ['Thought-Stalker Warlock', 2],
      ['Hearthborn Battler', 1],
      ['Valley Flamecaller', 1],
      ['Frilled Sparkshooter', 2],
      ['Reptilian Recruiter', 1],
      ['Scales of Shale', 2],
      ['Fell', 1],
      ['Agate Assault', 2],
      ['Blooming Blast', 2],
      ['Playful Shove', 2],
      ['Savor', 1],
      ['Nocturnal Hunger', 2],
      ['Mountain', 8],
      ['Swamp', 7],
      ['Rakdos Guildgate', 4],
      ['Bloodfell Caves', 4],
      ['Temple of Malice', 1],
    ],
  },
  {
    id: 'blb-rat-pack',
    name: 'Rat Pack',
    colors: ['U', 'B'],
    face: 'Vren, the Relentless',
    source: 'custom',
    series: 'starter',
    set: 'blb',
    cards: [
      ['Thought Shucker', 2],
      ['Shoreline Looter', 2],
      ['Persistent Marshstalker', 3],
      ['Azure Beastbinder', 1],
      ['Nightwhorl Hermit', 2],
      ['Mindwhisker', 2],
      ['Daggerfang Duo', 3],
      ['Tidecaller Mentor', 2],
      ['Mind Drill Assailant', 2],
      ['Wick, the Whorled Mind', 1],
      ['Vren, the Relentless', 1],
      ['Thornplate Intimidator', 2],
      ["Wick's Patrol", 1],
      ['Psychic Whorl', 2],
      ['Fell', 2],
      ['Into the Flood Maw', 2],
      ['Spellgyre', 1],
      ["Long River's Pull", 1],
      ['Dire Downdraft', 2],
      ['Run Away Together', 1],
      ['Diresight', 1],
      ['Island', 8],
      ['Swamp', 7],
      ['Dimir Guildgate', 4],
      ['Dismal Backwater', 4],
      ['Temple of Deceit', 1],
    ],
  },
  {
    id: 'blb-otter-antics',
    name: 'Otter Antics',
    colors: ['U', 'R'],
    face: 'Valley Floodcaller',
    source: 'custom',
    series: 'starter',
    set: 'blb',
    cards: [
      ['Stormcatch Mentor', 2],
      ['Coruscation Mage', 3],
      ['Thundertrap Trainer', 2],
      ['Kindlespark Duo', 3],
      ['Tempest Angler', 3],
      ['Harnesser of Storms', 1],
      ['Quaketusk Boar', 2],
      ['Valley Floodcaller', 1],
      ['Kitsa, Otterball Elite', 1],
      ['Stormsplitter', 1],
      ["Alania's Pathmaker", 2],
      ['Eddymurk Crab', 1],
      ['Playful Shove', 2],
      ['Take Out the Trash', 3],
      ['Blooming Blast', 2],
      ['Agate Assault', 2],
      ['Conduct Electricity', 1],
      ['Otterball Antics', 2],
      ['Dazzling Denial', 1],
      ["Sazacap's Brew", 1],
      ['Island', 8],
      ['Mountain', 7],
      ['Izzet Guildgate', 4],
      ['Swiftwater Cliffs', 4],
      ['Temple of Epiphany', 1],
    ],
  },
  {
    id: 'blb-lilypad-leap',
    name: 'Lilypad Leap',
    colors: ['G', 'U'],
    face: 'Clement, the Worrywort',
    source: 'custom',
    series: 'starter',
    set: 'blb',
    cards: [
      ['Sunshower Druid', 2],
      ['Mistbreath Elder', 1],
      ['Valley Mightcaller', 1],
      ['Bellowing Crier', 2],
      ['Pond Prophet', 3],
      ['Three Tree Scribe', 2],
      ['Dour Port-Mage', 1],
      ['Stickytongue Sentinel', 2],
      ['Long River Lurker', 2],
      ['Waterspout Warden', 2],
      ['Clement, the Worrywort', 1],
      ['Clifftop Lookout', 2],
      ['Splash Lasher', 2],
      ['Lilysplash Mentor', 2],
      ['Dreamdew Entrancer', 1],
      ['Splash Portal', 2],
      ['Polliwallop', 2],
      ['Hivespine Wolverine', 1],
      ['Galewind Moose', 1],
      ['Run Away Together', 2],
      ['Pawpatch Formation', 2],
      ['Forest', 8],
      ['Island', 7],
      ['Simic Guildgate', 4],
      ['Thornwood Falls', 4],
      ['Temple of Mystery', 1],
    ],
  },
  {
    id: 'blb-sky-flock',
    name: 'Sky Flock',
    colors: ['W', 'U'],
    face: 'Kastral, the Windcrested',
    source: 'custom',
    series: 'starter',
    set: 'blb',
    cards: [
      ['Plumecreed Escort', 2],
      ['Finch Formation', 2],
      ['Shrike Force', 3],
      ['Jackdaw Savior', 1],
      ['Plumecreed Mentor', 3],
      ['Seedpod Squire', 3],
      ['Salvation Swan', 1],
      ['Pileated Provisioner', 2],
      ['Skyskipper Duo', 2],
      ['Knightfisher', 2],
      ['Driftgloom Coyote', 1],
      ['Kastral, the Windcrested', 1],
      ['Dazzling Denial', 2],
      ['Feather of Flight', 2],
      ['Repel Calamity', 2],
      ['Banishing Light', 2],
      ['Parting Gust', 2],
      ['Into the Flood Maw', 2],
      ["Mabel's Mettle", 1],
      ['Plains', 8],
      ['Island', 7],
      ['Azorius Guildgate', 4],
      ['Tranquil Cove', 4],
      ['Temple of Enlightenment', 1],
    ],
  },
  {
    id: 'blb-raccoon-rumble',
    name: 'Raccoon Rumble',
    colors: ['R', 'G'],
    face: 'Muerra, Trash Tactician',
    source: 'custom',
    series: 'starter',
    set: 'blb',
    cards: [
      ['Three Tree Rootweaver', 2],
      ['Bakersbane Duo', 2],
      ['Bark-Knuckle Boxer', 2],
      ['Wandertale Mentor', 3],
      ['Brazen Collector', 2],
      ['Raccoon Rallier', 1],
      ['Brambleguard Veteran', 2],
      ['Roughshod Duo', 2],
      ['Byway Barterer', 1],
      ['Muerra, Trash Tactician', 1],
      ['Rust-Shield Rampager', 2],
      ['Teapot Slinger', 2],
      ['Junkblade Bruiser', 2],
      ['Quaketusk Boar', 1],
      ['Take Out the Trash', 2],
      ['Heaped Harvest', 1],
      ['Overprotect', 2],
      ["Hunter's Talent", 2],
      ["Hoarder's Overflow", 1],
      ['Blooming Blast', 2],
      ['Rabid Gnaw', 1],
      ['Mountain', 8],
      ['Forest', 7],
      ['Gruul Guildgate', 4],
      ['Rugged Highlands', 4],
      ['Temple of Abandon', 1],
    ],
  },
];

/**
 * Our own Marvel Super Heroes (MSH) decks, built like the starter decks (36
 * spells, 24 lands) and played against them.
 */
export const MARVEL_DECKS: Decklist[] = [
  {
    id: 'msh-heroes-unite',
    name: 'Heroes Unite',
    colors: ['R', 'W'],
    face: 'Thor Odinson',
    source: 'custom',
    series: 'starter',
    set: 'msh',
    cards: [
      ['Agent Maria Hill', 1],
      ['Agent of Atlas', 3],
      ['Kree Commandos', 2],
      ['Brave Brawler', 3],
      ['Hero in Training', 2],
      ['Crimson Operative', 2],
      ['Volcanic Villain', 2],
      ['Wakandan Drone Flock', 2],
      ['Okoye, Dora Milaje Leader', 1],
      ['Human Torch, Johnny Storm', 1],
      ['War Machine, Legacy of Iron', 1],
      ['Thor Odinson', 1],
      ['Monica Rambeau', 1],
      ['Helicarrier Strike', 2],
      ['HULK SMASH!', 2],
      ['Repulsor Blast', 2],
      ['Lightning Strike', 3],
      ['Team Tactics', 1],
      ['Web Up', 2],
      ['Super Villain Lockup', 2],
      ['Plains', 8],
      ['Mountain', 8],
      ['Asgardian Citadel', 4],
      ['Boros Guildgate', 3],
      ['Temple of Triumph', 1],
    ],
  },
  {
    id: 'msh-villainous-schemes',
    name: 'Villainous Schemes',
    colors: ['U', 'B'],
    face: 'Kang, Temporal Tyrant',
    source: 'custom',
    series: 'starter',
    set: 'msh',
    cards: [
      ['Red Room Recruit', 3],
      ['Agents of HYDRA', 2],
      ['HYDRA Troopers', 2],
      ['Ninja of the Hand', 2],
      ['Giant-Sized Flying Ant', 2],
      ["Kingpin's Enforcers", 2],
      ['Unliving Legionnaire', 2],
      ['Madame Masque', 1],
      ['Kang, Temporal Tyrant', 1],
      ['Baron Strucker, HYDRA Overlord', 1],
      ['Ghost, Spectral Saboteur', 1],
      ['Crossbones, Malicious Mercenary', 1],
      ['Yellowjacket, Heartless Marauder', 1],
      ["Trickster's Stratagem", 1],
      ['Visions of Villainy', 2],
      ['Dark Deed', 2],
      ['Hour of Defeat', 2],
      ['Depower', 2],
      ["Widow's Bite", 2],
      ['Cruel Alliance', 2],
      ['Futurist Forge', 1],
      ['We Say Thee Nay!', 1],
      ['Island', 8],
      ['Swamp', 8],
      ['A.I.M. Labs', 4],
      ['Dimir Guildgate', 3],
      ['Temple of Deceit', 1],
    ],
  },
  {
    id: 'msh-gamma-smash',
    name: 'Gamma Smash',
    colors: ['R', 'G'],
    face: 'Hulk, Gamma Goliath',
    source: 'custom',
    series: 'starter',
    set: 'msh',
    cards: [
      ['Wakandan Royal Guard', 2],
      ['Undercover Skrull', 2],
      ['White Tiger, Ava Ayala', 1],
      ['Volcanic Villain', 2],
      ["K'un-Lun Warrior", 2],
      ['Human Torch, Johnny Storm', 1],
      ["Ant-Man's Army", 2],
      ['Crimson Operative', 2],
      ['Pet Avengers', 2],
      ['Red Hulk', 1],
      ['The Thing, Ben Grimm', 1],
      ['Hercules, Prince of Power', 2],
      ['Abomination, Terrifying Titan', 1],
      ['Hulk, Gamma Goliath', 1],
      ['She-Hulk, Jade Defender', 1],
      ['Giant Growth', 2],
      ['Go Nuts!', 2],
      ['Lightning Strike', 4],
      ['HULK SMASH!', 2],
      ['Repulsor Blast', 2],
      ['Restorative Technique', 1],
      ['Mountain', 8],
      ['Forest', 8],
      ['Los Diablos Missile Base', 4],
      ['Gruul Guildgate', 3],
      ['Temple of Abandon', 1],
    ],
  },
  {
    id: 'msh-heroes-of-wakanda',
    name: 'Heroes of Wakanda',
    colors: ['G', 'W'],
    face: 'Black Panther, Vanguard',
    source: 'custom',
    series: 'starter',
    set: 'msh',
    cards: [
      ['Agent of Atlas', 2],
      ['Hero in Training', 2],
      ['Brave Brawler', 2],
      ['Wakandan Royal Guard', 3],
      ['Wakandan Drone Flock', 2],
      ['Pet Avengers', 2],
      ['Okoye, Dora Milaje Leader', 1],
      ['Black Panther, Vanguard', 1],
      ['Spider-Man, To the Rescue', 1],
      ['White Tiger, Ava Ayala', 1],
      ['Tigra, Feline Fury', 1],
      ["Ant-Man's Army", 1],
      ['Knight of Wundagore', 1],
      ['Giant Growth', 2],
      ['The Thing, Ben Grimm', 1],
      ['Hercules, Prince of Power', 1],
      ['Helicarrier Strike', 2],
      ['Web Up', 2],
      ['Super Villain Lockup', 2],
      ['Go Nuts!', 2],
      ['Restorative Technique', 1],
      ['Panther Pounce', 2],
      ["Murdock's Crusade", 1],
      ['Plains', 8],
      ['Forest', 8],
      ['Birnin Zana Plaza', 4],
      ['Selesnya Guildgate', 3],
      ['Temple of Plenty', 1],
    ],
  },
  {
    id: 'msh-lone-agents',
    name: 'Lone Agents',
    colors: ['W', 'B'],
    face: 'Black Widow, Double Agent',
    source: 'custom',
    series: 'starter',
    set: 'msh',
    cards: [
      ['Agent of Atlas', 2],
      ['Agents of S.H.I.E.L.D.', 2],
      ['Hero in Training', 2],
      ['Black Widow, Double Agent', 2],
      ['Luke Cage, Power Man', 1],
      ["Kingpin's Enforcers", 2],
      ['Agents of HYDRA', 2],
      ['Unliving Legionnaire', 2],
      ['Kree Commandos', 2],
      ['Crossbones, Malicious Mercenary', 1],
      ['Red Room Recruit', 1],
      ['Dark Deed', 2],
      ['Hour of Defeat', 3],
      ['Cruel Alliance', 1],
      ['Web Up', 2],
      ['Super Villain Lockup', 2],
      ['Helicarrier Strike', 2],
      ['Visions of Villainy', 1],
      ["Widow's Bite", 1],
      ['Wakandan Drone Flock', 2],
      ['Okoye, Dora Milaje Leader', 1],
      ['Plains', 8],
      ['Swamp', 8],
      ['Fisk Tower', 4],
      ['Orzhov Guildgate', 3],
      ['Temple of Silence', 1],
    ],
  },
  {
    id: 'msh-hydra-rising',
    name: 'HYDRA Rising',
    colors: ['B', 'R'],
    face: 'Madame Hydra',
    source: 'custom',
    series: 'starter',
    set: 'msh',
    cards: [
      ['Red Room Recruit', 2],
      ['Agents of HYDRA', 2],
      ['Yellowjacket, Heartless Marauder', 1],
      ['HYDRA Troopers', 2],
      ['Volcanic Villain', 2],
      ['Ninja of the Hand', 2],
      ['Crimson Operative', 2],
      ['Madame Hydra', 1],
      ['Bullseye, Death Dealer', 1],
      ['Crossbones, Malicious Mercenary', 1],
      ['Madame Masque', 1],
      ['Lightning Strike', 4],
      ['Dark Deed', 2],
      ['Hour of Defeat', 2],
      ['Hire a Crew', 1],
      ['Visions of Villainy', 1],
      ["Widow's Bite", 1],
      ['Repulsor Blast', 1],
      ['HULK SMASH!', 1],
      ['Cruel Alliance', 1],
      ['Unliving Legionnaire', 2],
      ['Red Hulk', 1],
      ['Avengers: Under Siege', 1],
      ['Elektra, Daughter of the Hand', 1],
      ['Swamp', 8],
      ['Mountain', 8],
      ["Hell's Kitchen", 4],
      ['Rakdos Guildgate', 3],
      ['Temple of Malice', 1],
    ],
  },
  {
    id: 'msh-stark-tech',
    name: 'Stark Tech',
    colors: ['U', 'R'],
    face: 'Iron Man, Master of Machines',
    source: 'custom',
    series: 'starter',
    set: 'msh',
    cards: [
      ['S.H.I.E.L.D. Deployment Drone', 2],
      ['H.E.R.B.I.E. Scout Unit', 2],
      ['Crimson Operative', 2],
      ['Ultron Drone', 2],
      ['Iron Man, Master of Machines', 2],
      ['Giant-Sized Flying Ant', 3],
      ['Lightning Strike', 4],
      ['Repulsor Blast', 3],
      ['We Say Thee Nay!', 1],
      ['Human Torch, Johnny Storm', 2],
      ['Red Hulk', 2],
      ['Volcanic Villain', 2],
      ['Falcon, Winged Wonder', 2],
      ['Atlantean Cavalry', 2],
      ["Trickster's Stratagem", 2],
      ['Thor, God of Thunder', 1],
      ['Tony Stark', 1],
      ['Fin Fang Foom', 1],
      ['Island', 8],
      ['Mountain', 8],
      ['Stark Industries', 4],
      ['Izzet Guildgate', 3],
      ['Temple of Epiphany', 1],
    ],
  },
  {
    id: 'msh-sky-patrol',
    name: 'Sky Patrol',
    colors: ['W', 'U'],
    face: 'Falcon, Winged Wonder',
    source: 'custom',
    series: 'starter',
    set: 'msh',
    cards: [
      ['Kree Commandos', 3],
      ['Wakandan Drone Flock', 3],
      ['S.H.I.E.L.D. Deployment Drone', 2],
      ['Giant-Sized Flying Ant', 3],
      ['Falcon, Winged Wonder', 2],
      ['Hero in Training', 2],
      ['Agent of Atlas', 2],
      ['Bold Biochemist', 1],
      ['Okoye, Dora Milaje Leader', 2],
      ['Helicarrier Strike', 2],
      ['Web Up', 3],
      ['Super Villain Lockup', 3],
      ['Depower', 2],
      ['We Say Thee Nay!', 1],
      ['Panther Pounce', 1],
      ["Trickster's Stratagem", 1],
      ['Super Suit', 1],
      ['Take Up the Shield', 1],
      ["Murdock's Crusade", 1],
      ['Plains', 8],
      ['Island', 8],
      ['Avengers Hangar', 4],
      ['Azorius Guildgate', 3],
      ['Temple of Enlightenment', 1],
    ],
  },
  {
    id: 'msh-growing-pains',
    name: 'Growing Pains',
    colors: ['G', 'U'],
    face: 'Ant-Man, Colony Commander',
    source: 'custom',
    series: 'starter',
    set: 'msh',
    cards: [
      ['Ant-Man, Colony Commander', 2],
      ['Wakandan Royal Guard', 3],
      ['Pet Avengers', 3],
      ['Giant-Sized Flying Ant', 3],
      ['Falcon, Winged Wonder', 2],
      ['Hercules, Prince of Power', 2],
      ['She-Hulk, Jade Defender', 2],
      ['Go Nuts!', 3],
      ["Trickster's Stratagem", 2],
      ['Punishing Punch', 3],
      ['The Thing, Ben Grimm', 2],
      ["Ant-Man's Army", 2],
      ['Abomination, Terrifying Titan', 3],
      ['Tigra, Feline Fury', 2],
      ['Serpent Specialist', 2],
      ['Forest', 10],
      ['Island', 9],
      ['Pym Technologies', 4],
      ['Temple of Mystery', 1],
    ],
  },
  {
    id: 'msh-savage-uprising',
    name: 'Savage Uprising',
    colors: ['B', 'G'],
    face: 'Killmonger, Scourge of Wakanda',
    source: 'custom',
    series: 'starter',
    set: 'msh',
    cards: [
      ['HYDRA Troopers', 2],
      ["Ant-Man's Army", 2],
      ['Ninja of the Hand', 2],
      ["Kingpin's Enforcers", 2],
      ['Killmonger, Scourge of Wakanda', 2],
      ['Unliving Legionnaire', 3],
      ['Pet Avengers', 2],
      ['Hour of Defeat', 3],
      ['Dark Deed', 2],
      ['Cruel Alliance', 2],
      ['Punishing Punch', 3],
      ['The Thing, Ben Grimm', 1],
      ['Wakandan Royal Guard', 2],
      ['Crossbones, Malicious Mercenary', 1],
      ['Abomination, Terrifying Titan', 2],
      ['Red Room Recruit', 2],
      ['The Serpent Society', 1],
      ['The Coming of Galactus', 1],
      ['Elektra, Daughter of the Hand', 1],
      ['Swamp', 10],
      ['Forest', 9],
      ['Subterranean Cavern', 4],
      ['Temple of Malady', 1],
    ],
  },
];

/**
 * Brawl decks (Arena's 1v1 Commander): the four Marvel Super Heroes Commander
 * precons as printed (from https://mtg.wtf/deck/msc/<slug>), plus a test deck
 * of our own built from Foundations and Bloomburrow cards and the precons'
 * shared staples. 100 cards, singleton, within the commander's colours.
 */
export const MARVEL_BRAWL_DECKS: Decklist[] = [
  {
    id: 'msc-avengers-assemble',
    name: 'Avengers Assemble',
    colors: ['W', 'U', 'R'],
    face: 'Captain America, Team Leader',
    commander: 'Captain America, Team Leader',
    source: 'arena',
    series: 'brawl',
    set: 'msc',
    cards: [
      ...[
        'Avenge',
        'Falcon and Redwing',
        'Hercules, Olympian Hero',
        'Heroic Return',
        'Heroic Sacrifice',
        'Methods of the Mighty',
        'Winter Soldier, Reborn Avenger',
        'Iron Man, Armored Avenger',
        "Jarvis, Earth's Mightiest Butler",
        'Professor Hulk',
        'The Wasp, Winsome Avenger',
        'West Coast Expansion',
        'Firebird, Blazing Ranger',
        'Photon, Mighty Marvel',
        'She-Hulk, Wallbreaker',
        'War Machine, Avenging Arsenal',
        'Ant-Man, Elusive Avenger',
        'Black Widow, Agile Avenger',
        'Captain Marvel, Apex Avenger',
        'Director Nick Fury',
        'Hawkeye, Avenging Archer',
        'Love on the Battlefield',
        'Quicksilver, Speedster',
        'Scarlet Witch, Chaotic Avenger',
        'Shang-Chi and the Ten Rings',
        'Avengers Quinjet',
        'Hulkbuster Armor',
        'Jocasta, Automaton Avenger',
        'Vision, Synthezoid Avenger',
        'Austere Command',
        'Bastion Protector',
        'Dismantling Wave',
        'Folk Hero',
        'Gift of Immortality',
        'Kindred Discovery',
        'Door of Destinies',
        'Metallic Mimic',
        'Tome of Legends',
        'Clifftop Retreat',
        'Coastal Peak',
        'Exotic Orchard',
        'Frostboil Snarl',
        'Furycalm Snarl',
        'Glacial Fortress',
        'Glittering Massif',
        'Irrigated Farmland',
        'Plaza of Heroes',
        'Port Town',
        'Prairie Stream',
        'Radiant Summit',
        'Scavenger Grounds',
        'Scorched Geyser',
        'Spectator Seating',
        'Sulfur Falls',
        'Raise the Palisade',
        "Thor, Asgard's Avenger",
        'Captain Mar-Vell, Space-Born',
        'Patriot, Shield Wielder',
        'Speed, Young Avenger',
        'Captain America, Living Legend',
        'Avengers Tower',
        'Destroy Evil',
        'Make Your Move',
        'Swords to Plowshares',
        'Arcane Denial',
        'Reconnaissance Mission',
        'Rip Apart',
        'Arcane Signet',
        "Hero's Blade",
        'Relic of Legends',
        'Sol Ring',
        'Talisman of Conviction',
        'Talisman of Creativity',
        'Talisman of Progress',
        'Thought Vessel',
        'Command Tower',
        'Mystic Monastery',
        'Path of Ancestry',
        'Secluded Courtyard',
        'Unclaimed Territory',
        'Fellwar Stone',
        "Herald's Horn",
        'Rescue, Pepper Potts',
      ].map((name): [string, number] => [name, 1]),
      ['Plains', 6],
      ['Island', 5],
      ['Mountain', 5],
    ],
  },
  {
    id: 'msc-wakanda-forever',
    name: 'Wakanda Forever',
    colors: ['G', 'W'],
    face: "T'Challa, the Black Panther",
    commander: "T'Challa, the Black Panther",
    source: 'arena',
    series: 'brawl',
    set: 'msc',
    cards: [
      ...[
        'Dora Milaje Elite',
        'Everett K. Ross, Hapless Attaché',
        'Hatut Zeraze Strike Force',
        "King Solomon's Frogs",
        'Midnight Angel Armor',
        'Queen Mother Ramonda',
        'Royal Talon Fighter Jet',
        'The Spear of Bashenga',
        'Ancestral Communion',
        'Fight for the Throne',
        "M'Baku, Jabari Chieftain",
        'Nakia, Wakandan Operative',
        "W'Kabi, Shield of the Nation",
        'Wakanda Forever!',
        'Zuri, Warrior of Wakanda',
        'Bast, Panther Goddess',
        'Okoye, Mighty and Adored',
        'Shuri, the Black Panther',
        'Storm, Queen of Wakanda',
        "T'Chaka, Venerable King",
        'Heart-Shaped Herb',
        'Kimoyo Beads',
        "N'Yami-Class Mother Ship",
        'Panther Habit',
        'Panther Robot',
        "Shuri's Fabricator",
        'Vibranium Mining Mech',
        'Vibranium Strike Gauntlets',
        'The Great Mound',
        'Divine Visitation',
        'Loyal Retainers',
        'Martial Coup',
        'Vanquish the Horde',
        'Birds of Paradise',
        'Conduit of Worlds',
        'Greater Good',
        "Nature's Lore",
        'Overwhelming Stampede',
        'Coveted Jewel',
        'Gilded Lotus',
        'Helm of the Host',
        'Metalwork Colossus',
        'Solemn Simulacrum',
        'Trading Post',
        'Bountiful Promenade',
        'Canopy Vista',
        'Fortified Village',
        'Razorverge Thicket',
        'Scattered Groves',
        'Scavenger Grounds',
        'Sungrass Prairie',
        'Sunpetal Grove',
        'Throne of the High City',
        'Scourglass',
        'Fleecemane Lion',
        'Hammer of Nazahn',
        "Mind's Eye",
        'Sword of the Animist',
        'Thran Dynamo',
        'Dispatch',
        'Generous Gift',
        'Ingenious Smith',
        'Palace Jailer',
        'Valorous Stance',
        'Beast Within',
        'Harmonize',
        'Loyal Guardian',
        'Arcane Signet',
        'Meteor Golem',
        'Sol Ring',
        'Whispersilk Cloak',
        'Command Tower',
        'Evolving Wilds',
        'Path of Ancestry',
        'Terramorphic Expanse',
      ].map((name): [string, number] => [name, 1]),
      ['Plains', 12],
      ['Forest', 12],
    ],
  },
  {
    id: 'msc-the-fantastic-four',
    name: 'The Fantastic Four',
    colors: ['W', 'U', 'R', 'G'],
    face: 'Invisible Woman',
    commander: 'Invisible Woman',
    source: 'arena',
    series: 'brawl',
    set: 'msc',
    cards: [
      ...[
        'Mister Fantastic',
        'Human Torch',
        'The Thing',
        'Galactus, Devourer of Worlds',
        "Silver Surfer, Galactus's Herald",
        'Invisible Force Field',
        'Ultimate Nullification',
        'Council of Reeds',
        'Fantastic Elasticity',
        'Lockjaw, Slobbering Teleporter',
        'Valeria Richards, Precocious',
        'Alicia Masters, Skilled Sculptor',
        'Flame On!',
        'Franklin Richards, Ascendant',
        'Nova Flame',
        "It's Clobberin' Time!",
        'Medusa, Inhuman Queen',
        'Black Bolt, Inhuman King',
        'Cosmic Crucible',
        'Crystal, Inhuman Princess',
        'Dragon Man, Reformed Robot',
        'First Family',
        'Namor, Atlantean King',
        'Power Pack',
        'Willie Lumpkin, Postman',
        'The Fantasticar',
        'H.E.R.B.I.E., Lovable Robot',
        'Negative Zone Portal',
        'Unstable Molecule Suit',
        'Cleansing Nova',
        'Clever Concealment',
        'Collective Effort',
        'Monologue Tax',
        'Promise of Loyalty',
        'Tragic Arrogance',
        'Quantum Misalignment',
        'Recurring Insight',
        'Into the Time Vortex',
        'Seize the Day',
        'Path of Discovery',
        'Galvanic Iteration',
        'Taunt from the Rampart',
        'Whirlwind of Thought',
        'Chromatic Lantern',
        'Mirage Mirror',
        'Canopy Vista',
        'Cinder Glade',
        'Clifftop Retreat',
        'Exotic Orchard',
        'Fabled Passage',
        'Glacial Fortress',
        'Hinterland Harbor',
        'Prairie Stream',
        'Radiant Summit',
        'Rejuvenating Springs',
        'Rootbound Crag',
        'Scorched Geyser',
        'Sodden Verdure',
        'Sulfur Falls',
        'Sunpetal Grove',
        'Terramorphic Expanse',
        "Mind's Dilation",
        'Annie Joins Up',
        'Genesis Ultimatum',
        'Mister Fantastic, Reed Richards',
        'Baxter Building',
        'Bovine Intervention',
        'Cut a Deal',
        'Path to Exile',
        'Deep Analysis',
        'Cultivate',
        'Farseek',
        'Terramorph',
        'Three Visits',
        'Expressive Iteration',
        'Hull Breach',
        'Arcane Signet',
        'Lightning Greaves',
        'Sol Ring',
        'Command Tower',
        'Evolving Wilds',
        'Path of Ancestry',
      ].map((name): [string, number] => [name, 1]),
      ['Plains', 5],
      ['Island', 4],
      ['Mountain', 3],
      ['Forest', 5],
    ],
  },
  {
    id: 'msc-doom-prevails',
    name: 'Doom Prevails',
    colors: ['U', 'B', 'R'],
    face: 'Doctor Doom, King of Latveria',
    commander: 'Doctor Doom, King of Latveria',
    source: 'arena',
    series: 'brawl',
    set: 'msc',
    cards: [
      ...[
        'Molecule Man',
        'Extract Power',
        'Glorious Purpose',
        'Helmut Zemo, Mastermind',
        'Kang Dynasty',
        'Age of Ultron',
        'Damocles Base, Sword of Kang',
        'Endless Ranks of HYDRA',
        'The Frightful Four',
        'Iron Monger, Sadistic Tycoon',
        'Klaw, Master of Sound',
        'Abomination, World Ravager',
        'Batroc the Leaper',
        'Killmonger, Ruthless Usurper',
        'Lady Loki, Agent of Chaos',
        'Living Laser',
        "Loki's Scepter",
        'Puppet Master, String Puller',
        'Stilt-Man, Towering Terror',
        'Titania, Proud Pummeler',
        'Archnemesis',
        'Kang Prime',
        'Loki, the Deceiver',
        'Red Ghost, Intangible Genius',
        'The Squadron Sinister',
        'Typhoid Mary, Fractured',
        'Ultron, Unlimited',
        "Doom's Time Platform",
        'Tri-Sentinel, Act of Vengeance',
        'Black Market Connections',
        'Kindred Dominance',
        'Lethal Scheme',
        'Toxic Deluge',
        'Blasphemous Act',
        'Chaos Warp',
        'Bedevil',
        'Currency Converter',
        "Progenitor's Icon",
        'Skullclamp',
        'Canyon Slough',
        'Choked Estuary',
        'Coastal Peak',
        'Dragonskull Summit',
        'Drowned Catacomb',
        'Exotic Orchard',
        'Fetid Pools',
        'Foreboding Ruins',
        'Frostboil Snarl',
        'Luxury Suite',
        'Scavenger Grounds',
        'Scorched Geyser',
        'Smoldering Marsh',
        'Sulfur Falls',
        'Sunken Hollow',
        'Spark Double',
        'Titan of Littjara',
        'Baron Strucker, HYDRA Overlord',
        'Moonstone, Harsh Mistress',
        'Kang, Temporal Tyrant',
        'Madame Hydra',
        'Villainous Hideout',
        'Containment Construct',
        'Chameleon, Master of Disguise',
        'Propaganda',
        "Night's Whisper",
        'Syphon Mind',
        'Tombstone, Career Criminal',
        'Withering Torment',
        'Superior Foes of Spider-Man',
        'Vandalblast',
        'Prowler, Clawed Thief',
        'Terminate',
        'Arcane Signet',
        'Patchwork Banner',
        'Sol Ring',
        'Swiftfoot Boots',
        'Talisman of Dominance',
        'Talisman of Indulgence',
        'Command Tower',
        'Crumbling Necropolis',
        'Path of Ancestry',
        'Secluded Courtyard',
        'Terramorphic Expanse',
        'Unclaimed Territory',
      ].map((name): [string, number] => [name, 1]),
      ['Island', 4],
      ['Swamp', 6],
      ['Mountain', 5],
    ],
  },
  {
    id: 'brawl-mabels-militia',
    name: "Mabel's Militia",
    colors: ['W', 'R'],
    face: 'Mabel, Heir to Cragflame',
    commander: 'Mabel, Heir to Cragflame',
    source: 'custom',
    series: 'brawl',
    cards: [
      // Creatures.
      ...[
        'Heartfire Hero',
        'Flowerfoot Swordmaster',
        'Manifold Mouse',
        'Emberheart Challenger',
        'Whiskerquill Scribe',
        'Nettle Guard',
        'Mouse Trapper',
        'Thistledown Players',
        'Brambleguard Captain',
        'Whiskervale Forerunner',
        'Seedglaive Mentor',
        'Veteran Guardmouse',
        'Roughshod Duo',
        'Brave-Kin Duo',
        'Swiftblade Vindicator',
        'Leonin Vanguard',
        'Dawnwing Marshal',
        'Cathar Commando',
        'Fencing Ace',
        'Resolute Reinforcements',
        'Moorland Inquisitor',
        'Crusader of Odric',
        'Dauntless Veteran',
        'Mentor of the Meek',
        'Leonin Warleader',
        'Inspiring Commander',
        'Ballyrush Banneret',
        'Brightblade Stoat',
        'Intrepid Rabbit',
        'Shrike Force',
        'Twinblade Paladin',
        'Vanguard Seraph',
        'Serra Angel',
        'Inspiring Overseer',
        'Youthful Valkyrie',
        'Steampath Charger',
        'Hired Claw',
        'Axgard Cavalry',
        // Spells.
        'Shock',
        'Burst Lightning',
        'Lightning Strike',
        'Abrade',
        'Fiery Annihilation',
        'Valorous Stance',
        'Banishing Light',
        'Pacifism',
        'Stasis Snare',
        "Mabel's Mettle",
        'Might of the Meek',
        'Rabbit Response',
        'Valley Rally',
        'Heroic Reinforcements',
        'Release the Dogs',
        // Artifacts.
        'Sol Ring',
        'Arcane Signet',
        'Talisman of Conviction',
        'Fellwar Stone',
        'Thought Vessel',
        'Adventuring Gear',
        'Swiftfoot Boots',
        'Short Bow',
        // Lands.
        'Command Tower',
        'Path of Ancestry',
        'Exotic Orchard',
        'Clifftop Retreat',
        'Radiant Summit',
        'Furycalm Snarl',
        'Glittering Massif',
        'Spectator Seating',
        'Boros Guildgate',
        'Wind-Scarred Crag',
        'Temple of Triumph',
        'Evolving Wilds',
        'Terramorphic Expanse',
        'Fabled Passage',
        'Unclaimed Territory',
        'Secluded Courtyard',
        'Scavenger Grounds',
      ].map((name): [string, number] => [name, 1]),
      ['Plains', 10],
      ['Mountain', 11],
    ],
  },
];

/**
 * Our own Final Fantasy (FIN) decks, built like the starter decks (36 spells,
 * 24 lands) and played against them (docs/final-fantasy-plan.md, phase 11).
 */
export const FINAL_FANTASY_DECKS: Decklist[] = [
  {
    id: 'fin-heroes-arsenal',
    name: "Heroes' Arsenal",
    colors: ['R', 'W'],
    face: 'Zidane, Tantalus Thief',
    source: 'custom',
    series: 'starter',
    set: 'fin',
    cards: [
      ['Giott, King of the Dwarves', 2],
      ['Dwarven Castle Guard', 3],
      ['Adelbert Steiner', 2],
      ['Item Shopkeep', 2],
      ['Coeurl', 1],
      ['Weapons Vendor', 2],
      ['Barret Wallace', 1],
      ['Zidane, Tantalus Thief', 1],
      ["White Mage's Staff", 2],
      ["Red Mage's Rapier", 2],
      ["Paladin's Arms", 2],
      ["Dragoon's Lance", 1],
      ["Samurai's Katana", 2],
      ["Warrior's Sword", 1],
      ["Machinist's Arsenal", 1],
      ['Crystal Fragments', 1],
      ['Thunder Magic', 3],
      ['Fire Magic', 1],
      ['Restoration Magic', 1],
      ['Slash of Light', 2],
      ["You're Not Alone", 1],
      ['Battle Menu', 1],
      ['Fate of the Sun-Cryst', 1],
      ['Plains', 8],
      ['Mountain', 8],
      ['Rabanastre, Royal City', 4],
      ["Adventurer's Inn", 2],
      ['Ishgard, the Holy See', 1],
      ['Lindblum, Industrial Regency', 1],
    ],
  },
  {
    id: 'fin-eidolons-call',
    name: "Eidolons' Call",
    colors: ['G', 'W'],
    face: 'Garnet, Princess of Alexandria',
    source: 'custom',
    series: 'starter',
    set: 'fin',
    cards: [
      ['Garnet, Princess of Alexandria', 2],
      ['Rinoa Heartilly', 2],
      ['Loporrit Scout', 3],
      ['Snow Villiers', 1],
      ['Goobbue Gardener', 2],
      ['Town Greeter', 1],
      ['Balamb T-Rexaur', 1],
      ["Dion, Bahamut's Dominant", 1],
      ['Summon: Choco/Mog', 3],
      ['Summon: Fenrir', 2],
      ['Summon: Primal Garuda', 2],
      ['Summon: Fat Chocobo', 2],
      ['Summon: Titan', 1],
      ['Clash of the Eikons', 2],
      ["Tifa's Limit Break", 2],
      ['Restoration Magic', 1],
      ['Airship Crash', 1],
      ['Fate of the Sun-Cryst', 2],
      ["Prishe's Wanderings", 2],
      ['Battle Menu', 2],
      ['Esper Origins', 1],
      ['Forest', 8],
      ['Plains', 8],
      ['Windurst, Federation Center', 4],
      ["Adventurer's Inn", 2],
      ['Zanarkand, Ancient Metropolis', 1],
      ['Ishgard, the Holy See', 1],
    ],
  },
  // 11b (group A)
  {
    id: 'fin-highwind-workshop',
    name: 'Highwind Workshop',
    colors: ['W', 'U'],
    face: 'Cid, Timeless Artificer',
    source: 'custom',
    series: 'starter',
    set: 'fin',
    cards: [
      ['Magitek Infantry', 2],
      ["Dragoon's Wyvern", 3],
      ['Gaelicat', 2],
      ['Tidus, Blitzball Star', 2],
      ['Ashe, Princess of Dalmasca', 1],
      ['Cid, Timeless Artificer', 4],
      ['Rook Turret', 2],
      ['Magitek Armor', 2],
      ['Delivery Moogle', 1],
      ['Edgar, King of Figaro', 1],
      ['Valkyrie Aerial Unit', 1],
      ["White Mage's Staff", 2],
      ["Thief's Knife", 2],
      ['White Auracite', 2],
      ['Ice Magic', 2],
      ['Battle Menu', 2],
      ['Slash of Light', 1],
      ['Fate of the Sun-Cryst', 1],
      ['Eject', 1],
      ['Aerith Rescue Mission', 1],
      ['Retrieve the Esper', 1],
      ['Plains', 8],
      ['Island', 8],
      ['Sharlayan, Nation of Scholars', 4],
      ["Adventurer's Inn", 2],
      ['Ishgard, the Holy See', 1],
      ['Jidoor, Aristocratic Capital', 1],
    ],
  },
  {
    id: 'fin-time-compression',
    name: 'Time Compression',
    colors: ['U', 'B'],
    face: 'Ultimecia, Time Sorceress',
    source: 'custom',
    series: 'starter',
    set: 'fin',
    cards: [
      ['Il Mheg Pixie', 3],
      ['Dark Confidant', 1],
      ['Undercity Dire Rat', 1],
      ['Locke Cole', 2],
      ["Jill, Shiva's Dominant", 2],
      ['Ahriman', 3],
      ['Qutrub Forayer', 1],
      ['Namazu Trader', 1],
      ['Ultimecia, Time Sorceress', 2],
      ['Summon: Shiva', 2],
      ['Ice Flan', 2],
      ['Malboro', 2],
      ['Summon: Anima', 2],
      ['Resentful Revelation', 1],
      ["Sephiroth's Intervention", 3],
      ["Vayne's Treachery", 3],
      ['Evil Reawakened', 1],
      ['The Final Days', 1],
      ['Ice Magic', 1],
      ['Overkill', 2],
      ['Island', 8],
      ['Swamp', 8],
      ['Treno, Dark City', 4],
      ["Adventurer's Inn", 2],
      ['Midgar, City of Mako', 1],
      ['Jidoor, Aristocratic Capital', 1],
    ],
  },
  {
    id: 'fin-black-mages-waltz',
    name: "Black Mages' Waltz",
    colors: ['B', 'R'],
    face: 'Black Waltz No. 3',
    source: 'custom',
    series: 'starter',
    set: 'fin',
    cards: [
      ['Hecteyes', 2],
      ['Undercity Dire Rat', 2],
      ['Garland, Knight of Cornelia', 2],
      ['Mysidian Elder', 3],
      ['Queen Brahne', 2],
      ["Shambling Cie'th", 2],
      ['Summon: G.F. Ifrit', 2],
      ['Black Waltz No. 3', 2],
      ['Summon: Esper Ramuh', 1],
      ["Black Mage's Rod", 2],
      ['Cornered by Black Mages', 2],
      ['Circle of Power', 1],
      ['Fire Magic', 1],
      ['Thunder Magic', 2],
      ['Suplex', 2],
      ["Vayne's Treachery", 2],
      ['Laughing Mad', 1],
      ['Opera Love Song', 1],
      ['Light of Judgment', 1],
      ["Sephiroth's Intervention", 1],
      ['Choco-Comet', 1],
      ['Resentful Revelation', 1],
      ['Swamp', 8],
      ['Mountain', 8],
      ['Vector, Imperial Capital', 4],
      ["Adventurer's Inn", 2],
      ['Lindblum, Industrial Regency', 1],
      ['Midgar, City of Mako', 1],
    ],
  },
  {
    id: 'fin-chocobo-stampede',
    name: 'Chocobo Stampede',
    colors: ['R', 'G'],
    face: 'Gladiolus Amicitia',
    source: 'custom',
    series: 'starter',
    set: 'fin',
    cards: [
      ["Sazh's Chocobo", 3],
      ['Sabotender', 3],
      ['Rydia, Summoner of Mist', 2],
      ['Summon: Fenrir', 2],
      ['Gigantoad', 2],
      ['Sazh Katzroy', 1],
      ['Summon: Fat Chocobo', 1],
      ['Gladiolus Amicitia', 2],
      ['Hill Gigas', 1],
      ['Balamb T-Rexaur', 1],
      ['Gysahl Greens', 2],
      ['Sidequest: Raise a Chocobo', 2],
      ['Ride the Shoopuf', 2],
      ['Chocobo Racetrack', 1],
      ['Call the Mountain Chocobo', 1],
      ['Choco-Comet', 1],
      ['Chocobo Kick', 2],
      ["Prishe's Wanderings", 2],
      ['Thunder Magic', 2],
      ["Tifa's Limit Break", 1],
      ['Reach the Horizon', 1],
      ['Commune with Beavers', 1],
      ['Forest', 9],
      ['Mountain', 8],
      ['Gongaga, Reactor Town', 4],
      ["Adventurer's Inn", 2],
      ['Zanarkand, Ancient Metropolis', 1],
    ],
  },
  // 11b (group B)
  {
    id: 'fin-turks-contract',
    name: "Turks' Contract",
    colors: ['W', 'B'],
    face: 'Rufus Shinra',
    source: 'custom',
    series: 'starter',
    set: 'fin',
    cards: [
      ['Judge Magister Gabranth', 2],
      ['Rufus Shinra', 2],
      ['Squall, SeeD Mercenary', 1],
      ['Al Bhed Salvagers', 3],
      ['Ahriman', 2],
      ['Undercity Dire Rat', 3],
      ['Namazu Trader', 1],
      ['Dwarven Castle Guard', 3],
      ['Magitek Infantry', 2],
      ["G'raha Tia", 1],
      ['Gaelicat', 2],
      ['Magic Pot', 1],
      ['Summon: Anima', 1],
      ["Vayne's Treachery", 2],
      ["Sephiroth's Intervention", 2],
      ['Overkill', 2],
      ['Cornered by Black Mages', 1],
      ['White Auracite', 1],
      ['Phoenix Down', 1],
      ['Battle Menu', 1],
      ['Fate of the Sun-Cryst', 1],
      ['Evil Reawakened', 1],
      ['Plains', 8],
      ['Swamp', 9],
      ['Insomnia, Crown City', 4],
      ["Adventurer's Inn", 2],
      ['Midgar, City of Mako', 1],
    ],
  },
  {
    id: 'fin-forbidden-magicks',
    name: 'Forbidden Magicks',
    colors: ['U', 'R'],
    face: 'Shantotto, Tactician Magician',
    source: 'custom',
    series: 'starter',
    set: 'fin',
    cards: [
      ['Shantotto, Tactician Magician', 2],
      ['The Emperor of Palamecia', 2],
      ['Tellah, Great Sage', 1],
      ['Sahagin', 2],
      ['Ultros, Obnoxious Octopus', 1],
      ['Blazing Bomb', 1],
      ['Prompto Argentum', 1],
      ['Mysidian Elder', 1],
      ['Ice Flan', 1],
      ['Hill Gigas', 1],
      ['Summon: Esper Ramuh', 1],
      ['Summon: Shiva', 2],
      ["Dragoon's Wyvern", 2],
      ['Rook Turret', 2],
      ['Il Mheg Pixie', 1],
      ['The Prima Vista', 1],
      ['Thunder Magic', 4],
      ['Fire Magic', 1],
      ['Ice Magic', 1],
      ['Light of Judgment', 2],
      ['Eject', 1],
      ['Suplex', 2],
      ['Laughing Mad', 1],
      ['Choco-Comet', 2],
      ['Island', 9],
      ['Mountain', 9],
      ['Baron, Airship Kingdom', 4],
      ['Lindblum, Industrial Regency', 1],
      ['Jidoor, Aristocratic Capital', 1],
    ],
  },
  {
    id: 'fin-into-the-void',
    name: 'Into the Void',
    colors: ['B', 'G'],
    face: 'Exdeath, Void Warlock',
    source: 'custom',
    series: 'starter',
    set: 'fin',
    cards: [
      ['Exdeath, Void Warlock', 2],
      ['Cloud of Darkness', 2],
      ['Shinra Reinforcements', 2],
      ['Undercity Dire Rat', 2],
      ['Hecteyes', 1],
      ['Tonberry', 1],
      ["Shambling Cie'th", 2],
      ['Malboro', 1],
      ['Summon: Anima', 1],
      ['Town Greeter', 2],
      ['Gran Pulse Ochu', 2],
      ['Goobbue Gardener', 2],
      ['Gigantoad', 1],
      ['Balamb T-Rexaur', 1],
      ['Diamond Weapon', 1],
      ['Coliseum Behemoth', 1],
      ['Summon: Titan', 1],
      ['Cactuar', 1],
      ['Evil Reawakened', 1],
      ['Fight On!', 1],
      ['Resentful Revelation', 1],
      ["Sephiroth's Intervention", 2],
      ["Rydia's Return", 1],
      ['Airship Crash', 1],
      ['Commune with Beavers', 2],
      ["Vayne's Treachery", 1],
      ['Swamp', 8],
      ['Forest', 9],
      ['Gohn, Town of Ruin', 4],
      ['Eden, Seat of the Sanctum', 1],
      ['Midgar, City of Mako', 1],
      ['Zanarkand, Ancient Metropolis', 1],
    ],
  },
  {
    id: 'fin-road-trip',
    name: 'Road Trip',
    colors: ['G', 'U'],
    face: 'Ignis Scientia',
    source: 'custom',
    series: 'starter',
    set: 'fin',
    cards: [
      ['Ignis Scientia', 2],
      ['Omega, Heartless Evolution', 1],
      ['Gran Pulse Ochu', 2],
      ['Goobbue Gardener', 3],
      ['Summon: Fenrir', 2],
      ["Dragoon's Wyvern", 2],
      ['Gigantoad', 4],
      ['Summon: Shiva', 3],
      ['Ice Flan', 2],
      ['Balamb T-Rexaur', 3],
      ['Rook Turret', 3],
      ['Ice Magic', 2],
      ['Chocobo Kick', 2],
      ['Airship Crash', 1],
      ['Clash of the Eikons', 3],
      ["Prishe's Wanderings", 1],
      ['Forest', 9],
      ['Island', 8],
      ['Guadosalam, Farplane Gateway', 4],
      ['Crossroads Village', 1],
      ['Jidoor, Aristocratic Capital', 1],
      ['Zanarkand, Ancient Metropolis', 1],
    ],
  },
];

/** Strixhaven (13a): our own decks (docs/strixhaven-13a-decks.md). */
export const STRIXHAVEN_DECKS: Decklist[] = [
  {
    id: 'stx-lorehold-reckoning',
    name: 'Lorehold Reckoning',
    colors: ['R', 'W'],
    face: 'Quintorius, Field Historian',
    source: 'custom',
    series: 'starter',
    set: 'stx',
    cards: [
      ['Eager First-Year', 1],
      ['Serra Angel', 2],
      ['Lorehold Pledgemage', 3],
      ['Inspiring Paladin', 2],
      ['Lorehold Apprentice', 2],
      ['Combat Professor', 2],
      ['Pillardrop Rescuer', 1],
      ['Venerable Warsinger', 2],
      ['Stonebound Mentor', 2],
      ['Fuming Effigy', 2],
      ['Relic Sloth', 2],
      ['Returned Pastcaller', 1],
      ['Quintorius, Field Historian', 1],
      ['Storm-Kiln Artist', 1],
      ['Blade Historian', 1],
      ['Angel of Finality', 1],
      ['Rip Apart', 2],
      ['Igneous Inspiration', 3],
      ['Heated Debate', 2],
      ['Expel', 1],
      ['Pigment Storm', 1],
      ['Lorehold Command', 1],
      ['Lorehold Campus', 4],
      ['Plains', 10],
      ['Mountain', 10],
    ],
    sideboard: [
      ['Spirit Summoning', 1],
      ['Reduce to Memory', 1],
      ['Start from Scratch', 1],
      ['Introduction to Prophecy', 1],
      ['Expanded Anatomy', 1],
    ],
  },
  {
    id: 'stx-quandrix-equation',
    name: 'Quandrix Equation',
    colors: ['G', 'U'],
    face: 'Biomathematician',
    source: 'custom',
    series: 'starter',
    set: 'stx',
    cards: [
      ['Biomathematician', 3],
      ['Quandrix Pledgemage', 3],
      ['Needlethorn Drake', 2],
      ['Frost Trickster', 2],
      ['Quandrix Cultivator', 1],
      ['Professor of Zoomancy', 2],
      ['Gnarlback Rhino', 4],
      ['Thrashing Brontodon', 4],
      ['Scrapshooter', 2],
      ['Knightfisher', 1],
      ['Lilysplash Mentor', 1],
      ['Dreamdew Entrancer', 1],
      ['Serpentine Curve', 1],
      ['Leyline Invocation', 1],
      ['Field Trip', 1],
      ['Mage Duel', 2],
      ['Devouring Tendrils', 2],
      ['Bite Down', 3],
      ['Quandrix Campus', 4],
      ['Forest', 10],
      ['Island', 10],
    ],
    sideboard: [
      ['Fractal Summoning', 1],
      ['Introduction to Prophecy', 1],
      ['Expanded Anatomy', 1],
      ['Environmental Sciences', 1],
    ],
  },
  // 13b: Silverquill (docs/strixhaven-13b-silverquill.md).
  {
    id: 'stx-silverquill-inkwell',
    name: 'Silverquill Inkwell',
    colors: ['W', 'B'],
    face: 'Shadrix Silverquill',
    source: 'custom',
    series: 'starter',
    set: 'stx',
    cards: [
      ['Eyetwitch', 1],
      ['Professor of Symbology', 1],
      ['Silverquill Apprentice', 2],
      ['Leech Fanatic', 2],
      ['Killian, Ink Duelist', 1],
      ['Silverquill Pledgemage', 2],
      ['Sedgemoor Witch', 1],
      ['Callous Bloodmage', 1],
      ['Shadewing Laureate', 1],
      ['Mage Hunter', 1],
      ['Specter of the Fens', 2],
      ['Spiteful Squad', 2],
      ['Owlin Shieldmage', 2],
      ['Combat Professor', 2],
      ['Pillardrop Rescuer', 1],
      ['Tenured Inkcaster', 1],
      ['Shadrix Silverquill', 1],
      ['Vanishing Verse', 1],
      ['Baleful Mastery', 1],
      ["Mage Hunters' Onslaught", 2],
      ['Closing Statement', 1],
      ['Defend the Campus', 1],
      ['Umbral Juke', 2],
      ['Silverquill Command', 1],
      ['Exhilarating Elocution', 1],
      ['Dramatic Finale', 1],
      ['Blot Out the Sky', 1],
      ['Silverquill Campus', 4],
      ['Plains', 10],
      ['Swamp', 10],
    ],
    sideboard: [
      ['Inkling Summoning', 1],
      ['Rise of Extus', 1],
      ['Reduce to Memory', 1],
      ['Hunt for Specimens', 1],
    ],
  },
  {
    id: 'stx-witherbloom-bloodroot',
    name: 'Witherbloom Bloodroot',
    colors: ['B', 'G'],
    face: 'Dina, Soul Steeper',
    source: 'custom',
    series: 'starter',
    set: 'stx',
    cards: [
      ['Eyetwitch', 2],
      ['Leech Fanatic', 2],
      ['Witherbloom Apprentice', 2],
      ['Blood Researcher', 2],
      ['Dina, Soul Steeper', 1],
      ['Callous Bloodmage', 1],
      ['Honor Troll', 1],
      ['Moldering Karok', 2],
      ['Professor of Zoomancy', 2],
      ['Springmane Cervin', 1],
      ['Specter of the Fens', 1],
      ['Mage Hunter', 1],
      ['Gnarled Professor', 2],
      ['Witherbloom Pledgemage', 2],
      ['Tenured Inkcaster', 1],
      ['Sedgemoor Witch', 2],
      ['Bayou Groff', 2],
      ['Hunt for Specimens', 2],
      ['Mortality Spear', 2],
      ['Baleful Mastery', 1],
      ["Mage Hunters' Onslaught", 1],
      ['Bite Down', 1],
      ['Devouring Tendrils', 2],
      ['Witherbloom Campus', 4],
      ['Forest', 10],
      ['Swamp', 10],
    ],
    sideboard: [
      ['Pest Summoning', 1],
      ['Basic Conjuration', 1],
      ['Containment Breach', 1],
      ['Environmental Sciences', 1],
    ],
  },
  {
    id: 'stx-prismari-artistry',
    name: 'Prismari Artistry',
    colors: ['U', 'R'],
    face: 'Galazeth Prismari',
    source: 'custom',
    series: 'starter',
    set: 'stx',
    cards: [
      ['Frost Trickster', 3],
      ['Prismari Apprentice', 1],
      ['Prismari Pledgemage', 3],
      ['Fuming Effigy', 3],
      ['Oggyar Battle-Seer', 2],
      ['Waterfall Aerialist', 2],
      ['Maelstrom Muse', 1],
      ['Elemental Expressionist', 1],
      ['Galazeth Prismari', 1],
      ['Retriever Phoenix', 1],
      ['Wormhole Serpent', 1],
      ['Giant Cindermaw', 2],
      ['Quaketusk Boar', 1],
      ['Shivan Dragon', 1],
      ['Skyskipper Duo', 1],
      ['Heated Debate', 3],
      ['Igneous Inspiration', 2],
      ['Pigment Storm', 3],
      ['Scorching Dragonfire', 1],
      ['Prismari Command', 1],
      ['Expressive Iteration', 1],
      ['Elemental Masterpiece', 1],
      ['Prismari Campus', 4],
      ['Island', 10],
      ['Mountain', 10],
    ],
    sideboard: [
      ['Elemental Summoning', 1],
      ['Start from Scratch', 1],
      ['Introduction to Prophecy', 1],
      ['Expanded Anatomy', 1],
    ],
  },
  {
    id: 'stx-azorius-skies',
    name: 'Azorius Skies',
    colors: ['W', 'U'],
    face: 'Combat Professor',
    source: 'custom',
    series: 'starter',
    set: 'stx',
    cards: [
      ['Professor of Symbology', 2],
      ['Burrog Befuddler', 2],
      ['Strict Proctor', 2],
      ['Thunderous Orator', 2],
      ['Frost Trickster', 3],
      ['Dream Strix', 2],
      ['Elite Spellbinder', 2],
      ["Mavinda, Students' Advocate", 1],
      ['Combat Professor', 2],
      ['Waterfall Aerialist', 2],
      ['Pillardrop Rescuer', 1],
      ['Ancestor Dragon', 1],
      ['Wormhole Serpent', 2],
      ['Serra Angel', 2],
      ['Lyra Dawnbringer', 1],
      ['Expel', 2],
      ['Reduce to Memory', 2],
      ['Banishing Light', 2],
      ['Detention Vortex', 2],
      ['Bury in Books', 1],
      ['Azorius Guildgate', 3],
      ['Tranquil Cove', 2],
      ['Plains', 11],
      ['Island', 8],
    ],
    sideboard: [
      ['Introduction to Annihilation', 1],
      ['Introduction to Prophecy', 1],
      ['Teachings of the Archaics', 1],
      ['Expanded Anatomy', 1],
      ['Environmental Sciences', 1],
    ],
  },
  {
    id: 'stx-rakdos-ruin',
    name: 'Rakdos Ruin',
    colors: ['B', 'R'],
    face: 'Efreet Flamepainter',
    source: 'custom',
    series: 'starter',
    set: 'stx',
    cards: [
      ['Eyetwitch', 2],
      ['Unwilling Ingredient', 1],
      ['Leech Fanatic', 2],
      ['Sedgemoor Witch', 2],
      ['Callous Bloodmage', 1],
      ['Tome Shredder', 2],
      ['Twinscroll Shaman', 2],
      ['Giant Cindermaw', 2],
      ['Vampire Nighthawk', 1],
      ['Novice Dissector', 1],
      ['Mage Hunter', 2],
      ['Fuming Effigy', 3],
      ['Specter of the Fens', 1],
      ['Retriever Phoenix', 1],
      ['Shivan Dragon', 1],
      ['Efreet Flamepainter', 1],
      ['Heated Debate', 3],
      ['Igneous Inspiration', 2],
      ['Pigment Storm', 1],
      ["Mage Hunters' Onslaught", 1],
      ['Baleful Mastery', 1],
      ["Hero's Downfall", 1],
      ['Scorching Dragonfire', 1],
      ['Start from Scratch', 1],
      ['Rakdos Guildgate', 4],
      ['Bloodfell Caves', 4],
      ['Temple of Malice', 1],
      ['Swamp', 8],
      ['Mountain', 7],
    ],
    sideboard: [
      ['Introduction to Annihilation', 1],
      ['Pest Summoning', 1],
      ['Elemental Summoning', 1],
      ['Spirit Summoning', 1],
    ],
  },
  {
    id: 'stx-selesnya-overgrowth',
    name: 'Selesnya Overgrowth',
    colors: ['G', 'W'],
    face: 'Gnarled Professor',
    source: 'custom',
    series: 'starter',
    set: 'stx',
    cards: [
      ['Strict Proctor', 2],
      ['Pilgrim of the Ages', 1],
      ['Shaile, Dean of Radiance', 2],
      ['Professor of Symbology', 2],
      ['Springmane Cervin', 3],
      ['Honor Troll', 2],
      ['Thunderous Orator', 1],
      ['Stonerise Spirit', 1],
      ['Professor of Zoomancy', 3],
      ['Combat Professor', 2],
      ['Dueling Coach', 2],
      ['Master Symmetrist', 2],
      ['Gnarled Professor', 2],
      ['Pillardrop Rescuer', 1],
      ['Bookwurm', 1],
      ['Guiding Voice', 1],
      ['Elite Spellbinder', 2],
      ['Devouring Tendrils', 2],
      ['Expel', 1],
      ['Reduce to Memory', 1],
      ["Mavinda, Students' Advocate", 1],
      ['Lisette, Dean of the Root', 1],
      ['Selesnya Guildgate', 4],
      ['Temple of Plenty', 1],
      ['Sunpetal Grove', 1],
      ['Forest', 9],
      ['Plains', 9],
    ],
    sideboard: [
      ['Expanded Anatomy', 1],
      ['Environmental Sciences', 1],
      ['Containment Breach', 1],
      ['Introduction to Annihilation', 1],
    ],
  },
  {
    id: 'stx-gruul-stampede',
    name: 'Gruul Stampede',
    colors: ['R', 'G'],
    face: 'Retriever Phoenix',
    source: 'custom',
    series: 'starter',
    set: 'stx',
    cards: [
      ['Burst Lightning', 1],
      ['Twinscroll Shaman', 3],
      ['Illustrious Historian', 2],
      ['Reckless Amplimancer', 2],
      ['Bayou Groff', 2],
      ['Gnarled Professor', 3],
      ['Gnarlback Rhino', 1],
      ['Shivan Dragon', 1],
      ['Master Symmetrist', 1],
      ['Professor of Zoomancy', 1],
      ['Retriever Phoenix', 2],
      ['Beast-Kin Ranger', 1],
      ['Giant Cindermaw', 1],
      ['Heated Debate', 2],
      ['Igneous Inspiration', 2],
      ['Devouring Tendrils', 2],
      ['Pigment Storm', 1],
      ['Mage Duel', 1],
      ['Big Play', 1],
      ['Enthusiastic Study', 1],
      ['Sudden Breakthrough', 1],
      ['Mascot Interception', 1],
      ['Fiery Annihilation', 1],
      ['Leyline Invocation', 1],
      ['Introduction to Annihilation', 1],
      ['Forest', 12],
      ['Mountain', 12],
    ],
    sideboard: [
      ['Expanded Anatomy', 1],
      ['Start from Scratch', 1],
      ['Environmental Sciences', 1],
      ['Basic Conjuration', 1],
    ],
  },
  {
    id: 'stx-dimir-tide',
    name: 'Dimir Tide',
    colors: ['U', 'B'],
    face: 'Mage Hunter',
    source: 'custom',
    series: 'starter',
    set: 'stx',
    cards: [
      ['Eyetwitch', 2],
      ['Unwilling Ingredient', 1],
      ['Leech Fanatic', 2],
      ['Sedgemoor Witch', 2],
      ['Callous Bloodmage', 2],
      ['Frost Trickster', 3],
      ['Dream Strix', 2],
      ['Mage Hunter', 3],
      ['Specter of the Fens', 2],
      ['Waterfall Aerialist', 1],
      ['Witherbloom Pledgemage', 2],
      ['Vampire Nighthawk', 2],
      ['Baleful Mastery', 2],
      ["Mage Hunters' Onslaught", 1],
      ['Umbral Juke', 1],
      ['Lash of Malice', 1],
      ['Bury in Books', 1],
      ["Hero's Downfall", 2],
      ['Fell', 1],
      ['Bake into a Pie', 1],
      ['Hunt for Specimens', 1],
      ["Poet's Quill", 1],
      ['Dimir Guildgate', 3],
      ['Dismal Backwater', 3],
      ['Temple of Deceit', 1],
      ['Swamp', 11],
      ['Island', 6],
    ],
    sideboard: [
      ['Introduction to Annihilation', 1],
      ['Pest Summoning', 1],
      ['Inkling Summoning', 1],
      ['Teachings of the Archaics', 1],
    ],
  },
];

/** Secrets of Strixhaven (14a): our own decks (docs/strixhaven-14a-decks.md). */
export const SECRETS_OF_STRIXHAVEN_DECKS: Decklist[] = [
  {
    id: 'sos-silverquill-debate-club',
    name: 'Silverquill Debate Club',
    colors: ['W', 'B'],
    face: 'Stirring Hopesinger',
    source: 'custom',
    series: 'starter',
    set: 'sos',
    cards: [
      ['Elite Interceptor', 2],
      ['Honorbound Page', 1],
      ['Eager Glyphmage', 1],
      ['Owlin Historian', 1],
      ['Rehearsed Debater', 2],
      ['Inkshape Demonstrator', 1],
      ['Quill-Blade Laureate', 1],
      ['Imperious Inkmage', 1],
      ['Inkling Mascot', 2],
      ['Scolding Administrator', 2],
      ['Snooping Page', 1],
      ['Melancholic Poet', 2],
      ['Sneering Shadewriter', 1],
      ["Conciliator's Duelist", 1],
      ['Stirring Hopesinger', 1],
      ['Silverquill Charm', 2],
      ['Harsh Annotation', 1],
      ['Last Gasp', 2],
      ['Foolish Fate', 1],
      ['Stand Up for Yourself', 1],
      ['Wander Off', 1],
      ['Interjection', 2],
      ['Rapier Wit', 1],
      ["Killian's Confidence", 1],
      ['Render Speechless', 1],
      ['Dissection Practice', 1],
      ['Graduation Day', 1],
      ["Ajani's Response", 1],
      ['Forum of Amity', 1],
      ['Shattered Sanctum', 1],
      ['Plains', 11],
      ['Swamp', 11],
    ],
  },
  {
    id: 'sos-witherbloom-pest-control',
    name: 'Witherbloom Pest Control',
    colors: ['B', 'G'],
    face: "Moseo, Vein's New Dean",
    source: 'custom',
    series: 'starter',
    set: 'sos',
    cards: [
      ['Bogwater Lumaret', 2],
      ['Essenceknit Scholar', 1],
      ['Old-Growth Educator', 2],
      ['Pest Mascot', 2],
      ["Teacher's Pest", 1],
      ['Lluwen, Exchange Student', 1],
      ['Pestbrood Sloth', 1],
      ["Shopkeeper's Bane", 1],
      ['Mindful Biomancer', 2],
      ['Thornfist Striker', 1],
      ['Ulna Alley Shopkeep', 1],
      ['Sneering Shadewriter', 2],
      ['Leech Collector', 1],
      ["Poisoner's Apprentice", 1],
      ['Blech, Loafing Pest', 1],
      ["Moseo, Vein's New Dean", 1],
      ['Grapple with Death', 2],
      ['Witherbloom Charm', 1],
      ['Last Gasp', 1],
      ['Foolish Fate', 1],
      ['Wander Off', 1],
      ['Efflorescence', 2],
      ['Send in the Pest', 1],
      ['Cost of Brilliance', 1],
      ['Root Manipulation', 1],
      ['Follow the Lumarets', 1],
      ["Oracle's Restoration", 1],
      ["Lumaret's Favor", 1],
      ['Dissection Practice', 1],
      ["Titan's Grave", 1],
      ['Deathcap Glade', 1],
      ['Swamp', 11],
      ['Forest', 11],
    ],
  },
  {
    id: 'sos-rakdos-sparks-and-ashes',
    name: 'Rakdos Sparks and Ashes',
    colors: ['B', 'R'],
    face: 'Emeritus of Woe',
    source: 'custom',
    series: 'starter',
    set: 'sos',
    cards: [
      ['Burrog Banemaker', 2],
      ['Scheming Silvertongue', 1],
      ['Postmortem Professor', 1],
      ['Goblin Glasswright', 2],
      ['Strife Scholar', 1],
      ['Adventurous Eater', 2],
      ['Charging Strifeknight', 1],
      ['Maelstrom Artisan', 1],
      ['Blazing Firesinger', 1],
      ['Eternal Student', 1],
      ['Sneering Shadewriter', 2],
      ['Cheerful Osteomancer', 1],
      ['Garrison Excavator', 1],
      ['Mica, Reader of Ruins', 1],
      ['Pigment Wrangler', 1],
      ['Emeritus of Woe', 1],
      ['Scathing Shadelock', 1],
      ['Last Gasp', 2],
      ['Foolish Fate', 1],
      ['Wander Off', 1],
      ['Unsubtle Mockery', 2],
      ['Tome Blast', 2],
      ['Heated Argument', 1],
      ['Impractical Joke', 1],
      ['Duel Tactics', 1],
      ['Cost of Brilliance', 1],
      ['Artistic Process', 1],
      ['Living History', 1],
      ['Ral Zarek, Guest Lecturer', 1],
      ['Swamp', 12],
      ['Mountain', 12],
    ],
  },
];

export const DECKS: Decklist[] = [
  ...ARENA_DECKS,
  ...COLOR_CHALLENGE_DECKS,
  ...BLOOMBURROW_DECKS,
  ...MARVEL_DECKS,
  ...MARVEL_BRAWL_DECKS,
  ...FINAL_FANTASY_DECKS,
  ...STRIXHAVEN_DECKS,
  ...SECRETS_OF_STRIXHAVEN_DECKS,
];
