import type { Color } from '@mtg/engine';

export interface Decklist {
  /** Stable key, e.g. for saved preferences. */
  id: string;
  name: string;
  colors: Color[];
  /** Card shown on the deck box. */
  face: string;
  /** Where the list comes from ('arena': MTG Arena; 'custom': ours, like the Jump In packets). */
  source: 'arena' | 'custom';
  /**
   * 'starter': two-colour Starter Deck Duel decks; 'colorChallenge': the
   * mono-colour decks Sparky plays; 'jumpIn': two Jump In packets together;
   * 'season': a deck built in Season mode, taken on an expedition.
   */
  series: 'starter' | 'colorChallenge' | 'jumpIn' | 'season' | 'brawl';
  /** A deck from another set than Foundations (shown in its own section). */
  set?: 'blb' | 'msc';
  cards: [name: string, count: number][];
  /** Brawl: the commander (not in `cards`, which hold the other 99). */
  commander?: string;
}

/**
 * MTG Arena's Foundations Starter Decks (Starter Deck Duel, March 2025), from
 * https://mtg.wiki/page/Foundations_Starter_Decks. Face cards are our pick.
 */
export const ARENA_DECKS: Decklist[] = [
  {
    id: 'arcane-aerialists',
    name: 'Arcane Aerialists',
    colors: ['W', 'U'],
    face: 'Giada, Font of Hope',
    source: 'arena',
    series: 'starter',
    cards: [
      ['Aegis Turtle', 2],
      ['Cloudblazer', 2],
      ['Curator of Destinies', 1],
      ['Dazzling Angel', 2],
      ['Empyrean Eagle', 3],
      ['Fog Bank', 2],
      ['Giada, Font of Hope', 1],
      ["Healer's Hawk", 2],
      ['High Fae Trickster', 1],
      ['Inspiring Overseer', 2],
      ['Lyra Dawnbringer', 1],
      ['Serra Angel', 2],
      ['Spectral Sailor', 2],
      ['Vanguard Seraph', 2],
      ['Youthful Valkyrie', 2],
      ['Faebloom Trick', 2],
      ['Chart a Course', 2],
      ['Goldvein Pick', 2],
      ['Stasis Snare', 3],
      ['Plains', 8],
      ['Island', 7],
      ['Azorius Guildgate', 4],
      ['Temple of Enlightenment', 1],
      ['Tranquil Cove', 4],
    ],
  },
  {
    id: 'cat-attack',
    name: 'Cat Attack',
    colors: ['G', 'W'],
    face: 'Arahbo, the First Fang',
    source: 'arena',
    series: 'starter',
    cards: [
      ['Arahbo, the First Fang', 1],
      ['Dawnwing Marshal', 2],
      ['Felidar Savior', 2],
      ['Good-Fortune Unicorn', 3],
      ['Helpful Hunter', 4],
      ['Leonin Vanguard', 3],
      ['Regal Caracal', 1],
      ['Savannah Lions', 3],
      ['Wary Thespian', 4],
      ['Claws Out', 4],
      ['Giant Growth', 2],
      ['Felling Blow', 2],
      ['Angelic Destiny', 1],
      ['Anthem of Champions', 1],
      ['Banishing Light', 2],
      ['Unflinching Courage', 1],
      ['Blossoming Sands', 4],
      ['Forest', 6],
      ['Plains', 9],
      ['Selesnya Guildgate', 4],
      ['Temple of Plenty', 1],
    ],
  },
  {
    id: 'graveyard-gifts',
    name: 'Graveyard Gifts',
    colors: ['U', 'B'],
    face: 'Kiora, the Rising Tide',
    source: 'arena',
    series: 'starter',
    cards: [
      ['Abyssal Harvester', 1],
      ['Arbiter of Woe', 2],
      ['Arcanis the Omnipotent', 1],
      ['Billowing Shriekmass', 2],
      ['Brineborn Cutthroat', 2],
      ['Crow of Dark Tidings', 2],
      ['Dreadwing Scavenger', 4],
      ['Gleaming Barrier', 3],
      ['Kiora, the Rising Tide', 1],
      ['Bake into a Pie', 2],
      ['Essence Scatter', 2],
      ['Opt', 4],
      ['Stab', 4],
      ['Inspiration from Beyond', 2],
      ['Rise of the Dark Realms', 1],
      ['Zombify', 3],
      ['Dimir Guildgate', 4],
      ['Dismal Backwater', 4],
      ['Island', 7],
      ['Swamp', 8],
      ['Temple of Deceit', 1],
    ],
  },
  {
    id: 'learn-from-the-land',
    name: 'Learn From the Land',
    colors: ['G', 'U'],
    face: 'Tatyova, Benthic Druid',
    source: 'arena',
    series: 'starter',
    cards: [
      ['Apothecary Stomper', 2],
      ['Bigfin Bouncer', 2],
      ['Druid of the Cowl', 4],
      ['Elfsworn Giant', 2],
      ['Exclusion Mage', 3],
      ['Llanowar Elves', 3],
      ['Loot, Exuberant Explorer', 1],
      ['Magnigoth Sentry', 2],
      ['Mild-Mannered Librarian', 2],
      ['Mischievous Mystic', 2],
      ['Mossborn Hydra', 1],
      ['Rampaging Baloths', 1],
      ['Spectral Sailor', 2],
      ['Tatyova, Benthic Druid', 2],
      ['Quick Study', 2],
      ['Circuitous Route', 2],
      ['Felling Blow', 2],
      ['Primeval Bounty', 1],
      ['Forest', 10],
      ['Island', 5],
      ['Simic Guildgate', 4],
      ['Temple of Mystery', 1],
      ['Thornwood Falls', 4],
    ],
  },
  {
    id: 'might-of-the-legion',
    name: 'Might of the Legion',
    colors: ['R', 'W'],
    face: 'Aurelia, the Warleader',
    source: 'arena',
    series: 'starter',
    cards: [
      ['Aurelia, the Warleader', 1],
      ['Axgard Cavalry', 2],
      ['Crusader of Odric', 3],
      ['Dauntless Veteran', 2],
      ['Dawnwing Marshal', 2],
      ['Fanatical Firebrand', 3],
      ['Frenzied Goblin', 2],
      ['Krenko, Mob Boss', 1],
      ['Resolute Reinforcements', 2],
      ['Searslicer Goblin', 1],
      ['Serra Angel', 2],
      ['Burst Lightning', 2],
      ['Goblin Surprise', 2],
      ['Valorous Stance', 2],
      ['Dragon Fodder', 2],
      ['Heroic Reinforcements', 2],
      ['Release the Dogs', 2],
      ['Celestial Armor', 1],
      ['Goldvein Pick', 2],
      ['Boros Guildgate', 2],
      ['Mountain', 8],
      ['Plains', 9],
      ['Temple of Triumph', 1],
      ['Wind-Scarred Crag', 4],
    ],
  },
  {
    id: 'morbid-machinations',
    name: 'Morbid Machinations',
    colors: ['B', 'G'],
    face: 'Spinner of Souls',
    source: 'arena',
    series: 'starter',
    cards: [
      ['Cackling Prowler', 2],
      ['Eager Trufflesnout', 2],
      ['Infernal Vessel', 2],
      ['Infestation Sage', 2],
      ['Llanowar Elves', 3],
      ['Midnight Reaper', 1],
      ['Needletooth Pack', 2],
      ['Quilled Greatwurm', 1],
      ['Reassembling Skeleton', 2],
      ['Scavenging Ooze', 1],
      ['Spinner of Souls', 1],
      ['Tragic Banshee', 2],
      ['Vampire Gourmand', 2],
      ['Wardens of the Cycle', 3],
      ['Wary Thespian', 2],
      ['Undying Malice', 2],
      ['Eaten Alive', 2],
      ['Felling Blow', 2],
      ['Vampiric Rites', 2],
      ['Forest', 8],
      ['Golgari Guildgate', 4],
      ['Jungle Hollow', 4],
      ['Swamp', 7],
      ['Temple of Malady', 1],
    ],
  },
  {
    id: 'path-of-power',
    name: 'Path of Power',
    colors: ['R', 'G'],
    face: 'Halana and Alena, Partners',
    source: 'arena',
    series: 'starter',
    cards: [
      ['Ashroot Animist', 1],
      ['Axgard Cavalry', 2],
      ['Beast-Kin Ranger', 2],
      ['Courageous Goblin', 2],
      ['Eager Trufflesnout', 2],
      ['Giant Cindermaw', 2],
      ['Halana and Alena, Partners', 1],
      ['Llanowar Elves', 3],
      ['Mild-Mannered Librarian', 2],
      ['Nessian Hornbeetle', 3],
      ['Ruby, Daring Tracker', 2],
      ['Skyraker Giant', 2],
      ['Spinner of Souls', 1],
      ['Vizier of the Menagerie', 1],
      ['Bulk Up', 1],
      ['Scorching Dragonfire', 2],
      ['Snakeskin Veil', 2],
      ['Bushwhack', 2],
      ['Felling Blow', 2],
      ["Garruk's Uprising", 1],
      ['Forest', 8],
      ['Gruul Guildgate', 4],
      ['Mountain', 7],
      ['Rugged Highlands', 4],
      ['Temple of Abandon', 1],
    ],
  },
  {
    id: 'reckless-raid',
    name: 'Reckless Raid',
    colors: ['B', 'R'],
    face: 'Alesha, Who Laughs at Fate',
    source: 'arena',
    series: 'starter',
    cards: [
      ['Alesha, Who Laughs at Fate', 1],
      ['Battlesong Berserker', 2],
      ['Diregraf Ghoul', 4],
      ['Goblin Boarders', 3],
      ['High-Society Hunter', 1],
      ['Infestation Sage', 3],
      ['Massacre Wurm', 1],
      ['Perforating Artist', 3],
      ['Searslicer Goblin', 1],
      ['Slumbering Cerberus', 3],
      ['Strongbox Raider', 2],
      ['Vampire Gourmand', 3],
      ['Abrade', 3],
      ['Burst Lightning', 2],
      ['Fake Your Own Death', 2],
      ["Hero's Downfall", 2],
      ['Bloodfell Caves', 4],
      ['Mountain', 7],
      ['Rakdos Guildgate', 4],
      ['Swamp', 8],
      ['Temple of Malice', 1],
    ],
  },
  {
    id: 'vampiric-hunger',
    name: 'Vampiric Hunger',
    colors: ['W', 'B'],
    face: 'Elenda, Saint of Dusk',
    source: 'arena',
    series: 'starter',
    cards: [
      ["Ajani's Pridemate", 3],
      ['Cat Collector', 2],
      ['Dazzling Angel', 2],
      ['Elenda, Saint of Dusk', 1],
      ['Fiendish Panda', 2],
      ["Healer's Hawk", 2],
      ['Hinterland Sanctifier', 2],
      ['Inspiring Overseer', 2],
      ['Sanguine Syphoner', 2],
      ['Sun-Blessed Healer', 2],
      ['Twinblade Paladin', 2],
      ['Vampire Nighthawk', 2],
      ['Vengeful Bloodwitch', 2],
      ['Moment of Craving', 2],
      ['Moment of Triumph', 2],
      ['Mortify', 2],
      ['Tribute to Hunger', 2],
      ['Angelic Destiny', 1],
      ['Phyrexian Arena', 1],
      ['Orzhov Guildgate', 4],
      ['Plains', 8],
      ['Scoured Barrens', 4],
      ['Swamp', 7],
      ['Temple of Silence', 1],
    ],
  },
  {
    id: 'wondrous-wizardry',
    name: 'Wondrous Wizardry',
    colors: ['U', 'R'],
    face: 'Niv-Mizzet, Visionary',
    source: 'arena',
    series: 'starter',
    cards: [
      ['Archmage of Runes', 1],
      ['Balmor, Battlemage Captain', 1],
      ['Drake Hatcher', 1],
      ['Enigma Drake', 2],
      ['Ghitu Lavarunner', 4],
      ['Heartfire Immolator', 2],
      ['Mischievous Mystic', 2],
      ['Niv-Mizzet, Visionary', 1],
      ['Ovika, Enigma Goliath', 1],
      ['Tolarian Terror', 3],
      ['Arcane Epiphany', 2],
      ['Burst Lightning', 4],
      ['Dive Down', 3],
      ['Fiery Annihilation', 2],
      ['Opt', 4],
      ['Chart a Course', 3],
      ['Island', 8],
      ['Mountain', 7],
      ['Izzet Guildgate', 4],
      ['Swiftwater Cliffs', 4],
      ['Temple of Epiphany', 1],
    ],
  },
];

/**
 * MTG Arena's Color Challenge decks (August 2020): the five mono-colour decks
 * new players unlock and Sparky plays. From https://mtg.wiki/page/Color_Challenge_decks
 * (upgraded lists; the sideboards are left out). Face cards are our pick.
 */
export const COLOR_CHALLENGE_DECKS: Decklist[] = [
  {
    id: 'keep-the-peace',
    name: 'Keep the Peace',
    colors: ['W'],
    face: 'Angel of Vitality',
    source: 'arena',
    series: 'colorChallenge',
    cards: [
      ['Charmed Stray', 4],
      ['Fencing Ace', 2],
      ['Hallowed Priest', 4],
      ['Impassioned Orator', 3],
      ['Moorland Inquisitor', 2],
      ['Angel of Vitality', 2],
      ['Leonin Warleader', 2],
      ['Serra Angel', 1],
      ['Spiritual Guardian', 1],
      ['Angelic Guardian', 1],
      ['Inspiring Commander', 2],
      ['Goring Ceratops', 1],
      ['Pacifism', 3],
      ['Angelic Reward', 1],
      ['Tactical Advantage', 4],
      ['Confront the Assault', 1],
      ['Bond of Discipline', 1],
      ['Plains', 25],
    ],
  },
  {
    id: 'aerial-domination',
    name: 'Aerial Domination',
    colors: ['U'],
    face: 'Windreader Sphinx',
    source: 'arena',
    series: 'colorChallenge',
    cards: [
      ['Wall of Runes', 2],
      ['Sworn Guardian', 2],
      ['Waterkin Shaman', 3],
      ['Cloudkin Seer', 3],
      ['Warden of Evos Isle', 3],
      ['Octoprophet', 2],
      ['Soulblade Djinn', 2],
      ['Windstorm Drake', 2],
      ['Frilled Sea Serpent', 1],
      ['Riddlemaster Sphinx', 2],
      ['Windreader Sphinx', 1],
      ['Waterknot', 3],
      ['Unsummon', 3],
      ['Glint', 2],
      ['Winged Words', 2],
      ['Sleep', 1],
      ['Overflowing Insight', 1],
      ['Island', 25],
    ],
  },
  {
    id: 'cold-blooded-killers',
    name: 'Cold-Blooded Killers',
    colors: ['B'],
    face: 'Demon of Loathing',
    source: 'arena',
    series: 'colorChallenge',
    cards: [
      ['Sanitarium Skeleton', 2],
      ['Typhoid Rats', 2],
      ['Malakir Cullblade', 3],
      ['Vampire Opportunist', 2],
      ['Mardu Outrider', 2],
      ['Savage Gorger', 3],
      ['Skeleton Archer', 2],
      ['Sengir Vampire', 2],
      ['Soulhunter Rakshasa', 1],
      ['Nightmare', 1],
      ['Demon of Loathing', 2],
      ['Eternal Thirst', 1],
      ['Compound Fracture', 4],
      ['Cruel Cut', 1],
      ['Unlikely Aid', 3],
      ['Murder', 3],
      ['Bad Deal', 1],
      ['Swamp', 25],
    ],
  },
  {
    id: 'goblins-everywhere',
    name: 'Goblins Everywhere!',
    colors: ['R'],
    face: 'Goblin Gang Leader',
    source: 'arena',
    series: 'colorChallenge',
    cards: [
      ['Tin Street Cadet', 3],
      ['Goblin Tunneler', 2],
      ['Nest Robber', 4],
      ['Molten Ravager', 2],
      ['Goblin Gang Leader', 2],
      ['Goblin Trashmaster', 1],
      ['Ogre Battledriver', 2],
      ['Immortal Phoenix', 1],
      ['Volcanic Dragon', 1],
      ['Siege Dragon', 2],
      ['Raid Bombardment', 2],
      ['Shock', 3],
      ['Storm Strike', 2],
      ['Burn Bright', 2],
      ['Inescapable Blaze', 2],
      ['Goblin Gathering', 4],
      ['Mountain', 25],
    ],
  },
  {
    id: 'large-and-in-charge',
    name: 'Large and in Charge',
    colors: ['G'],
    face: 'Gigantosaurus',
    source: 'arena',
    series: 'colorChallenge',
    cards: [
      ['Jungle Delver', 3],
      ['Ilysian Caryatid', 4],
      ['Woodland Mystic', 2],
      ['Wildwood Patrol', 2],
      ['Baloth Packhunter', 4],
      ['Prized Unicorn', 1],
      ['Rumbling Baloth', 2],
      ['World Shaper', 1],
      ['Gigantosaurus', 2],
      ['Sentinel Spider', 2],
      ['Affectionate Indrik', 2],
      ['Rampaging Brontodon', 2],
      ['Colossal Majesty', 2],
      ['Epic Proportions', 1],
      ['Stony Strength', 2],
      ['Rabid Bite', 3],
      ['Forest', 25],
    ],
  },
];

/**
 * Our Bloomburrow decks, built like the Foundations starter decks (two
 * colours, 36 spells and 24 lands) so they play against them.
 */
export const BLOOMBURROW_DECKS: Decklist[] = [
  {
    id: 'blb-forage-and-feast',
    name: 'Forage and Feast',
    colors: ['B', 'G'],
    face: 'Camellia, the Seedmiser',
    source: 'custom',
    series: 'starter',
    set: 'blb',
    cards: [
      ['Agate-Blade Assassin', 2],
      ['Bakersbane Duo', 3],
      ['Vinereap Mentor', 3],
      ['Bonebind Orator', 2],
      ['Bushy Bodyguard', 2],
      ['Daggerfang Duo', 3],
      ['Curious Forager', 2],
      ['Honored Dreyleader', 2],
      ['Camellia, the Seedmiser', 1],
      ['Treetop Sentries', 2],
      ['Thornplate Intimidator', 2],
      ["Wick's Patrol", 1],
      ['Feed the Cycle', 2],
      ['Savor', 3],
      ['Nocturnal Hunger', 2],
      ['Longstalk Brawl', 2],
      ['Consumed by Greed', 1],
      ["Hazel's Nocturne", 1],
      ['Forest', 8],
      ['Swamp', 7],
      ['Golgari Guildgate', 4],
      ['Jungle Hollow', 4],
      ['Temple of Malady', 1],
    ],
  },
  {
    id: 'blb-warren-rally',
    name: 'Warren Rally',
    colors: ['G', 'W'],
    face: 'Warren Warleader',
    source: 'custom',
    series: 'starter',
    set: 'blb',
    cards: [
      ['Seasoned Warrenguard', 3],
      ['Brave-Kin Duo', 2],
      ['Nettle Guard', 2],
      ['Warren Elder', 2],
      ['Burrowguard Mentor', 2],
      ['Finneas, Ace Archer', 1],
      ['Intrepid Rabbit', 3],
      ['Harvestrite Host', 2],
      ['Druid of the Spade', 2],
      ['Hazardroot Herbalist', 2],
      ['Warren Warleader', 1],
      ['Treeguard Duo', 2],
      ['Carrot Cake', 2],
      ['Hop to It', 2],
      ['Crumb and Get It', 2],
      ["Mabel's Mettle", 2],
      ['Rabbit Response', 1],
      ['Repel Calamity', 2],
      ['Banishing Light', 1],
      ['Plains', 8],
      ['Forest', 7],
      ['Selesnya Guildgate', 4],
      ['Blossoming Sands', 4],
      ['Temple of Plenty', 1],
    ],
  },
  {
    id: 'blb-night-flight',
    name: 'Night Flight',
    colors: ['W', 'B'],
    face: 'Zoraline, Cosmos Caller',
    source: 'custom',
    series: 'starter',
    set: 'blb',
    cards: [
      ['Lifecreed Duo', 3],
      ['Starscape Cleric', 3],
      ['Brightblade Stoat', 2],
      ['Essence Channeler', 1],
      ['Moonrise Cleric', 3],
      ['Moonstone Harbinger', 2],
      ['Starlit Soothsayer', 3],
      ['Zoraline, Cosmos Caller', 1],
      ['Wax-Wane Witness', 2],
      ['Star Charter', 2],
      ['Starseer Mentor', 2],
      ['Glidedive Duo', 2],
      ['Sonar Strike', 2],
      ['Fell', 2],
      ['Diresight', 2],
      ['Sinister Monolith', 2],
      ['Lunar Convocation', 1],
      ['Starfall Invocation', 1],
      ['Plains', 8],
      ['Swamp', 7],
      ['Orzhov Guildgate', 4],
      ['Scoured Barrens', 4],
      ['Temple of Silence', 1],
    ],
  },
  {
    id: 'blb-valiant-squeak',
    name: 'Valiant Squeak',
    colors: ['R', 'W'],
    face: 'Mabel, Heir to Cragflame',
    source: 'custom',
    series: 'starter',
    set: 'blb',
    cards: [
      ['Heartfire Hero', 4],
      ['Flowerfoot Swordmaster', 2],
      ['Emberheart Challenger', 1],
      ['Whiskerquill Scribe', 2],
      ['Manifold Mouse', 1],
      ['Nettle Guard', 2],
      ['Seedglaive Mentor', 3],
      ['Mabel, Heir to Cragflame', 1],
      ['Mouse Trapper', 2],
      ['Thistledown Players', 2],
      ['Brambleguard Captain', 2],
      ['Whiskervale Forerunner', 1],
      ['Veteran Guardmouse', 2],
      ['Might of the Meek', 3],
      ['Rabid Gnaw', 2],
      ["Mabel's Mettle", 2],
      ['War Squeak', 2],
      ['Blooming Blast', 2],
      ['Mountain', 8],
      ['Plains', 7],
      ['Boros Guildgate', 4],
      ['Wind-Scarred Crag', 4],
      ['Temple of Triumph', 1],
    ],
  },
  {
    id: 'blb-scorching-scales',
    name: 'Scorching Scales',
    colors: ['B', 'R'],
    face: 'Gev, Scaled Scorch',
    source: 'custom',
    series: 'starter',
    set: 'blb',
    cards: [
      ['Iridescent Vinelasher', 2],
      ['Ravine Raider', 2],
      ['Hired Claw', 2],
      ['Agate-Blade Assassin', 3],
      ['Steampath Charger', 3],
      ['Fireglass Mentor', 2],
      ['Gev, Scaled Scorch', 1],
      ['Cindering Cutthroat', 2],
      ['Thought-Stalker Warlock', 2],
      ['Hearthborn Battler', 1],
      ['Valley Flamecaller', 1],
      ['Frilled Sparkshooter', 2],
      ['Reptilian Recruiter', 1],
      ['Scales of Shale', 2],
      ['Fell', 1],
      ['Agate Assault', 2],
      ['Blooming Blast', 2],
      ['Playful Shove', 2],
      ['Savor', 1],
      ['Nocturnal Hunger', 2],
      ['Mountain', 8],
      ['Swamp', 7],
      ['Rakdos Guildgate', 4],
      ['Bloodfell Caves', 4],
      ['Temple of Malice', 1],
    ],
  },
  {
    id: 'blb-rat-pack',
    name: 'Rat Pack',
    colors: ['U', 'B'],
    face: 'Vren, the Relentless',
    source: 'custom',
    series: 'starter',
    set: 'blb',
    cards: [
      ['Thought Shucker', 2],
      ['Shoreline Looter', 2],
      ['Persistent Marshstalker', 3],
      ['Azure Beastbinder', 1],
      ['Nightwhorl Hermit', 2],
      ['Mindwhisker', 2],
      ['Daggerfang Duo', 3],
      ['Tidecaller Mentor', 2],
      ['Mind Drill Assailant', 2],
      ['Wick, the Whorled Mind', 1],
      ['Vren, the Relentless', 1],
      ['Thornplate Intimidator', 2],
      ["Wick's Patrol", 1],
      ['Psychic Whorl', 2],
      ['Fell', 2],
      ['Into the Flood Maw', 2],
      ['Spellgyre', 1],
      ["Long River's Pull", 1],
      ['Dire Downdraft', 2],
      ['Run Away Together', 1],
      ['Diresight', 1],
      ['Island', 8],
      ['Swamp', 7],
      ['Dimir Guildgate', 4],
      ['Dismal Backwater', 4],
      ['Temple of Deceit', 1],
    ],
  },
  {
    id: 'blb-otter-antics',
    name: 'Otter Antics',
    colors: ['U', 'R'],
    face: 'Valley Floodcaller',
    source: 'custom',
    series: 'starter',
    set: 'blb',
    cards: [
      ['Stormcatch Mentor', 2],
      ['Coruscation Mage', 3],
      ['Thundertrap Trainer', 2],
      ['Kindlespark Duo', 3],
      ['Tempest Angler', 3],
      ['Harnesser of Storms', 1],
      ['Quaketusk Boar', 2],
      ['Valley Floodcaller', 1],
      ['Kitsa, Otterball Elite', 1],
      ['Stormsplitter', 1],
      ["Alania's Pathmaker", 2],
      ['Eddymurk Crab', 1],
      ['Playful Shove', 2],
      ['Take Out the Trash', 3],
      ['Blooming Blast', 2],
      ['Agate Assault', 2],
      ['Conduct Electricity', 1],
      ['Otterball Antics', 2],
      ['Dazzling Denial', 1],
      ["Sazacap's Brew", 1],
      ['Island', 8],
      ['Mountain', 7],
      ['Izzet Guildgate', 4],
      ['Swiftwater Cliffs', 4],
      ['Temple of Epiphany', 1],
    ],
  },
  {
    id: 'blb-lilypad-leap',
    name: 'Lilypad Leap',
    colors: ['G', 'U'],
    face: 'Clement, the Worrywort',
    source: 'custom',
    series: 'starter',
    set: 'blb',
    cards: [
      ['Sunshower Druid', 2],
      ['Mistbreath Elder', 1],
      ['Valley Mightcaller', 1],
      ['Bellowing Crier', 2],
      ['Pond Prophet', 3],
      ['Three Tree Scribe', 2],
      ['Dour Port-Mage', 1],
      ['Stickytongue Sentinel', 2],
      ['Long River Lurker', 2],
      ['Waterspout Warden', 2],
      ['Clement, the Worrywort', 1],
      ['Clifftop Lookout', 2],
      ['Splash Lasher', 2],
      ['Lilysplash Mentor', 2],
      ['Dreamdew Entrancer', 1],
      ['Splash Portal', 2],
      ['Polliwallop', 2],
      ['Hivespine Wolverine', 1],
      ['Galewind Moose', 1],
      ['Run Away Together', 2],
      ['Pawpatch Formation', 2],
      ['Forest', 8],
      ['Island', 7],
      ['Simic Guildgate', 4],
      ['Thornwood Falls', 4],
      ['Temple of Mystery', 1],
    ],
  },
  {
    id: 'blb-sky-flock',
    name: 'Sky Flock',
    colors: ['W', 'U'],
    face: 'Kastral, the Windcrested',
    source: 'custom',
    series: 'starter',
    set: 'blb',
    cards: [
      ['Plumecreed Escort', 2],
      ['Finch Formation', 2],
      ['Shrike Force', 3],
      ['Jackdaw Savior', 1],
      ['Plumecreed Mentor', 3],
      ['Seedpod Squire', 3],
      ['Salvation Swan', 1],
      ['Pileated Provisioner', 2],
      ['Skyskipper Duo', 2],
      ['Knightfisher', 2],
      ['Driftgloom Coyote', 1],
      ['Kastral, the Windcrested', 1],
      ['Dazzling Denial', 2],
      ['Feather of Flight', 2],
      ['Repel Calamity', 2],
      ['Banishing Light', 2],
      ['Parting Gust', 2],
      ['Into the Flood Maw', 2],
      ["Mabel's Mettle", 1],
      ['Plains', 8],
      ['Island', 7],
      ['Azorius Guildgate', 4],
      ['Tranquil Cove', 4],
      ['Temple of Enlightenment', 1],
    ],
  },
  {
    id: 'blb-raccoon-rumble',
    name: 'Raccoon Rumble',
    colors: ['R', 'G'],
    face: 'Muerra, Trash Tactician',
    source: 'custom',
    series: 'starter',
    set: 'blb',
    cards: [
      ['Three Tree Rootweaver', 2],
      ['Bakersbane Duo', 2],
      ['Bark-Knuckle Boxer', 2],
      ['Wandertale Mentor', 3],
      ['Brazen Collector', 2],
      ['Raccoon Rallier', 1],
      ['Brambleguard Veteran', 2],
      ['Roughshod Duo', 2],
      ['Byway Barterer', 1],
      ['Muerra, Trash Tactician', 1],
      ['Rust-Shield Rampager', 2],
      ['Teapot Slinger', 2],
      ['Junkblade Bruiser', 2],
      ['Quaketusk Boar', 1],
      ['Take Out the Trash', 2],
      ['Heaped Harvest', 1],
      ['Overprotect', 2],
      ["Hunter's Talent", 2],
      ["Hoarder's Overflow", 1],
      ['Blooming Blast', 2],
      ['Rabid Gnaw', 1],
      ['Mountain', 8],
      ['Forest', 7],
      ['Gruul Guildgate', 4],
      ['Rugged Highlands', 4],
      ['Temple of Abandon', 1],
    ],
  },
];

/**
 * Brawl decks (Arena's 1v1 Commander): the four Marvel Super Heroes Commander
 * precons as printed (from https://mtg.wtf/deck/msc/<slug>), plus a test deck
 * of our own built from Foundations and Bloomburrow cards and the precons'
 * shared staples. 100 cards, singleton, within the commander's colours.
 */
export const MARVEL_BRAWL_DECKS: Decklist[] = [
  {
    id: 'msc-avengers-assemble',
    name: 'Avengers Assemble',
    colors: ['W', 'U', 'R'],
    face: 'Captain America, Team Leader',
    commander: 'Captain America, Team Leader',
    source: 'arena',
    series: 'brawl',
    set: 'msc',
    cards: [
      ...[
        'Avenge',
        'Falcon and Redwing',
        'Hercules, Olympian Hero',
        'Heroic Return',
        'Heroic Sacrifice',
        'Methods of the Mighty',
        'Winter Soldier, Reborn Avenger',
        'Iron Man, Armored Avenger',
        "Jarvis, Earth's Mightiest Butler",
        'Professor Hulk',
        'The Wasp, Winsome Avenger',
        'West Coast Expansion',
        'Firebird, Blazing Ranger',
        'Photon, Mighty Marvel',
        'She-Hulk, Wallbreaker',
        'War Machine, Avenging Arsenal',
        'Ant-Man, Elusive Avenger',
        'Black Widow, Agile Avenger',
        'Captain Marvel, Apex Avenger',
        'Director Nick Fury',
        'Hawkeye, Avenging Archer',
        'Love on the Battlefield',
        'Quicksilver, Speedster',
        'Scarlet Witch, Chaotic Avenger',
        'Shang-Chi and the Ten Rings',
        'Avengers Quinjet',
        'Hulkbuster Armor',
        'Jocasta, Automaton Avenger',
        'Vision, Synthezoid Avenger',
        'Austere Command',
        'Bastion Protector',
        'Dismantling Wave',
        'Folk Hero',
        'Gift of Immortality',
        'Kindred Discovery',
        'Door of Destinies',
        'Metallic Mimic',
        'Tome of Legends',
        'Clifftop Retreat',
        'Coastal Peak',
        'Exotic Orchard',
        'Frostboil Snarl',
        'Furycalm Snarl',
        'Glacial Fortress',
        'Glittering Massif',
        'Irrigated Farmland',
        'Plaza of Heroes',
        'Port Town',
        'Prairie Stream',
        'Radiant Summit',
        'Scavenger Grounds',
        'Scorched Geyser',
        'Spectator Seating',
        'Sulfur Falls',
        'Raise the Palisade',
        "Thor, Asgard's Avenger",
        'Captain Mar-Vell, Space-Born',
        'Patriot, Shield Wielder',
        'Speed, Young Avenger',
        'Captain America, Living Legend',
        'Avengers Tower',
        'Destroy Evil',
        'Make Your Move',
        'Swords to Plowshares',
        'Arcane Denial',
        'Reconnaissance Mission',
        'Rip Apart',
        'Arcane Signet',
        "Hero's Blade",
        'Relic of Legends',
        'Sol Ring',
        'Talisman of Conviction',
        'Talisman of Creativity',
        'Talisman of Progress',
        'Thought Vessel',
        'Command Tower',
        'Mystic Monastery',
        'Path of Ancestry',
        'Secluded Courtyard',
        'Unclaimed Territory',
        'Fellwar Stone',
        "Herald's Horn",
        'Rescue, Pepper Potts',
      ].map((name): [string, number] => [name, 1]),
      ['Plains', 6],
      ['Island', 5],
      ['Mountain', 5],
    ],
  },
  {
    id: 'brawl-mabels-militia',
    name: "Mabel's Militia",
    colors: ['W', 'R'],
    face: 'Mabel, Heir to Cragflame',
    commander: 'Mabel, Heir to Cragflame',
    source: 'custom',
    series: 'brawl',
    cards: [
      // Creatures.
      ...[
        'Heartfire Hero',
        'Flowerfoot Swordmaster',
        'Manifold Mouse',
        'Emberheart Challenger',
        'Whiskerquill Scribe',
        'Nettle Guard',
        'Mouse Trapper',
        'Thistledown Players',
        'Brambleguard Captain',
        'Whiskervale Forerunner',
        'Seedglaive Mentor',
        'Veteran Guardmouse',
        'Roughshod Duo',
        'Brave-Kin Duo',
        'Swiftblade Vindicator',
        'Leonin Vanguard',
        'Dawnwing Marshal',
        'Cathar Commando',
        'Fencing Ace',
        'Resolute Reinforcements',
        'Moorland Inquisitor',
        'Crusader of Odric',
        'Dauntless Veteran',
        'Mentor of the Meek',
        'Leonin Warleader',
        'Inspiring Commander',
        'Ballyrush Banneret',
        'Brightblade Stoat',
        'Intrepid Rabbit',
        'Shrike Force',
        'Twinblade Paladin',
        'Vanguard Seraph',
        'Serra Angel',
        'Inspiring Overseer',
        'Youthful Valkyrie',
        'Steampath Charger',
        'Hired Claw',
        'Axgard Cavalry',
        // Spells.
        'Shock',
        'Burst Lightning',
        'Lightning Strike',
        'Abrade',
        'Fiery Annihilation',
        'Valorous Stance',
        'Banishing Light',
        'Pacifism',
        'Stasis Snare',
        "Mabel's Mettle",
        'Might of the Meek',
        'Rabbit Response',
        'Valley Rally',
        'Heroic Reinforcements',
        'Release the Dogs',
        // Artifacts.
        'Sol Ring',
        'Arcane Signet',
        'Talisman of Conviction',
        'Fellwar Stone',
        'Thought Vessel',
        'Adventuring Gear',
        'Swiftfoot Boots',
        'Short Bow',
        // Lands.
        'Command Tower',
        'Path of Ancestry',
        'Exotic Orchard',
        'Clifftop Retreat',
        'Radiant Summit',
        'Furycalm Snarl',
        'Glittering Massif',
        'Spectator Seating',
        'Boros Guildgate',
        'Wind-Scarred Crag',
        'Temple of Triumph',
        'Evolving Wilds',
        'Terramorphic Expanse',
        'Fabled Passage',
        'Unclaimed Territory',
        'Secluded Courtyard',
        'Scavenger Grounds',
      ].map((name): [string, number] => [name, 1]),
      ['Plains', 10],
      ['Mountain', 11],
    ],
  },
];

export const DECKS: Decklist[] = [
  ...ARENA_DECKS,
  ...COLOR_CHALLENGE_DECKS,
  ...BLOOMBURROW_DECKS,
  ...MARVEL_BRAWL_DECKS,
];
