import type { Color } from '@mtg/engine';

/**
 * Themed half-decks for Jump In!, Arena's mode where you pick two 20-card
 * packets and shuffle them together. Arena's packets use cards we haven't
 * implemented, so these are our own, ten per set (Foundations, Bloomburrow,
 * Marvel Super Heroes): twelve spells around a theme, one rare, plus eight
 * basic lands of the packet's colour.
 */
export interface Packet {
  id: string;
  name: string;
  color: Color;
  /** Card shown on the packet. */
  face: string;
  blurb: string;
  /** Bloomburrow or Marvel Super Heroes (default Foundations). Packets of different sets pair freely. */
  set?: 'blb' | 'msh';
  /** The twelve spells; the basic lands are added by `packetCards`. */
  spells: [name: string, count: number][];
}

export const PACKET_LANDS = 8;

export const PACKETS: Packet[] = [
  {
    id: 'angels',
    name: 'Angels',
    color: 'W',
    face: 'Giada, Font of Hope',
    blurb: 'Flyers that gain life and grow each other',
    spells: [
      ["Healer's Hawk", 1],
      ['Youthful Valkyrie', 2],
      ['Dazzling Angel', 2],
      ['Inspiring Overseer', 1],
      ['Angel of Vitality', 1],
      ['Giada, Font of Hope', 1],
      ['Vanguard Seraph', 1],
      ['Serra Angel', 1],
      ['Pacifism', 1],
      ['Moment of Triumph', 1],
    ],
  },
  {
    id: 'cats',
    name: 'Cats',
    color: 'W',
    face: 'Arahbo, the First Fang',
    blurb: 'Cheap cats that pounce early and pile on',
    spells: [
      ['Savannah Lions', 1],
      ['Leonin Vanguard', 1],
      ['Helpful Hunter', 2],
      ['Dawnwing Marshal', 1],
      ["Ajani's Pridemate", 1],
      ['Arahbo, the First Fang', 1],
      ['Cat Collector', 1],
      ['Felidar Savior', 1],
      ['Valorous Stance', 1],
      ['Banishing Light', 1],
      ['Claws Out', 1],
    ],
  },
  {
    id: 'wizards',
    name: 'Wizards',
    color: 'U',
    face: 'Drake Hatcher',
    blurb: 'Cast spells, draw cards, counter theirs',
    spells: [
      ['Opt', 2],
      ['Mischievous Mystic', 2],
      ['Drake Hatcher', 1],
      ['Fog Bank', 1],
      ['Exclusion Mage', 1],
      ['Quick Study', 1],
      ['Essence Scatter', 1],
      ['Faebloom Trick', 1],
      ['Arcane Epiphany', 1],
      ['Tolarian Terror', 1],
    ],
  },
  {
    id: 'pirates',
    name: 'Pirates',
    color: 'U',
    face: 'Kiora, the Rising Tide',
    blurb: 'Slippery raiders that dig for the right card',
    spells: [
      ['Spectral Sailor', 2],
      ['Dive Down', 1],
      ['Brineborn Cutthroat', 2],
      ['Chart a Course', 1],
      ['Kiora, the Rising Tide', 1],
      ['Aegis Turtle', 1],
      ['Inspiration from Beyond', 1],
      ['Bigfin Bouncer', 2],
      ['Tolarian Terror', 1],
    ],
  },
  {
    id: 'vampires',
    name: 'Vampires',
    color: 'B',
    face: 'High-Society Hunter',
    blurb: 'Drain life and pick off their creatures',
    spells: [
      ['Vampiric Rites', 1],
      ['Stab', 1],
      ['Vampire Gourmand', 2],
      ['Sanguine Syphoner', 1],
      ['Vengeful Bloodwitch', 1],
      ['Moment of Craving', 1],
      ['Vampire Nighthawk', 1],
      ['Infernal Vessel', 1],
      ['Tribute to Hunger', 1],
      ["Hero's Downfall", 1],
      ['High-Society Hunter', 1],
    ],
  },
  {
    id: 'undead',
    name: 'Undead',
    color: 'B',
    face: 'Midnight Reaper',
    blurb: 'Creatures that keep coming back',
    spells: [
      ['Diregraf Ghoul', 2],
      ['Eaten Alive', 1],
      ['Undying Malice', 1],
      ['Reassembling Skeleton', 1],
      ['Crow of Dark Tidings', 2],
      ['Midnight Reaper', 1],
      ['Bake into a Pie', 1],
      ['Billowing Shriekmass', 1],
      ['Zombify', 1],
      ['Tragic Banshee', 1],
    ],
  },
  {
    id: 'goblins',
    name: 'Goblins',
    color: 'R',
    face: 'Krenko, Mob Boss',
    blurb: 'A swarm of goblins, and a boss who makes more',
    spells: [
      ['Fanatical Firebrand', 1],
      ['Frenzied Goblin', 1],
      ['Burst Lightning', 1],
      ['Kindled Fury', 1],
      ['Swab Goblin', 1],
      ['Courageous Goblin', 1],
      ['Dragon Fodder', 1],
      ['Raging Redcap', 1],
      ['Goblin Boarders', 1],
      ['Guttersnipe', 1],
      ['Goblin Surprise', 1],
      ['Krenko, Mob Boss', 1],
    ],
  },
  {
    id: 'dragonfire',
    name: 'Dragonfire',
    color: 'R',
    face: 'Shivan Dragon',
    blurb: 'Burn a path for a dragon',
    spells: [
      ['Ghitu Lavarunner', 1],
      ['Sure Strike', 1],
      ['Viashino Pyromancer', 1],
      ['Heartfire Immolator', 1],
      ['Firebrand Archer', 1],
      ['Scorching Dragonfire', 1],
      ['Fiery Annihilation', 1],
      ['Ball Lightning', 1],
      ['Spitfire Lagac', 1],
      ['Skyraker Giant', 1],
      ['Dragon Trainer', 1],
      ['Shivan Dragon', 1],
    ],
  },
  {
    id: 'elves',
    name: 'Elves',
    color: 'G',
    face: 'Imperious Perfect',
    blurb: 'Mana elves into a big elf army',
    spells: [
      ['Llanowar Elves', 2],
      ['Giant Growth', 1],
      ['Snakeskin Veil', 1],
      ['Thornweald Archer', 1],
      ["Dwynen's Elite", 1],
      ['Scavenging Ooze', 1],
      ['Bite Down', 1],
      ['Imperious Perfect', 1],
      ['Beast-Kin Ranger', 1],
      ['Wildheart Invoker', 1],
      ['Tajuru Pathwarden', 1],
    ],
  },
  {
    id: 'stompers',
    name: 'Stompers',
    color: 'G',
    face: 'Rampaging Baloths',
    blurb: 'Huge beasts and the mana to cast them',
    spells: [
      ['Llanowar Elves', 1],
      ['Bushwhack', 1],
      ['Giant Growth', 1],
      ['Bear Cub', 1],
      ['Eager Trufflesnout', 1],
      ['Felling Blow', 1],
      ['Gnarlback Rhino', 1],
      ['Magnigoth Sentry', 1],
      ['Needletooth Pack', 1],
      ['Elfsworn Giant', 1],
      ['Rampaging Baloths', 1],
      ['Pelakka Wurm', 1],
    ],
  },
  // Bloomburrow: our own packets, one theme per animal family.
  {
    id: 'blb-rabbits',
    name: 'Rabbits',
    color: 'W',
    face: 'Valley Questcaller',
    blurb: 'A warren that keeps growing and goes wide',
    set: 'blb',
    spells: [
      ['Brave-Kin Duo', 1],
      ['Seasoned Warrenguard', 1],
      ['Warren Elder', 1],
      ['Intrepid Rabbit', 2],
      ['Harvestrite Host', 1],
      ['Valley Questcaller', 1],
      ['Hop to It', 1],
      ['Rabbit Response', 1],
      ['Crumb and Get It', 1],
      ['Carrot Cake', 1],
      ['Repel Calamity', 1],
    ],
  },
  {
    id: 'blb-mice',
    name: 'Mice',
    color: 'W',
    face: 'Whiskervale Forerunner',
    blurb: 'Valiant soldiers that grow when you target them',
    set: 'blb',
    spells: [
      ['Flowerfoot Swordmaster', 1],
      ['Nettle Guard', 2],
      ['Brightblade Stoat', 1],
      ['Mouse Trapper', 1],
      ['Thistledown Players', 1],
      ['Whiskervale Forerunner', 1],
      ["Mabel's Mettle", 1],
      ['Brave-Kin Duo', 1],
      ['Sonar Strike', 1],
      ['Feather of Flight', 1],
      ['Dewdrop Cure', 1],
    ],
  },
  {
    id: 'blb-otters',
    name: 'Otters',
    color: 'U',
    face: 'Thundertrap Trainer',
    blurb: 'Spellslingers that fill the air with tricks',
    set: 'blb',
    spells: [
      ['Thundertrap Trainer', 1],
      ['Bellowing Crier', 1],
      ['Mindwhisker', 1],
      ['Plumecreed Escort', 1],
      ['Daring Waverider', 1],
      ['Otterball Antics', 2],
      ['Pearl of Wisdom', 1],
      ['Into the Flood Maw', 1],
      ['Dazzling Denial', 1],
      ['Shore Up', 1],
      ['Dire Downdraft', 1],
    ],
  },
  {
    id: 'blb-frogs',
    name: 'Frogs',
    color: 'U',
    face: 'Dour Port-Mage',
    blurb: 'Frogs and birds that bounce and come back',
    set: 'blb',
    spells: [
      ['Dour Port-Mage', 1],
      ['Long River Lurker', 1],
      ['Waterspout Warden', 2],
      ['Splash Lasher', 1],
      ['Finch Formation', 1],
      ['Knightfisher', 1],
      ['Skyskipper Duo', 1],
      ["Long River's Pull", 1],
      ['Shore Up', 1],
      ['Splash Portal', 1],
      ['Eddymurk Crab', 1],
    ],
  },
  {
    id: 'blb-bats',
    name: 'Bats',
    color: 'B',
    face: 'Darkstar Augur',
    blurb: 'Fliers that drain life every time it changes',
    set: 'blb',
    spells: [
      ['Starscape Cleric', 2],
      ['Moonstone Harbinger', 1],
      ['Starlit Soothsayer', 2],
      ['Glidedive Duo', 1],
      ['Darkstar Augur', 1],
      ['Savor', 1],
      ['Nocturnal Hunger', 1],
      ['Diresight', 1],
      ['Fell', 1],
      ['Consumed by Greed', 1],
    ],
  },
  {
    id: 'blb-rats',
    name: 'Rats',
    color: 'B',
    face: 'Valley Rotcaller',
    blurb: 'Rats and squirrels that grind out the long game',
    set: 'blb',
    spells: [
      ['Bonebind Orator', 1],
      ['Daggerfang Duo', 1],
      ['Thornplate Intimidator', 1],
      ['Persistent Marshstalker', 2],
      ['Bonecache Overseer', 1],
      ['Valley Rotcaller', 1],
      ["Wick's Patrol", 1],
      ['Scales of Shale', 1],
      ['Psychic Whorl', 1],
      ['Early Winter', 1],
      ['Feed the Cycle', 1],
    ],
  },
  {
    id: 'blb-hero-mice',
    name: 'Hero Mice',
    color: 'R',
    face: 'Manifold Mouse',
    blurb: 'Fast heroes pumped by every trick you cast',
    set: 'blb',
    spells: [
      ['Heartfire Hero', 2],
      ['Whiskerquill Scribe', 2],
      ['Brambleguard Captain', 1],
      ['Roughshod Duo', 1],
      ['Manifold Mouse', 1],
      ['Might of the Meek', 2],
      ['War Squeak', 1],
      ['Rabid Gnaw', 1],
      ['Valley Rally', 1],
    ],
  },
  {
    id: 'blb-lizards',
    name: 'Lizards',
    color: 'R',
    face: 'Valley Flamecaller',
    blurb: 'Lizards that burn the opponent as they fight',
    set: 'blb',
    spells: [
      ['Steampath Charger', 2],
      ['Flamecache Gecko', 1],
      ['Frilled Sparkshooter', 1],
      ['Reptilian Recruiter', 1],
      ['Kindlespark Duo', 1],
      ['Valley Flamecaller', 1],
      ['Agate Assault', 1],
      ['Take Out the Trash', 1],
      ['Blooming Blast', 1],
      ["Sazacap's Brew", 1],
      ['Conduct Electricity', 1],
    ],
  },
  {
    id: 'blb-squirrels',
    name: 'Squirrels',
    color: 'G',
    face: 'Thornvault Forager',
    blurb: 'Squirrels that stash Food and forage for value',
    set: 'blb',
    spells: [
      ['Bakersbane Duo', 1],
      ['Bushy Bodyguard', 1],
      ['Curious Forager', 1],
      ['Honored Dreyleader', 1],
      ['Treetop Sentries', 2],
      ['Thornvault Forager', 1],
      ['Heaped Harvest', 1],
      ['Cache Grab', 1],
      ['Longstalk Brawl', 1],
      ['Stocking the Pantry', 1],
      ['Overprotect', 1],
    ],
  },
  {
    id: 'blb-woodland',
    name: 'Woodland',
    color: 'G',
    face: 'Mistbreath Elder',
    blurb: 'Frogs, raccoons and big beasts of the wood',
    set: 'blb',
    spells: [
      ['Sunshower Druid', 1],
      ['Stickytongue Sentinel', 1],
      ['Clifftop Lookout', 1],
      ['Treeguard Duo', 1],
      ['Bark-Knuckle Boxer', 1],
      ['Brambleguard Veteran', 1],
      ['Rust-Shield Rampager', 1],
      ['Galewind Moose', 1],
      ['Mistbreath Elder', 1],
      ['High Stride', 1],
      ['Polliwallop', 1],
      ['Hazardroot Herbalist', 1],
    ],
  },
  // Marvel Super Heroes: our own packets around the set's teams and themes.
  {
    id: 'msh-shield',
    name: 'S.H.I.E.L.D.',
    color: 'W',
    face: 'Agent Phil Coulson',
    blurb: 'Agents and spies who back each other up',
    set: 'msh',
    spells: [
      ['Agent Maria Hill', 1],
      ['Agent of Atlas', 2],
      ['Agents of S.H.I.E.L.D.', 2],
      ['Agent 13, Sharon Carter', 1],
      ['Agent Phil Coulson', 1],
      ['Raft Security Officer', 1],
      ['Helicarrier Strike', 1],
      ['Take Up the Shield', 1],
      ["Murdock's Crusade", 1],
      ['Super Villain Lockup', 1],
    ],
  },
  {
    id: 'msh-avengers',
    name: 'Avengers',
    color: 'W',
    face: 'Captain America, Wings of Freedom',
    blurb: 'Heroes who assemble and fight as a team',
    set: 'msh',
    spells: [
      ['Brave Brawler', 2],
      ['Hero in Training', 2],
      ['Patriot, Shield Wielder', 1],
      ['Luke Cage, Power Man', 1],
      ['Okoye, Dora Milaje Leader', 1],
      ['Captain Mar-Vell, Space-Born', 1],
      ['Captain America, Wings of Freedom', 1],
      ['Panther Pounce', 1],
      ['Take Up the Shield', 1],
      ['Borough Backup', 1],
    ],
  },
  {
    id: 'msh-scientists',
    name: 'Scientists',
    color: 'U',
    face: 'Leader, Super-Genius',
    blurb: 'Geniuses with gadgets and clever answers',
    set: 'msh',
    spells: [
      ['Bold Biochemist', 2],
      ['A.I.M. Scientists', 1],
      ['Mister Fantastic, Reed Richards', 1],
      ['Leader, Super-Genius', 1],
      ['Futurist Forge', 1],
      ['Pym Particles', 1],
      ['Depower', 1],
      ['We Say Thee Nay!', 1],
      ["Trickster's Stratagem", 1],
      ['Super Suit', 1],
      ['Giant-Sized Flying Ant', 1],
    ],
  },
  {
    id: 'msh-sky-and-sea',
    name: 'Sky and Sea',
    color: 'U',
    face: 'The Wondrous Wasp',
    blurb: 'Fliers and Atlanteans that strike from above',
    set: 'msh',
    spells: [
      ['Aerial Doombot', 1],
      ['Atlantean Cavalry', 2],
      ['S.H.I.E.L.D. Deployment Drone', 1],
      ['Giant-Sized Flying Ant', 1],
      ['Falcon, Winged Wonder', 1],
      ['The Wondrous Wasp', 1],
      ['Depower', 1],
      ['We Say Thee Nay!', 1],
      ['Pym Particles', 1],
      ["Trickster's Stratagem", 1],
      ['Super Suit', 1],
    ],
  },
  {
    id: 'msh-hydra',
    name: 'HYDRA',
    color: 'B',
    face: 'Baron Helmut Zemo',
    blurb: 'Cut off one head, two more take its place',
    set: 'msh',
    spells: [
      ['Agents of HYDRA', 2],
      ['HYDRA Troopers', 2],
      ['Red Room Recruit', 1],
      ['Baron Strucker, HYDRA Overlord', 1],
      ['Crossbones, Malicious Mercenary', 1],
      ['Baron Helmut Zemo', 1],
      ['HYDRA Infiltration', 1],
      ['Dark Deed', 1],
      ["Widow's Bite", 1],
      ['Hour of Defeat', 1],
    ],
  },
  {
    id: 'msh-villains',
    name: 'Villains',
    color: 'B',
    face: 'Elektra, Daughter of the Hand',
    blurb: 'Ninjas, enforcers and villains who won’t stay dead',
    set: 'msh',
    spells: [
      ['Ninja of the Hand', 2],
      ["Kingpin's Enforcers", 1],
      ['Unliving Legionnaire', 1],
      ['Roxxon Brutes', 1],
      ['Madame Masque', 1],
      ['Yellowjacket, Heartless Marauder', 1],
      ['Elektra, Daughter of the Hand', 1],
      ['Visions of Villainy', 1],
      ['Cruel Alliance', 1],
      ['Too Evil to Stay Dead', 1],
      ['Stolen Stark Tech', 1],
    ],
  },
  {
    id: 'msh-firepower',
    name: 'Firepower',
    color: 'R',
    face: 'Hawkeye, Master Marksman',
    blurb: 'Fast heroes and big hits',
    set: 'msh',
    spells: [
      ["K'un-Lun Warrior", 2],
      ['Human Torch, Johnny Storm', 1],
      ['Speed, Young Avenger', 1],
      ['Hawkeye, Master Marksman', 1],
      ['HULK SMASH!', 1],
      ['Team Tactics', 1],
      ['Blazing Crescendo', 2],
      ['Vision of Love', 1],
      ['Repulsor Blast', 1],
      ['Hire a Crew', 1],
    ],
  },
  {
    id: 'msh-robots',
    name: 'Robots',
    color: 'R',
    face: 'Fin Fang Foom',
    blurb: 'Killer robots and villains on a rampage',
    set: 'msh',
    spells: [
      ['HYDRA Assault Robot', 2],
      ['Machinesmith Automaton', 2],
      ['Volcanic Villain', 1],
      ['Crimson Operative', 1],
      ['Kree Sentinel', 1],
      ['Red Hulk', 1],
      ['Fin Fang Foom', 1],
      ['HULK SMASH!', 1],
      ['Repulsor Blast', 1],
      ['Hire a Crew', 1],
    ],
  },
  {
    id: 'msh-might',
    name: 'Might',
    color: 'G',
    face: 'The Unbeatable Squirrel Girl',
    blurb: 'Strong heroes who punch their way through',
    set: 'msh',
    spells: [
      ['Guerrilla Gorilla', 2],
      ['White Tiger, Ava Ayala', 1],
      ['Tigra, Feline Fury', 1],
      ['Hercules, Prince of Power', 1],
      ['She-Hulk, Jade Defender', 1],
      ['Wakandan Royal Guard', 1],
      ['The Thing, Ben Grimm', 1],
      ['The Unbeatable Squirrel Girl', 1],
      ['Go Nuts!', 1],
      ['Punishing Punch', 1],
      ['Rapid Rescue', 1],
    ],
  },
  {
    id: 'msh-wild-things',
    name: 'Wild Things',
    color: 'G',
    face: 'Mole Man, Moloid Master',
    blurb: 'Ants, dinosaurs and things from below',
    set: 'msh',
    spells: [
      ['Serpent Specialist', 1],
      ['Knight of Wundagore', 1],
      ["Ant-Man's Army", 2],
      ['Pet Avengers', 1],
      ['Undercover Skrull', 1],
      ['Savage Land Dinosaur', 1],
      ['Mole Man, Moloid Master', 1],
      ['Restorative Technique', 1],
      ['Training Regimen', 1],
      ['Go Nuts!', 1],
      ['Rapid Rescue', 1],
    ],
  },
];

const BASICS: Record<Color, string> = {
  W: 'Plains',
  U: 'Island',
  B: 'Swamp',
  R: 'Mountain',
  G: 'Forest',
};

/** A packet's full 20 cards: its spells and its basic lands. */
export function packetCards(p: Packet): [string, number][] {
  return [...p.spells, [BASICS[p.color], PACKET_LANDS]];
}
