import type { Color } from '@mtg/engine';

/**
 * Themed half-decks for Jump In!, Arena's mode where you pick two 20-card
 * packets and shuffle them together. Most are our own, ten per set
 * (Foundations, Bloomburrow, Marvel Super Heroes, Final Fantasy, Strixhaven, Secrets of
 * Strixhaven), plus cross-set custom themes: twelve spells
 * around a theme, one rare, plus eight basic lands of the packet's colour.
 * Arena's own Bloomburrow and Foundations packets are here too
 * (`ARENA_BLB_PACKETS`, `ARENA_FDN_PACKETS`).
 */
export interface Packet {
  id: string;
  name: string;
  /** One colour, or two for multicolour themes. */
  colors: Color[];
  /** Card shown on the packet. */
  face: string;
  blurb: string;
  /** Bloomburrow, Marvel Super Heroes, Final Fantasy, Strixhaven or Secrets of Strixhaven (default Foundations). Packets of different sets pair freely. */
  set?: 'blb' | 'msh' | 'fin' | 'stx' | 'sos';
  /** Arena's own packet (default: ours). */
  source?: 'arena';
  /** Custom theme that deliberately borrows cards from multiple sets. */
  crossSet?: boolean;
  /** The twelve spells; the basic lands are added by `packetCards`. */
  spells: [name: string, count: number][];
  /** Two-colour packets: their eight lands (default: eight basics of the colour). */
  lands?: [name: string, count: number][];
}

export const PACKET_LANDS = 8;

/** Our own packets: ten per set, plus cross-set custom themes. */
const OWN_PACKETS: Packet[] = [
  {
    id: 'angels',
    name: 'Angels',
    colors: ['W'],
    face: 'Giada, Font of Hope',
    blurb: 'Flyers that gain life and grow each other',
    spells: [
      ["Healer's Hawk", 1],
      ['Youthful Valkyrie', 2],
      ['Dazzling Angel', 2],
      ['Inspiring Overseer', 1],
      ['Angel of Vitality', 1],
      ['Giada, Font of Hope', 1],
      ['Vanguard Seraph', 1],
      ['Serra Angel', 1],
      ['Pacifism', 1],
      ['Moment of Triumph', 1],
    ],
  },
  {
    id: 'cats',
    name: 'Cats',
    colors: ['W'],
    face: 'Arahbo, the First Fang',
    blurb: 'Cheap cats that pounce early and pile on',
    spells: [
      ['Savannah Lions', 1],
      ['Leonin Vanguard', 1],
      ['Helpful Hunter', 2],
      ['Dawnwing Marshal', 1],
      ["Ajani's Pridemate", 1],
      ['Arahbo, the First Fang', 1],
      ['Cat Collector', 1],
      ['Felidar Savior', 1],
      ['Valorous Stance', 1],
      ['Banishing Light', 1],
      ['Claws Out', 1],
    ],
  },
  {
    id: 'wizards',
    name: 'Wizards',
    colors: ['U'],
    face: 'Drake Hatcher',
    blurb: 'Cast spells, draw cards, counter theirs',
    spells: [
      ['Opt', 2],
      ['Mischievous Mystic', 2],
      ['Drake Hatcher', 1],
      ['Fog Bank', 1],
      ['Exclusion Mage', 1],
      ['Quick Study', 1],
      ['Procrastinate', 1],
      ['Faebloom Trick', 1],
      ['Arcane Epiphany', 1],
      ['Tolarian Terror', 1],
    ],
  },
  {
    id: 'pirates',
    name: 'Pirates',
    colors: ['U'],
    face: 'Kiora, the Rising Tide',
    blurb: 'Slippery raiders that dig for the right card',
    spells: [
      ['Spectral Sailor', 2],
      ['Dive Down', 1],
      ['Brineborn Cutthroat', 2],
      ['Chart a Course', 1],
      ['Kiora, the Rising Tide', 1],
      ['Aegis Turtle', 1],
      ['Inspiration from Beyond', 1],
      ['Bigfin Bouncer', 2],
      ['Tolarian Terror', 1],
    ],
  },
  {
    id: 'vampires',
    name: 'Vampires',
    colors: ['B'],
    face: 'High-Society Hunter',
    blurb: 'Drain life and pick off their creatures',
    spells: [
      ['Vampiric Rites', 1],
      ['Stab', 1],
      ['Vampire Gourmand', 2],
      ['Sanguine Syphoner', 1],
      ['Vengeful Bloodwitch', 1],
      ['Moment of Craving', 1],
      ['Vampire Nighthawk', 1],
      ['Infernal Vessel', 1],
      ['Tribute to Hunger', 1],
      ["Hero's Downfall", 1],
      ['High-Society Hunter', 1],
    ],
  },
  {
    id: 'undead',
    name: 'Undead',
    colors: ['B'],
    face: 'Midnight Reaper',
    blurb: 'Creatures that keep coming back',
    spells: [
      ['Diregraf Ghoul', 2],
      ['Eaten Alive', 1],
      ['Undying Malice', 1],
      ['Reassembling Skeleton', 1],
      ['Crow of Dark Tidings', 2],
      ['Midnight Reaper', 1],
      ['Bake into a Pie', 1],
      ['Billowing Shriekmass', 1],
      ['Zombify', 1],
      ['Tragic Banshee', 1],
    ],
  },
  {
    id: 'goblins',
    name: 'Goblins',
    colors: ['R'],
    face: 'Krenko, Mob Boss',
    blurb: 'A swarm of goblins, and a boss who makes more',
    spells: [
      ['Fanatical Firebrand', 1],
      ['Frenzied Goblin', 1],
      ['Burst Lightning', 1],
      ['Kindled Fury', 1],
      ['Swab Goblin', 1],
      ['Courageous Goblin', 1],
      ['Dragon Fodder', 1],
      ['Raging Redcap', 1],
      ['Goblin Boarders', 1],
      ['Guttersnipe', 1],
      ['Goblin Surprise', 1],
      ['Krenko, Mob Boss', 1],
    ],
  },
  {
    id: 'dragonfire',
    name: 'Dragonfire',
    colors: ['R'],
    face: 'Shivan Dragon',
    blurb: 'Burn a path for a dragon',
    spells: [
      ['Ghitu Lavarunner', 1],
      ['Sure Strike', 1],
      ['Viashino Pyromancer', 1],
      ['Heartfire Immolator', 1],
      ['Firebrand Archer', 1],
      ['Scorching Dragonfire', 1],
      ['Fiery Annihilation', 1],
      ['Ball Lightning', 1],
      ['Spitfire Lagac', 1],
      ['Skyraker Giant', 1],
      ['Dragon Trainer', 1],
      ['Shivan Dragon', 1],
    ],
  },
  {
    id: 'elves',
    name: 'Elves',
    colors: ['G'],
    face: 'Imperious Perfect',
    blurb: 'Mana elves into a big elf army',
    spells: [
      ['Llanowar Elves', 2],
      ['Giant Growth', 1],
      ['Snakeskin Veil', 1],
      ['Thornweald Archer', 1],
      ["Dwynen's Elite", 1],
      ['Scavenging Ooze', 1],
      ['Bite Down', 1],
      ['Imperious Perfect', 1],
      ['Beast-Kin Ranger', 1],
      ['Wildheart Invoker', 1],
      ['Tajuru Pathwarden', 1],
    ],
  },
  {
    id: 'stompers',
    name: 'Stompers',
    colors: ['G'],
    face: 'Rampaging Baloths',
    blurb: 'Huge beasts and the mana to cast them',
    spells: [
      ['Llanowar Elves', 1],
      ['Bushwhack', 1],
      ['Giant Growth', 1],
      ['Bear Cub', 1],
      ['Eager Trufflesnout', 1],
      ['Felling Blow', 1],
      ['Gnarlback Rhino', 1],
      ['Magnigoth Sentry', 1],
      ['Needletooth Pack', 1],
      ['Elfsworn Giant', 1],
      ['Rampaging Baloths', 1],
      ['Pelakka Wurm', 1],
    ],
  },
  // Bloomburrow: our own packets, one theme per animal family.
  {
    id: 'blb-rabbits',
    name: 'Rabbits',
    colors: ['W'],
    face: 'Valley Questcaller',
    blurb: 'A warren that keeps growing and goes wide',
    set: 'blb',
    spells: [
      ['Brave-Kin Duo', 1],
      ['Seasoned Warrenguard', 1],
      ['Warren Elder', 1],
      ['Intrepid Rabbit', 2],
      ['Harvestrite Host', 1],
      ['Valley Questcaller', 1],
      ['Hop to It', 1],
      ['Rabbit Response', 1],
      ['Crumb and Get It', 1],
      ['Carrot Cake', 1],
      ['Repel Calamity', 1],
    ],
  },
  {
    id: 'blb-mice',
    name: 'Mice',
    colors: ['W'],
    face: 'Whiskervale Forerunner',
    blurb: 'Valiant soldiers that grow when you target them',
    set: 'blb',
    spells: [
      ['Flowerfoot Swordmaster', 1],
      ['Nettle Guard', 2],
      ['Brightblade Stoat', 1],
      ['Mouse Trapper', 1],
      ['Thistledown Players', 1],
      ['Whiskervale Forerunner', 1],
      ["Mabel's Mettle", 1],
      ['Brave-Kin Duo', 1],
      ['Sonar Strike', 1],
      ['Feather of Flight', 1],
      ['Dewdrop Cure', 1],
    ],
  },
  {
    id: 'blb-otters',
    name: 'Otters',
    colors: ['U'],
    face: 'Thundertrap Trainer',
    blurb: 'Spellslingers that fill the air with tricks',
    set: 'blb',
    spells: [
      ['Thundertrap Trainer', 1],
      ['Bellowing Crier', 1],
      ['Mindwhisker', 1],
      ['Plumecreed Escort', 1],
      ['Daring Waverider', 1],
      ['Otterball Antics', 2],
      ['Pearl of Wisdom', 1],
      ['Into the Flood Maw', 1],
      ['Dazzling Denial', 1],
      ['Shore Up', 1],
      ['Dire Downdraft', 1],
    ],
  },
  {
    id: 'blb-frogs',
    name: 'Frogs',
    colors: ['U'],
    face: 'Dour Port-Mage',
    blurb: 'Frogs and birds that bounce and come back',
    set: 'blb',
    spells: [
      ['Dour Port-Mage', 1],
      ['Long River Lurker', 1],
      ['Waterspout Warden', 2],
      ['Splash Lasher', 1],
      ['Finch Formation', 1],
      ['Knightfisher', 1],
      ['Skyskipper Duo', 1],
      ["Long River's Pull", 1],
      ['Shore Up', 1],
      ['Splash Portal', 1],
      ['Eddymurk Crab', 1],
    ],
  },
  {
    id: 'blb-bats',
    name: 'Bats',
    colors: ['B'],
    face: 'Darkstar Augur',
    blurb: 'Fliers that drain life every time it changes',
    set: 'blb',
    spells: [
      ['Starscape Cleric', 2],
      ['Moonstone Harbinger', 1],
      ['Starlit Soothsayer', 2],
      ['Glidedive Duo', 1],
      ['Darkstar Augur', 1],
      ['Savor', 1],
      ['Nocturnal Hunger', 1],
      ['Diresight', 1],
      ['Fell', 1],
      ['Consumed by Greed', 1],
    ],
  },
  {
    id: 'blb-rats',
    name: 'Rats',
    colors: ['B'],
    face: 'Valley Rotcaller',
    blurb: 'Rats and squirrels that grind out the long game',
    set: 'blb',
    spells: [
      ['Bonebind Orator', 1],
      ['Daggerfang Duo', 1],
      ['Thornplate Intimidator', 1],
      ['Persistent Marshstalker', 2],
      ['Bonecache Overseer', 1],
      ['Valley Rotcaller', 1],
      ["Wick's Patrol", 1],
      ['Scales of Shale', 1],
      ['Psychic Whorl', 1],
      ['Early Winter', 1],
      ['Feed the Cycle', 1],
    ],
  },
  {
    id: 'blb-hero-mice',
    name: 'Hero Mice',
    colors: ['R'],
    face: 'Manifold Mouse',
    blurb: 'Fast heroes pumped by every trick you cast',
    set: 'blb',
    spells: [
      ['Heartfire Hero', 2],
      ['Whiskerquill Scribe', 2],
      ['Brambleguard Captain', 1],
      ['Roughshod Duo', 1],
      ['Manifold Mouse', 1],
      ['Might of the Meek', 2],
      ['War Squeak', 1],
      ['Rabid Gnaw', 1],
      ['Valley Rally', 1],
    ],
  },
  {
    id: 'blb-lizards',
    name: 'Lizards',
    colors: ['R'],
    face: 'Valley Flamecaller',
    blurb: 'Lizards that burn the opponent as they fight',
    set: 'blb',
    spells: [
      ['Steampath Charger', 2],
      ['Flamecache Gecko', 1],
      ['Frilled Sparkshooter', 1],
      ['Reptilian Recruiter', 1],
      ['Kindlespark Duo', 1],
      ['Valley Flamecaller', 1],
      ['Agate Assault', 1],
      ['Take Out the Trash', 1],
      ['Blooming Blast', 1],
      ["Sazacap's Brew", 1],
      ['Conduct Electricity', 1],
    ],
  },
  {
    id: 'blb-squirrels',
    name: 'Squirrels',
    colors: ['G'],
    face: 'Thornvault Forager',
    blurb: 'Squirrels that stash Food and forage for value',
    set: 'blb',
    spells: [
      ['Bakersbane Duo', 1],
      ['Bushy Bodyguard', 1],
      ['Curious Forager', 1],
      ['Honored Dreyleader', 1],
      ['Treetop Sentries', 2],
      ['Thornvault Forager', 1],
      ['Heaped Harvest', 1],
      ['Cache Grab', 1],
      ['Longstalk Brawl', 1],
      ['Stocking the Pantry', 1],
      ['Overprotect', 1],
    ],
  },
  {
    id: 'blb-woodland',
    name: 'Woodland',
    colors: ['G'],
    face: 'Mistbreath Elder',
    blurb: 'Frogs, raccoons and big beasts of the wood',
    set: 'blb',
    spells: [
      ['Sunshower Druid', 1],
      ['Stickytongue Sentinel', 1],
      ['Clifftop Lookout', 1],
      ['Treeguard Duo', 1],
      ['Bark-Knuckle Boxer', 1],
      ['Brambleguard Veteran', 1],
      ['Rust-Shield Rampager', 1],
      ['Galewind Moose', 1],
      ['Mistbreath Elder', 1],
      ['High Stride', 1],
      ['Polliwallop', 1],
      ['Hazardroot Herbalist', 1],
    ],
  },
  // Marvel Super Heroes: our own packets around the set's teams and themes.
  {
    id: 'msh-shield',
    name: 'S.H.I.E.L.D.',
    colors: ['W'],
    face: 'Agent Phil Coulson',
    blurb: 'Agents and spies who back each other up',
    set: 'msh',
    spells: [
      ['Agent Maria Hill', 1],
      ['Agent of Atlas', 2],
      ['Agents of S.H.I.E.L.D.', 2],
      ['Agent 13, Sharon Carter', 1],
      ['Agent Phil Coulson', 1],
      ['Raft Security Officer', 1],
      ['Helicarrier Strike', 1],
      ['Take Up the Shield', 1],
      ["Murdock's Crusade", 1],
      ['Super Villain Lockup', 1],
    ],
  },
  {
    id: 'msh-avengers',
    name: 'Avengers',
    colors: ['W'],
    face: 'Captain America, Wings of Freedom',
    blurb: 'Heroes who assemble and fight as a team',
    set: 'msh',
    spells: [
      ['Brave Brawler', 2],
      ['Hero in Training', 2],
      ['Patriot, Shield Wielder', 1],
      ['Luke Cage, Power Man', 1],
      ['Okoye, Dora Milaje Leader', 1],
      ['Captain Mar-Vell, Space-Born', 1],
      ['Captain America, Wings of Freedom', 1],
      ['Panther Pounce', 1],
      ['Take Up the Shield', 1],
      ['Borough Backup', 1],
    ],
  },
  {
    id: 'msh-scientists',
    name: 'Scientists',
    colors: ['U'],
    face: 'Leader, Super-Genius',
    blurb: 'Geniuses with gadgets and clever answers',
    set: 'msh',
    spells: [
      ['Bold Biochemist', 2],
      ['A.I.M. Scientists', 1],
      ['Mister Fantastic, Reed Richards', 1],
      ['Leader, Super-Genius', 1],
      ['Futurist Forge', 1],
      ['Pym Particles', 1],
      ['Depower', 1],
      ['We Say Thee Nay!', 1],
      ["Trickster's Stratagem", 1],
      ['Super Suit', 1],
      ['Giant-Sized Flying Ant', 1],
    ],
  },
  {
    id: 'msh-sky-and-sea',
    name: 'Sky and Sea',
    colors: ['U'],
    face: 'The Wondrous Wasp',
    blurb: 'Fliers and Atlanteans that strike from above',
    set: 'msh',
    spells: [
      ['Aerial Doombot', 1],
      ['Atlantean Cavalry', 2],
      ['S.H.I.E.L.D. Deployment Drone', 1],
      ['Giant-Sized Flying Ant', 1],
      ['Falcon, Winged Wonder', 1],
      ['The Wondrous Wasp', 1],
      ['Depower', 1],
      ['We Say Thee Nay!', 1],
      ['Pym Particles', 1],
      ["Trickster's Stratagem", 1],
      ['Super Suit', 1],
    ],
  },
  {
    id: 'msh-hydra',
    name: 'HYDRA',
    colors: ['B'],
    face: 'Baron Helmut Zemo',
    blurb: 'Cut off one head, two more take its place',
    set: 'msh',
    spells: [
      ['Agents of HYDRA', 2],
      ['HYDRA Troopers', 2],
      ['Red Room Recruit', 1],
      ['Baron Strucker, HYDRA Overlord', 1],
      ['Crossbones, Malicious Mercenary', 1],
      ['Baron Helmut Zemo', 1],
      ['HYDRA Infiltration', 1],
      ['Dark Deed', 1],
      ["Widow's Bite", 1],
      ['Hour of Defeat', 1],
    ],
  },
  {
    id: 'msh-villains',
    name: 'Villains',
    colors: ['B'],
    face: 'Elektra, Daughter of the Hand',
    blurb: 'Ninjas, enforcers and villains who won’t stay dead',
    set: 'msh',
    spells: [
      ['Ninja of the Hand', 2],
      ["Kingpin's Enforcers", 1],
      ['Unliving Legionnaire', 1],
      ['Roxxon Brutes', 1],
      ['Madame Masque', 1],
      ['Yellowjacket, Heartless Marauder', 1],
      ['Elektra, Daughter of the Hand', 1],
      ['Visions of Villainy', 1],
      ['Cruel Alliance', 1],
      ['Too Evil to Stay Dead', 1],
      ['Stolen Stark Tech', 1],
    ],
  },
  {
    id: 'msh-firepower',
    name: 'Firepower',
    colors: ['R'],
    face: 'Hawkeye, Master Marksman',
    blurb: 'Fast heroes and big hits',
    set: 'msh',
    spells: [
      ["K'un-Lun Warrior", 2],
      ['Human Torch, Johnny Storm', 1],
      ['Speed, Young Avenger', 1],
      ['Hawkeye, Master Marksman', 1],
      ['HULK SMASH!', 1],
      ['Team Tactics', 1],
      ['Blazing Crescendo', 2],
      ['Vision of Love', 1],
      ['Repulsor Blast', 1],
      ['Hire a Crew', 1],
    ],
  },
  {
    id: 'msh-robots',
    name: 'Robots',
    colors: ['R'],
    face: 'Fin Fang Foom',
    blurb: 'Killer robots and villains on a rampage',
    set: 'msh',
    spells: [
      ['HYDRA Assault Robot', 2],
      ['Machinesmith Automaton', 2],
      ['Volcanic Villain', 1],
      ['Crimson Operative', 1],
      ['Kree Sentinel', 1],
      ['Red Hulk', 1],
      ['Fin Fang Foom', 1],
      ['HULK SMASH!', 1],
      ['Repulsor Blast', 1],
      ['Hire a Crew', 1],
    ],
  },
  {
    id: 'msh-might',
    name: 'Might',
    colors: ['G'],
    face: 'The Unbeatable Squirrel Girl',
    blurb: 'Strong heroes who punch their way through',
    set: 'msh',
    spells: [
      ['Guerrilla Gorilla', 2],
      ['White Tiger, Ava Ayala', 1],
      ['Tigra, Feline Fury', 1],
      ['Hercules, Prince of Power', 1],
      ['She-Hulk, Jade Defender', 1],
      ['Wakandan Royal Guard', 1],
      ['The Thing, Ben Grimm', 1],
      ['The Unbeatable Squirrel Girl', 1],
      ['Go Nuts!', 1],
      ['Punishing Punch', 1],
      ['Rapid Rescue', 1],
    ],
  },
  {
    id: 'msh-wild-things',
    name: 'Wild Things',
    colors: ['G'],
    face: 'Mole Man, Moloid Master',
    blurb: 'Ants, dinosaurs and things from below',
    set: 'msh',
    spells: [
      ['Serpent Specialist', 1],
      ['Knight of Wundagore', 1],
      ["Ant-Man's Army", 2],
      ['Pet Avengers', 1],
      ['Undercover Skrull', 1],
      ['Savage Land Dinosaur', 1],
      ['Mole Man, Moloid Master', 1],
      ['Restorative Technique', 1],
      ['Training Regimen', 1],
      ['Go Nuts!', 1],
      ['Rapid Rescue', 1],
    ],
  },
  {
    id: 'msh-ten-rings',
    name: 'Ten Rings',
    colors: ['W', 'U'],
    face: 'Shang-Chi and the Ten Rings',
    blurb: 'Draw cards, grow Shang-Chi and strike through with flying allies',
    set: 'msh',
    crossSet: true,
    spells: [
      ['Shang-Chi and the Ten Rings', 1],
      ['Helpful Hunter', 2],
      ['Inspiring Overseer', 1],
      ['Spectral Sailor', 1],
      ['Mischievous Mystic', 1],
      ['Opt', 2],
      ['Quick Study', 1],
      ['Shore Up', 1],
      ['Banishing Light', 1],
      ['Faebloom Trick', 1],
    ],
    lands: [
      ['Thriving Isle', 2],
      ['Island', 3],
      ['Plains', 3],
    ],
  },
  {
    id: 'msh-reborn-avengers',
    name: 'Reborn Avengers',
    colors: ['W'],
    face: 'Winter Soldier, Reborn Avenger',
    blurb: 'Trade Heroes early, then bring them back stronger with Winter Soldier',
    set: 'msh',
    crossSet: true,
    spells: [
      ['Winter Soldier, Reborn Avenger', 1],
      ['Peggy Carter, Secret Agent', 1],
      ['Hero in Training', 2],
      ['Brave Brawler', 1],
      ['Colleen Wing, Street Samurai', 1],
      ['Agent of Atlas', 1],
      ['Okoye, Dora Milaje Leader', 1],
      ['Goldvein Pick', 1],
      ['Take Up the Shield', 1],
      ['Secure Detention', 1],
      ['Moment of Triumph', 1],
    ],
  },
  // Strixhaven: our own packets around the school's creature types and spells.
  {
    id: 'stx-spirits',
    name: 'Spirits',
    colors: ['W'],
    face: 'Strict Proctor',
    blurb: 'Spirits that guard the campus and fend off spells',
    set: 'stx',
    spells: [
      ['Stonerise Spirit', 2],
      ['Pillardrop Rescuer', 1],
      ['Ageless Guardian', 2],
      ['Pilgrim of the Ages', 1],
      ["Stonebinder's Familiar", 1],
      ['Strict Proctor', 1],
      ['Combat Professor', 1],
      ['Expel', 1],
      ['Defend the Campus', 1],
      ['Guiding Voice', 1],
    ],
  },
  {
    id: 'stx-lecturers',
    name: 'Lecturers',
    colors: ['W'],
    face: 'Elite Spellbinder',
    blurb: 'Eager students and coaches who keep the class in line',
    set: 'stx',
    spells: [
      ['Eager First-Year', 2],
      ['Star Pupil', 1],
      ['Professor of Symbology', 1],
      ['Dueling Coach', 1],
      ['Clever Lumimancer', 1],
      ['Thunderous Orator', 1],
      ['Elite Spellbinder', 1],
      ['Study Break', 1],
      ['Beaming Defiance', 1],
      ['Show of Confidence', 1],
      ['Reduce to Memory', 1],
    ],
  },
  {
    id: 'stx-wizards',
    name: 'Wizards',
    colors: ['U'],
    face: 'Torrent Sculptor',
    blurb: 'Wizards, flyers and counterspells',
    set: 'stx',
    spells: [
      ['Frost Trickster', 2],
      ['Waterfall Aerialist', 1],
      ['Vortex Runner', 1],
      ['Soothsayer Adept', 1],
      ['Symmetry Sage', 1],
      ['Torrent Sculptor', 1],
      ['Pop Quiz', 1],
      ['Divide by Zero', 1],
      ['Reject', 1],
      ['Curate', 1],
      ['Arcane Subtraction', 1],
    ],
  },
  {
    id: 'stx-depths',
    name: 'Strixes and Serpents',
    colors: ['U'],
    face: 'Dream Strix',
    blurb: 'Strixes, serpents and tricks from the deep',
    set: 'stx',
    spells: [
      ['Dream Strix', 1],
      ['Wormhole Serpent', 1],
      ['Kelpie Guide', 1],
      ['Soothsayer Adept', 2],
      ['Vortex Runner', 1],
      ['Serpentine Curve', 2],
      ['Resculpt', 1],
      ['Bury in Books', 1],
      ['Snow Day', 1],
      ["Mentor's Guidance", 1],
    ],
  },
  {
    id: 'stx-warlocks',
    name: 'Warlocks',
    colors: ['B'],
    face: 'Callous Bloodmage',
    blurb: 'Warlocks who drain and dispatch',
    set: 'stx',
    spells: [
      ['Leech Fanatic', 2],
      ['Arrogant Poet', 1],
      ['Novice Dissector', 1],
      ['Promising Duskmage', 1],
      ['Tenured Inkcaster', 1],
      ['Callous Bloodmage', 1],
      ['Lash of Malice', 1],
      ['Essence Infusion', 1],
      ['Crushing Disappointment', 1],
      ["Professor's Warning", 1],
      ['Hunt for Specimens', 1],
    ],
  },
  {
    id: 'stx-specters',
    name: 'Specters and Horrors',
    colors: ['B'],
    face: 'Sedgemoor Witch',
    blurb: 'Specters, horrors and removal',
    set: 'stx',
    spells: [
      ['Specter of the Fens', 2],
      ['Eyetwitch', 2],
      ['Mage Hunter', 1],
      ['Brackish Trudge', 1],
      ['Sedgemoor Witch', 1],
      ['Unwilling Ingredient', 1],
      ["Mage Hunters' Onslaught", 1],
      ['Necrotic Fumes', 1],
      ['Umbral Juke', 1],
      ['Flunk', 1],
    ],
  },
  {
    id: 'stx-shamans',
    name: 'Shamans',
    colors: ['R'],
    face: 'Flamescroll Celebrant',
    blurb: 'Shamans who turn spells into damage',
    set: 'stx',
    spells: [
      ['Illustrious Historian', 1],
      ['Twinscroll Shaman', 2],
      ['Storm-Kiln Artist', 1],
      ['Pillardrop Warden', 1],
      ['Hall Monitor', 1],
      ['Ardent Dustspeaker', 1],
      ['Flamescroll Celebrant', 1],
      ['Heated Debate', 1],
      ['Pigment Storm', 1],
      ['Sudden Breakthrough', 1],
      ['Enthusiastic Study', 1],
    ],
  },
  {
    id: 'stx-spellfire',
    name: 'Spellfire',
    colors: ['R'],
    face: 'Retriever Phoenix',
    blurb: 'Burn, spirits and a phoenix that keeps coming back',
    set: 'stx',
    spells: [
      ['Tome Shredder', 2],
      ['Fuming Effigy', 1],
      ['Blood Age General', 1],
      ['Grinning Ignus', 1],
      ['Retriever Phoenix', 1],
      ['Igneous Inspiration', 1],
      ['Academic Dispute', 1],
      ['Mascot Interception', 1],
      ['Start from Scratch', 1],
      ['First Day of Class', 1],
      ['Explosive Welcome', 1],
    ],
  },
  {
    id: 'stx-druids',
    name: 'Druids',
    colors: ['G'],
    face: 'Gnarled Professor',
    blurb: 'Druids and trolls that grow big',
    set: 'stx',
    spells: [
      ['Karok Wrangler', 1],
      ['Professor of Zoomancy', 2],
      ['Reckless Amplimancer', 2],
      ['Honor Troll', 1],
      ['Master Symmetrist', 1],
      ['Gnarled Professor', 1],
      ['Field Trip', 1],
      ['Big Play', 1],
      ['Leyline Invocation', 1],
      ['Charge Through', 1],
    ],
  },
  {
    id: 'stx-beasts',
    name: 'Beasts',
    colors: ['G'],
    face: 'Augmenter Pugilist',
    blurb: 'Crocodiles, wurms and trolls that fight',
    set: 'stx',
    spells: [
      ['Springmane Cervin', 1],
      ['Bayou Groff', 2],
      ['Spined Karok', 2],
      ['Bookwurm', 1],
      ['Scurrid Colony', 1],
      ['Overgrown Arch', 1],
      ['Augmenter Pugilist', 1],
      ['Mage Duel', 1],
      ['Tangletrap', 1],
      ['Fortifying Draught', 1],
    ],
  },
  // Secrets of Strixhaven: our own packets around the school's creature types and spells.
  {
    id: 'sos-clerics',
    name: 'Clerics',
    colors: ['W'],
    face: 'Joined Researchers',
    blurb: 'Cats, owls and elephants of the cloister',
    set: 'sos',
    spells: [
      ['Eager Glyphmage', 2],
      ['Honorbound Page', 2],
      ['Ascendant Dustspeaker', 1],
      ['Owlin Historian', 1],
      ['Spiritcall Enthusiast', 1],
      ['Inkshape Demonstrator', 1],
      ['Quill-Blade Laureate', 1],
      ['Joined Researchers', 1],
      ['Interjection', 1],
      ["Ajani's Response", 1],
    ],
  },
  {
    id: 'sos-debaters',
    name: 'Debate Team',
    colors: ['W'],
    face: 'Stirring Hopesinger',
    blurb: 'Interceptors, spirits and quick comebacks',
    set: 'sos',
    spells: [
      ['Elite Interceptor', 2],
      ['Stone Docent', 2],
      ['Summoned Dromedary', 1],
      ['Soaring Stoneglider', 1],
      ['Ennis, Debate Moderator', 1],
      ['Shattered Acolyte', 1],
      ['Rehearsed Debater', 1],
      ['Rapier Wit', 1],
      ['Harsh Annotation', 1],
      ['Stirring Hopesinger', 1],
    ],
  },
  {
    id: 'sos-merfolk',
    name: 'Merfolk Wizards',
    colors: ['U'],
    face: 'Harmonized Trio',
    blurb: 'Merfolk and wizards that keep the spells coming',
    set: 'sos',
    spells: [
      ['Landscape Painter', 2],
      ['Hydro-Channeler', 2],
      ['Campus Composer', 1],
      ['Orysa, Tide Choreographer', 1],
      ['Deluge Virtuoso', 1],
      ['Textbook Tabulator', 1],
      ['Muse Seeker', 1],
      ['Harmonized Trio', 1],
      ['Procrastinate', 1],
      ['Run Behind', 1],
    ],
  },
  {
    id: 'sos-skycoaches',
    name: 'Skycoaches',
    colors: ['U'],
    face: 'Skycoach Conductor',
    blurb: 'Flyers, study sessions and counterspells',
    set: 'sos',
    spells: [
      ['Spellbook Seeker', 2],
      ['Encouraging Aviator', 1],
      ['Tester of the Tangential', 1],
      ['Matterbending Mage', 1],
      ['Brush Off', 1],
      ['Banishing Betrayal', 1],
      ['Chase Inspiration', 1],
      ['Homesickness', 1],
      ['Flow State', 1],
      ['Skycoach Conductor', 1],
      ['Fractalize', 1],
    ],
  },
  {
    id: 'sos-warlocks',
    name: 'Warlocks',
    colors: ['B'],
    face: 'Grave Researcher',
    blurb: 'Warlocks, students and vampires of the night library',
    set: 'sos',
    spells: [
      ['Adventurous Eater', 2],
      ['Cheerful Osteomancer', 2],
      ['Burrog Banemaker', 1],
      ['Sneering Shadewriter', 1],
      ['Ulna Alley Shopkeep', 1],
      ['Eternal Student', 1],
      ['Leech Collector', 1],
      ['Last Gasp', 1],
      ['Grave Researcher', 1],
      ['Wander Off', 1],
    ],
  },
  {
    id: 'sos-curses',
    name: 'Curses and Pests',
    colors: ['B'],
    face: 'Scheming Silvertongue',
    blurb: 'Pests, removal and the cost of brilliance',
    set: 'sos',
    spells: [
      ['Send in the Pest', 2],
      ['Pull from the Grave', 1],
      ['Cost of Brilliance', 2],
      ['Masterful Flourish', 1],
      ['Foolish Fate', 1],
      ['End of the Hunt', 1],
      ['Dissection Practice', 1],
      ['Melancholic Poet', 1],
      ['Forum Necroscribe', 1],
      ['Scheming Silvertongue', 1],
    ],
  },
  {
    id: 'sos-sorcerers',
    name: 'Sorcerers',
    colors: ['R'],
    face: 'Maelstrom Artisan',
    blurb: 'Orcs, goblins and giants that cast and strike',
    set: 'sos',
    spells: [
      ['Expressive Firedancer', 2],
      ['Rubble Rouser', 1],
      ['Strife Scholar', 1],
      ['Tackle Artist', 1],
      ['Zealous Lorecaster', 1],
      ['Goblin Glasswright', 1],
      ['Pigment Wrangler', 1],
      ['Garrison Excavator', 1],
      ['Heated Argument', 1],
      ['Tome Blast', 1],
      ['Maelstrom Artisan', 1],
    ],
  },
  {
    id: 'sos-bards',
    name: 'Firebards',
    colors: ['R'],
    face: 'Molten-Core Maestro',
    blurb: 'Bards and beasts that burn the stage down',
    set: 'sos',
    spells: [
      ['Rearing Embermare', 2],
      ['Thunderdrum Soloist', 1],
      ['Blazing Firesinger', 1],
      ['Charging Strifeknight', 1],
      ['Mica, Reader of Ruins', 1],
      ['Ancestral Anger', 1],
      ['Unsubtle Mockery', 1],
      ["Archaic's Agony", 1],
      ['Duel Tactics', 1],
      ['Impractical Joke', 1],
      ['Molten-Core Maestro', 1],
    ],
  },
  {
    id: 'sos-druids',
    name: 'Druids',
    colors: ['G'],
    face: 'Vastlands Scavenger',
    blurb: 'Elves and dryads that grow the garden',
    set: 'sos',
    spells: [
      ['Mindful Biomancer', 2],
      ['Tenured Concocter', 1],
      ['Emil, Vastlands Roamer', 1],
      ['Environmental Scientist', 1],
      ['Thornfist Striker', 1],
      ['Topiary Lecturer', 2],
      ['Wild Hypothesis', 1],
      ['Efflorescence', 1],
      ['Follow the Lumarets', 1],
      ['Vastlands Scavenger', 1],
    ],
  },
  {
    id: 'sos-beasts',
    name: 'Beasts and Pests',
    colors: ['G'],
    face: 'Slumbering Trudge',
    blurb: 'Giraffes, newts and sloths that fight and fatten up',
    set: 'sos',
    spells: [
      ['Hungry Graffalon', 2],
      ['Studious First-Year', 1],
      ['Noxious Newt', 2],
      ["Shopkeeper's Bane", 1],
      ['Pestbrood Sloth', 1],
      ['Aberrant Manawurm', 1],
      ['Burrog Barrage', 1],
      ['Glorious Decay', 1],
      ['Chelonian Tackle', 1],
      ['Slumbering Trudge', 1],
    ],
  },
  // Final Fantasy: our own packets around the set's jobs, summons and creatures.
  {
    id: 'fin-knights',
    name: 'Knights',
    colors: ['W'],
    face: "Dion, Bahamut's Dominant",
    blurb: 'Heroes take up arms and fly with Bahamut',
    set: 'fin',
    spells: [
      ['Dwarven Castle Guard', 2],
      ['Zack Fair', 1],
      ['Adelbert Steiner', 1],
      ['Coeurl', 1],
      ['Weapons Vendor', 1],
      ["Dion, Bahamut's Dominant", 1],
      ["Paladin's Arms", 1],
      ["Dragoon's Lance", 1],
      ['Battle Menu', 1],
      ['Slash of Light', 1],
      ['Fate of the Sun-Cryst', 1],
    ],
  },
  {
    id: 'fin-white-magic',
    name: 'White Magic',
    colors: ['W'],
    face: 'Aerith Gainsborough',
    blurb: 'Healers and moogles who keep the party standing',
    set: 'fin',
    spells: [
      ['Aerith Gainsborough', 1],
      ["White Mage's Staff", 1],
      ['Ambrosia Whiteheart', 1],
      ['Snow Villiers', 1],
      ['Coeurl', 1],
      ['Cloudbound Moogle', 2],
      ['Delivery Moogle', 1],
      ['Summon: Choco/Mog', 1],
      ['Phoenix Down', 1],
      ['Restoration Magic', 1],
      ['White Auracite', 1],
    ],
  },
  {
    id: 'fin-summons',
    name: 'Summons',
    colors: ['U'],
    face: 'Summon: Leviathan',
    blurb: 'Call on Shiva and Leviathan to freeze and flood the field',
    set: 'fin',
    spells: [
      ["Dragoon's Wyvern", 2],
      ['Sahagin', 1],
      ['Il Mheg Pixie', 1],
      ['Qiqirn Merchant', 1],
      ['Ice Flan', 1],
      ['Summon: Shiva', 1],
      ['Summon: Leviathan', 1],
      ['Ice Magic', 1],
      ['Dreams of Laguna', 1],
      ["Stuck in Summoner's Sanctum", 1],
      ['Syncopate', 1],
    ],
  },
  {
    id: 'fin-airships',
    name: 'Airships',
    colors: ['U'],
    face: 'The Lunar Whale',
    blurb: 'Machina crews take to the skies',
    set: 'fin',
    spells: [
      ['Scorpion Sentinel', 2],
      ["Dragoon's Wyvern", 1],
      ['Rook Turret', 1],
      ['Valkyrie Aerial Unit', 1],
      ['The Prima Vista', 1],
      ['The Lunar Whale', 1],
      ["Thief's Knife", 1],
      ["Sage's Nouliths", 1],
      ['Retrieve the Esper', 1],
      ['Combat Tutorial', 1],
      ['Eject', 1],
    ],
  },
  {
    id: 'fin-black-mages',
    name: 'Black Mages',
    colors: ['B'],
    face: 'Dark Confidant',
    blurb: 'Every spell they cast sends a spark at the enemy',
    set: 'fin',
    spells: [
      ['Dark Confidant', 1],
      ['Hecteyes', 1],
      ['Ahriman', 1],
      ['Qutrub Forayer', 1],
      ["Shambling Cie'th", 1],
      ["Black Mage's Rod", 1],
      ['Cornered by Black Mages', 2],
      ['Circle of Power', 1],
      ["Vayne's Treachery", 1],
      ["Sephiroth's Intervention", 1],
      ['Poison the Waters', 1],
    ],
  },
  {
    id: 'fin-dark-knights',
    name: 'Dark Knights',
    colors: ['B'],
    face: 'Cecil, Dark Knight',
    blurb: 'Power drawn from darkness, at a price',
    set: 'fin',
    spells: [
      ['Cecil, Dark Knight', 1],
      ['Undercity Dire Rat', 2],
      ['Tonberry', 1],
      ['Reno and Rude', 1],
      ['Shinra Reinforcements', 1],
      ['Al Bhed Salvagers', 1],
      ['Demon Wall', 1],
      ['Malboro', 1],
      ["Dark Knight's Greatsword", 1],
      ['Overkill', 1],
      ['Fight On!', 1],
    ],
  },
  {
    id: 'fin-warriors',
    name: 'Warriors',
    colors: ['R'],
    face: 'Firion, Wild Rose Warrior',
    blurb: 'Pick a weapon and charge in',
    set: 'fin',
    spells: [
      ['Item Shopkeep', 2],
      ['Freya Crescent', 1],
      ['Prompto Argentum', 1],
      ['Firion, Wild Rose Warrior', 1],
      ['Barret Wallace', 1],
      ['Hill Gigas', 1],
      ["Red Mage's Rapier", 1],
      ["Samurai's Katana", 1],
      ["Warrior's Sword", 1],
      ['Thunder Magic', 1],
      ['Suplex', 1],
    ],
  },
  {
    id: 'fin-red-mages',
    name: 'Red Mages',
    colors: ['R'],
    face: "Clive, Ifrit's Dominant",
    blurb: 'Fire, thunder and the Eikon Ifrit',
    set: 'fin',
    spells: [
      ['Blazing Bomb', 1],
      ['Sabotender', 1],
      ['Mysidian Elder', 1],
      ['Queen Brahne', 1],
      ['Summon: G.F. Ifrit', 1],
      ['Summon: Esper Ramuh', 1],
      ["Clive, Ifrit's Dominant", 1],
      ['Fire Magic', 1],
      ['Thunder Magic', 1],
      ['Choco-Comet', 1],
      ['Laughing Mad', 1],
      ['Light of Judgment', 1],
    ],
  },
  {
    id: 'fin-chocobos',
    name: 'Chocobos',
    colors: ['G'],
    face: 'Bartz and Boko',
    blurb: 'A flock of chocobos that grows with every land',
    set: 'fin',
    spells: [
      ["Sazh's Chocobo", 2],
      ['Loporrit Scout', 1],
      ['Bartz and Boko', 1],
      ['Gysahl Greens', 2],
      ['Summon: Fat Chocobo', 1],
      ['Sidequest: Raise a Chocobo', 1],
      ["Prishe's Wanderings", 1],
      ['Chocobo Kick', 1],
      ['Blitzball Shot', 1],
      ['Clash of the Eikons', 1],
    ],
  },
  {
    id: 'fin-monsters',
    name: 'Monsters',
    colors: ['G'],
    face: 'Jumbo Cactuar',
    blurb: 'Cactuars, behemoths and other fiends of the wild',
    set: 'fin',
    spells: [
      ['Cactuar', 1],
      ['Gran Pulse Ochu', 1],
      ['Goobbue Gardener', 2],
      ['Town Greeter', 1],
      ['Gigantoad', 1],
      ['Balamb T-Rexaur', 1],
      ['Coliseum Behemoth', 1],
      ['Jumbo Cactuar', 1],
      ["Tifa's Limit Break", 1],
      ['Clash of the Eikons', 1],
      ['Airship Crash', 1],
    ],
  },
];

/**
 * MTG Arena's ten Bloomburrow packets (July 2024), from
 * https://magic.wizards.com/en/news/mtg-arena/jump-in-packets-update-for-bloomburrow.
 * Arena swaps a few cards for alternates at random; these are the listed
 * packets. Arena also picks the lands; two-colour packets get a gain-land and
 * basics split by their mana symbols.
 */
export const ARENA_BLB_PACKETS: Packet[] = [
  {
    id: 'blb-arena-bats',
    name: 'Bats',
    colors: ['W', 'B'],
    face: 'Zoraline, Cosmos Caller',
    blurb: 'Lifelinking Bats that bring back the fallen',
    set: 'blb',
    source: 'arena',
    spells: [
      ['Zoraline, Cosmos Caller', 1],
      ['Starseer Mentor', 1],
      ['Moonrise Cleric', 1],
      ['Lifecreed Duo', 1],
      ['Star Charter', 1],
      ['Sonar Strike', 1],
      ['Starlit Soothsayer', 1],
      ['Sinister Monolith', 1],
      ['Nocturnal Hunger', 1],
      ['Wax-Wane Witness', 1],
      ['Moonstone Harbinger', 1],
      ['Three Tree Mascot', 1],
    ],
    lands: [
      ['Scoured Barrens', 1],
      ['Plains', 4],
      ['Swamp', 3],
    ],
  },
  {
    id: 'blb-arena-otters',
    name: 'Otters',
    colors: ['U', 'R'],
    face: 'Alania, Divergent Storm',
    blurb: 'Noncreature spells that power up Otters',
    set: 'blb',
    source: 'arena',
    spells: [
      ['Alania, Divergent Storm', 1],
      ['Stormcatch Mentor', 1],
      ['Agate Assault', 1],
      ['Otterball Antics', 1],
      ['Daring Waverider', 1],
      ['Wildfire Howl', 1],
      ['Kindlespark Duo', 1],
      ['Coruscation Mage', 1],
      ['Harnesser of Storms', 1],
      ['Conduct Electricity', 1],
      ['Valley Rally', 1],
      ['Three Tree Mascot', 1],
    ],
    lands: [
      ['Swiftwater Cliffs', 1],
      ['Island', 2],
      ['Mountain', 5],
    ],
  },
  {
    id: 'blb-arena-squirrels',
    name: 'Squirrels',
    colors: ['B', 'G'],
    face: 'Camellia, the Seedmiser',
    blurb: 'Forage, Food and a well-stocked graveyard',
    set: 'blb',
    source: 'arena',
    spells: [
      ['Camellia, the Seedmiser', 1],
      ['Vinereap Mentor', 1],
      ['Corpseberry Cultivator', 1],
      ['Bonebind Orator', 1],
      ['Bonecache Overseer', 1],
      ["Wick's Patrol", 1],
      ['Treetop Sentries', 1],
      ['Cache Grab', 1],
      ['Bushy Bodyguard', 1],
      ['Feed the Cycle', 1],
      ['Honored Dreyleader', 1],
      ['Three Tree Mascot', 1],
    ],
    lands: [
      ['Jungle Hollow', 1],
      ['Swamp', 4],
      ['Forest', 3],
    ],
  },
  {
    id: 'blb-arena-mice',
    name: 'Mice',
    colors: ['R', 'W'],
    face: 'Mabel, Heir to Cragflame',
    blurb: 'Valiant Mice that hit hard',
    set: 'blb',
    source: 'arena',
    spells: [
      ['Mabel, Heir to Cragflame', 1],
      ['Seedglaive Mentor', 1],
      ['Veteran Guardmouse', 1],
      ['Brave-Kin Duo', 1],
      ['Brambleguard Captain', 1],
      ['Flowerfoot Swordmaster', 1],
      ["Mabel's Mettle", 1],
      ['Whiskerquill Scribe', 1],
      ['War Squeak', 1],
      ['Short Bow', 1],
      ['Heartfire Hero', 1],
      ['Three Tree Mascot', 1],
    ],
    lands: [
      ['Wind-Scarred Crag', 1],
      ['Mountain', 4],
      ['Plains', 3],
    ],
  },
  {
    id: 'blb-arena-frogs',
    name: 'Frogs',
    colors: ['G', 'U'],
    face: 'Clement, the Worrywort',
    blurb: 'Frogs that bounce and replay each other',
    set: 'blb',
    source: 'arena',
    spells: [
      ['Clement, the Worrywort', 1],
      ['Lilysplash Mentor', 1],
      ['Pond Prophet', 1],
      ['Bellowing Crier', 1],
      ['Splash Lasher', 1],
      ['Skyskipper Duo', 1],
      ['Long River Lurker', 1],
      ['Three Tree Scribe', 1],
      ['High Stride', 1],
      ['Sunshower Druid', 1],
      ['Stickytongue Sentinel', 1],
      ['Polliwallop', 1],
    ],
    lands: [
      ['Thornwood Falls', 1],
      ['Forest', 4],
      ['Island', 3],
    ],
  },
  {
    id: 'blb-arena-rabbits',
    name: 'Rabbits',
    colors: ['W'],
    face: 'Valley Questcaller',
    blurb: 'A warren of tokens that goes wide',
    set: 'blb',
    source: 'arena',
    spells: [
      ['Valley Questcaller', 1],
      ['Harvestrite Host', 1],
      ['Hop to It', 1],
      ['Seasoned Warrenguard', 1],
      ["Builder's Talent", 1],
      ['Rabbit Response', 1],
      ['Warren Elder', 1],
      ['Intrepid Rabbit', 1],
      ['Banishing Light', 1],
      ['Driftgloom Coyote', 1],
      ['Carrot Cake', 1],
      ['Patchwork Banner', 1],
    ],
  },
  {
    id: 'blb-arena-rats',
    name: 'Rats',
    colors: ['B'],
    face: "Cruelclaw's Heist",
    blurb: 'Thieving Rats with threshold',
    set: 'blb',
    source: 'arena',
    spells: [
      ["Cruelclaw's Heist", 1],
      ['Fell', 1],
      ["Bandit's Talent", 1],
      ['Thought-Stalker Warlock', 1],
      ['Thornplate Intimidator', 1],
      ['Agate-Blade Assassin', 1],
      ['Ravine Raider', 1],
      ['Ruthless Negotiation', 1],
      ['Consumed by Greed', 1],
      ['Huskburster Swarm', 1],
      ['Scales of Shale', 1],
      ['Psychic Whorl', 1],
    ],
  },
  {
    id: 'blb-arena-lizards',
    name: 'Lizards',
    colors: ['R'],
    face: 'Hearthborn Battler',
    blurb: 'Lizards that burn the opponent',
    set: 'blb',
    source: 'arena',
    spells: [
      ['Hearthborn Battler', 1],
      ['Quaketusk Boar', 1],
      ['Reptilian Recruiter', 1],
      ["Alania's Pathmaker", 1],
      ['Raccoon Rallier', 1],
      ['Roughshod Duo', 1],
      ['Flamecache Gecko', 1],
      ['Frilled Sparkshooter', 1],
      ['Blooming Blast', 1],
      ['Rabid Gnaw', 1],
      ["Sazacap's Brew", 1],
      ["Hoarder's Overflow", 1],
    ],
  },
  {
    id: 'blb-arena-threshold',
    name: 'Threshold',
    colors: ['U'],
    face: 'Portent of Calamity',
    blurb: 'Fill the graveyard, then cash in',
    set: 'blb',
    source: 'arena',
    spells: [
      ['Spellgyre', 1],
      ['Sugar Coat', 1],
      ['Portent of Calamity', 1],
      ['Dire Downdraft', 1],
      ['Mindwhisker', 1],
      ['Nightwhorl Hermit', 1],
      ['Bellowing Crier', 1],
      ['Thought Shucker', 1],
      ['Lightshell Duo', 1],
      ['Shoreline Looter', 1],
      ['Sterling Hound', 1],
      ['Shore Up', 1],
    ],
  },
  {
    id: 'blb-arena-exploring',
    name: 'Exploring',
    colors: ['G'],
    face: 'Tender Wildguide',
    blurb: 'Big creatures and lands from the graveyard',
    set: 'blb',
    source: 'arena',
    spells: [
      ['Tender Wildguide', 1],
      ['Galewind Moose', 1],
      ['Hivespine Wolverine', 1],
      ['Bark-Knuckle Boxer', 1],
      ["Hunter's Talent", 1],
      ['Clifftop Lookout', 1],
      ['Three Tree Rootweaver', 1],
      ['Stickytongue Sentinel', 1],
      ['Rust-Shield Rampager', 1],
      ['Heaped Harvest', 1],
      ['Pawpatch Formation', 1],
      ['Peerless Recycling', 1],
    ],
  },
];

/**
 * MTG Arena's eleven Foundations packets (November 2024), from
 * https://magic.wizards.com/en/news/mtg-arena/jump-in-packets-update-for-foundations.
 * Like the Bloomburrow ones, these are the listed packets. Arena adds the
 * lands: the packet's own (a guildgate or Evolving Wilds), then basics split
 * by mana symbols.
 */
export const ARENA_FDN_PACKETS: Packet[] = [
  {
    id: 'fdn-arena-flyers',
    name: 'Flyers',
    colors: ['W', 'U'],
    face: 'High Fae Trickster',
    blurb: 'Flyers, and tricks at instant speed',
    source: 'arena',
    spells: [
      ['High Fae Trickster', 1],
      ['Empyrean Eagle', 1],
      ['Cloudblazer', 1],
      ['Leonin Skyhunter', 1],
      ['Faebloom Trick', 1],
      ['Kitesail Corsair', 1],
      ['Inspiring Overseer', 1],
      ['Skyship Buccaneer', 1],
      ['Spectral Sailor', 1],
      ['Luminous Rebuke', 1],
      ['Fleeting Flight', 1],
    ],
    lands: [
      ['Azorius Guildgate', 1],
      ['Plains', 4],
      ['Island', 4],
    ],
  },
  {
    id: 'fdn-arena-threshold',
    name: 'Threshold',
    colors: ['U', 'B'],
    face: 'Kiora, the Rising Tide',
    blurb: 'Fill the graveyard; seven cards turns it on',
    source: 'arena',
    spells: [
      ['Kiora, the Rising Tide', 1],
      ['Dreadwing Scavenger', 1],
      ['Cephalid Inkmage', 1],
      ['Billowing Shriekmass', 1],
      ['Rune-Sealed Wall', 1],
      ['Chart a Course', 1],
      ['Eaten by Piranhas', 1],
      ['Uncharted Voyage', 1],
      ['Quick Study', 1],
      ['Strix Lookout', 1],
      ['Refute', 1],
    ],
    lands: [
      ['Dimir Guildgate', 1],
      ['Island', 6],
      ['Swamp', 2],
    ],
  },
  {
    id: 'fdn-arena-raiders',
    name: 'Raiders',
    colors: ['B', 'R'],
    face: 'Alesha, Who Laughs at Fate',
    blurb: 'Attackers that make every death hurt',
    source: 'arena',
    spells: [
      ['Alesha, Who Laughs at Fate', 1],
      ['Perforating Artist', 1],
      ['Garna, Bloodfist of Keld', 1],
      ['Sower of Chaos', 1],
      ['Strongbox Raider', 1],
      ['Frenzied Goblin', 1],
      ['Sanguine Syphoner', 1],
      ['Goblin Smuggler', 1],
      ['Burst Lightning', 1],
      ['Feed the Swarm', 1],
      ['Vengeful Bloodwitch', 1],
    ],
    lands: [
      ['Rakdos Guildgate', 1],
      ['Mountain', 5],
      ['Swamp', 3],
    ],
  },
  {
    id: 'fdn-arena-growth',
    name: 'Growth',
    colors: ['R', 'G'],
    face: 'Ruby, Daring Tracker',
    blurb: 'Big creatures and the burn to clear the way',
    source: 'arena',
    spells: [
      ['Sylvan Scavenging', 1],
      ['Ruby, Daring Tracker', 1],
      ['Elvish Regrower', 1],
      ['Nessian Hornbeetle', 1],
      ['Bolt Bend', 1],
      ['Courageous Goblin', 1],
      ['Battle-Rattle Shaman', 1],
      ['Treetop Snarespinner', 1],
      ['Gnarlid Colony', 1],
      ['Sure Strike', 1],
      ['Obliterating Bolt', 1],
    ],
    lands: [
      ['Gruul Guildgate', 1],
      ['Forest', 5],
      ['Mountain', 3],
    ],
  },
  {
    id: 'fdn-arena-strong',
    name: 'Strong',
    colors: ['G', 'W'],
    face: 'Mossborn Hydra',
    blurb: '+1/+1 counters that keep growing',
    source: 'arena',
    spells: [
      ['Mossborn Hydra', 1],
      ['Inspiring Call', 1],
      ['Good-Fortune Unicorn', 1],
      ['Ordeal of Nylea', 1],
      ['Wildwood Scourge', 1],
      ['Mild-Mannered Librarian', 1],
      ['Bite Down', 1],
      ['Treetop Snarespinner', 1],
      ['Gnarlid Colony', 1],
      ['Bushwhack', 1],
      ['Felidar Savior', 1],
    ],
    lands: [
      ['Selesnya Guildgate', 1],
      ['Forest', 6],
      ['Plains', 2],
    ],
  },
  {
    id: 'fdn-arena-cats',
    name: 'Cats',
    colors: ['W'],
    face: 'Arahbo, the First Fang',
    blurb: 'Cats that pounce together',
    source: 'arena',
    spells: [
      ['Arahbo, the First Fang', 1],
      ['Ingenious Leonin', 1],
      ['Prideful Parent', 1],
      ['Dawnwing Marshal', 1],
      ['Felidar Savior', 1],
      ['Savannah Lions', 1],
      ['Helpful Hunter', 1],
      ["Ajani's Pridemate", 1],
      ['Prayer of Binding', 1],
      ['Joust Through', 1],
      ['Claws Out', 1],
    ],
    lands: [
      ['Evolving Wilds', 1],
      ['Plains', 8],
    ],
  },
  {
    id: 'fdn-arena-drawing',
    name: 'Drawing',
    colors: ['U'],
    face: 'Homunculus Horde',
    blurb: 'Draw two a turn and cash in',
    source: 'arena',
    spells: [
      ['Homunculus Horde', 1],
      ['Erudite Wizard', 1],
      ['Refute', 1],
      ['Spectral Sailor', 1],
      ['Arcane Epiphany', 1],
      ['Mischievous Mystic', 1],
      ['Clinquant Skymage', 1],
      ['Storm Fleet Spy', 1],
      ['Eaten by Piranhas', 1],
      ['Strix Lookout', 1],
      ['Think Twice', 1],
    ],
    lands: [
      ['Evolving Wilds', 1],
      ['Island', 8],
    ],
  },
  {
    id: 'fdn-arena-zombies',
    name: 'Zombie',
    colors: ['B'],
    face: 'Zul Ashur, Lich Lord',
    blurb: 'Zombies and deathtouch that drain',
    source: 'arena',
    spells: [
      ['Zul Ashur, Lich Lord', 1],
      ['Maalfeld Twins', 1],
      ['Soul-Shackled Zombie', 1],
      ['Crow of Dark Tidings', 1],
      ['Hungry Ghoul', 1],
      ['Deadly Plot', 1],
      ['Moment of Craving', 1],
      ['Vampiric Rites', 1],
      ['Diregraf Ghoul', 1],
      ['Knight of Malice', 1],
      ['Vampire Gourmand', 1],
    ],
    lands: [
      ['Evolving Wilds', 1],
      ['Swamp', 8],
    ],
  },
  {
    id: 'fdn-arena-goblins',
    name: 'Goblins',
    colors: ['R'],
    face: 'Dropkick Bomber',
    blurb: 'A goblin horde and Impact Tremors',
    source: 'arena',
    spells: [
      ['Dropkick Bomber', 1],
      ['Dragon Fodder', 1],
      ['Goblin Surprise', 1],
      ['Impact Tremors', 1],
      ['Goblin Negotiation', 1],
      ['Goblin Oriflamme', 1],
      ['Goblin Smuggler', 1],
      ['Volley Veteran', 1],
      ['Sure Strike', 1],
      ['Fiery Annihilation', 1],
      ['Obliterating Bolt', 1],
    ],
    lands: [
      ['Evolving Wilds', 1],
      ['Mountain', 8],
    ],
  },
  {
    id: 'fdn-arena-hares',
    name: 'Hares',
    colors: ['W'],
    face: 'Skyknight Squire',
    blurb: 'Seven Hare Apparents',
    source: 'arena',
    spells: [
      ['Hare Apparent', 7],
      ['Crusader of Odric', 1],
      ["Syr Alin, the Lion's Claw", 1],
      ['Make a Stand', 1],
      ['Make Your Move', 1],
      ['Dauntless Veteran', 1],
      ['Skyknight Squire', 1],
    ],
    lands: [['Plains', 7]],
  },
  {
    id: 'fdn-arena-elves',
    name: 'Elves',
    colors: ['G'],
    face: 'Dwynen, Gilt-Leaf Daen',
    blurb: 'An elf lord and elves that fight',
    source: 'arena',
    spells: [
      ['Elvish Archdruid', 1],
      ['Dwynen, Gilt-Leaf Daen', 1],
      ['Reclamation Sage', 1],
      ["Dwynen's Elite", 1],
      ['Llanowar Elves', 1],
      ['Beast-Kin Ranger', 1],
      ['Elfsworn Giant', 1],
      ['Druid of the Cowl', 1],
      ['Felling Blow', 1],
      ['Bite Down', 1],
      ['Snakeskin Veil', 1],
      ['Thornweald Archer', 1],
    ],
  },
];

/** Every packet: ours and Arena's. */

/**
 * The official Marvel Super Heroes Jumpstart packets (June 2026), from
 * https://magic.wizards.com/en/news/announcements/marvel-super-heroes-jumpstart-booster-themes,
 * as each becomes playable (docs/marvel-jumpstart.md tracks the rest). 13
 * cards and 7 basics: a Thriving land and the basics are the packet's lands.
 */
export const MARVEL_JUMPSTART_PACKETS: Packet[] = [
  {
    id: 'msh-jumpstart-hydra',
    name: 'HYDRA',
    colors: ['B'],
    face: 'Viper, Cruel Conspirator',
    blurb: 'Villains that strike from the shadows',
    set: 'msh',
    source: 'arena',
    spells: [
      ['Bob, Reluctant HYDRA Agent', 1],
      ['Viper, Cruel Conspirator', 1],
      ['Agents of HYDRA', 1],
      ['HYDRA Troopers', 1],
      ['Baron Strucker, HYDRA Overlord', 1],
      ['Arnim Zola, Bio-Fanatic', 1],
      ['Crossbones, Malicious Mercenary', 1],
      ['HYDRA Disintegrator', 1],
      ['Dark Deed', 1],
      ['Cruel Alliance', 1],
      ['HYDRA Infiltration', 1],
      ['Infernal Rebirth', 1],
    ],
    lands: [
      ['Thriving Moor', 1],
      ['Swamp', 7],
    ],
  },
  {
    id: 'msh-jumpstart-shield',
    name: 'Agents of S.H.I.E.L.D.',
    colors: ['W'],
    face: 'Nick Fury, Spymaster',
    blurb: 'Spies that win when one hero attacks alone',
    set: 'msh',
    source: 'arena',
    spells: [
      ['Agent Phil Coulson', 1],
      ['Peggy Carter, Secret Agent', 1],
      ['Agent 13, Sharon Carter', 1],
      ['Agents of S.H.I.E.L.D.', 1],
      ['Quake, Agent of S.H.I.E.L.D.', 1],
      ['S.H.I.E.L.D. Helicarrier', 1],
      ['Borough Backup', 1],
      ['Nick Fury, Spymaster', 1],
      ['S.H.I.E.L.D. Spy Kit', 1],
      ['Helicarrier Strike', 1],
      ['Strategic Intervention', 1],
      ['Web Up', 1],
    ],
    lands: [
      ['Thriving Heath', 1],
      ['Plains', 7],
    ],
  },
  {
    id: 'msh-jumpstart-trained',
    name: 'Trained',
    colors: ['G'],
    face: 'Shang-Chi, Martial Mentor',
    blurb: 'Heroes that train up with +1/+1 counters',
    set: 'msh',
    source: 'arena',
    spells: [
      ['Serpent Specialist', 1],
      ['White Tiger, Ava Ayala', 1],
      ['Undercover Skrull', 1],
      ['Hercules, Prince of Power', 1],
      ['She-Hulk, Attorney-at-Law', 1],
      ['Pet Avengers', 1],
      ['Shang-Chi, Martial Mentor', 1],
      ['Wakandan Royal Guard', 1],
      ['Advancing the Spirit', 1],
      ['Restorative Technique', 1],
      ['Punishing Punch', 1],
      ['Colossal Collision', 1],
    ],
    lands: [
      ['Thriving Grove', 1],
      ['Forest', 7],
    ],
  },
  {
    id: 'msh-jumpstart-pym',
    name: 'Pym Particles',
    colors: ['U'],
    face: 'Wasp, Shrinking Savior',
    blurb: 'Shrink and grow with Ant-Man, Wasp and their swarms',
    set: 'msh',
    source: 'arena',
    spells: [
      ['Aerial Doombot', 1],
      ['Bold Biochemist', 1],
      ["Ant-Man's Air Force", 1],
      ['Ant-Man, Reformed Rogue', 1],
      ['Wasp, Shrinking Savior', 1],
      ['A.I.M. Scientists', 1],
      ['Giant-Sized Flying Ant', 1],
      ['Pym Particles', 1],
      ['Super Suit', 1],
      ['Quantum Reduction', 1],
      ['Depower', 1],
      ['Robotics Mastery', 1],
    ],
    lands: [
      ['Thriving Isle', 1],
      ['Island', 7],
    ],
  },
  {
    id: 'msh-jumpstart-hire',
    name: 'Heroes for Hire',
    colors: ['R'],
    face: 'Luke Cage, Hero for Hire',
    blurb: 'Heroes paid in Treasure who hit hard',
    set: 'msh',
    source: 'arena',
    spells: [
      ['Stark Industries Executive', 1],
      ["K'un-Lun Warrior", 1],
      ['Misty Knight, Hero for Hire', 1],
      ['Iron Fist, Hero for Hire', 1],
      ['Contract Hero', 1],
      ['Jessica Jones, Private Eye', 1],
      ['Luke Cage, Hero for Hire', 1],
      ['Red Hulk', 1],
      ['Bionic Blow', 1],
      ['Big Score', 1],
      ['Heroes for Hire', 1],
      ['Marvelous Melee', 1],
    ],
    lands: [
      ['Thriving Bluff', 1],
      ['Mountain', 7],
    ],
  },
  {
    id: 'msh-jumpstart-animal',
    name: 'Animal',
    colors: ['G'],
    face: 'Lucky the Pizza Dog',
    blurb: 'Pets and beasts that feast on Food',
    set: 'msh',
    source: 'arena',
    spells: [
      ['Lucky the Pizza Dog', 1],
      ['Guerrilla Gorilla', 1],
      ['Tigra, Feline Fury', 1],
      ['Wakandan Tusker', 1],
      ["Ant-Man's Army", 1],
      ['Tippy-Toe, Terrific Partner', 1],
      ['Pet Avengers', 1],
      ['Savage Land Dinosaur', 1],
      ['Go Nuts!', 1],
      ['Scout the City', 1],
      ['Beast Mode', 1],
      ['Heroic Feast', 1],
    ],
    lands: [
      ['Thriving Grove', 1],
      ['Forest', 7],
    ],
  },
  {
    id: 'msh-jumpstart-great-lakes',
    name: 'Great Lakes Avengers',
    colors: ['G'],
    face: 'The Unbeatable Squirrel Girl',
    blurb: 'Unlikely heroes that punch above their weight',
    set: 'msh',
    source: 'arena',
    spells: [
      ['Guerrilla Gorilla', 1],
      ['Doorman', 1],
      ['Mister Immortal', 1],
      ['Tippy-Toe, Terrific Partner', 1],
      ['Flatman', 1],
      ['The Unbeatable Squirrel Girl', 1],
      ['Big Bertha', 1],
      ['Savage Land Dinosaur', 1],
      ['Rapid Rescue', 1],
      ['Go Nuts!', 1],
      ['Beast Mode', 1],
      ['Training Regimen', 1],
    ],
    lands: [
      ['Thriving Grove', 1],
      ['Forest', 7],
    ],
  },
  {
    id: 'msh-jumpstart-tricksters',
    name: 'Tricksters',
    colors: ['U'],
    face: 'Loki, Lord of Misrule',
    blurb: 'Copies, clones and Loki’s schemes',
    set: 'msh',
    source: 'arena',
    spells: [
      ['Kid Loki', 1],
      ['Living Lies of Loki', 1],
      ["Ant-Man's Air Force", 1],
      ['Impossible Man', 1],
      ['Ghost, Spectral Saboteur', 1],
      ['Loki, Lord of Misrule', 1],
      ['A.I.M. Scientists', 1],
      ['We Say Thee Nay!', 1],
      ['Quantum Reduction', 1],
      ["Trickster's Stratagem", 1],
      ['Multiversal Recruitment', 1],
      ['The Clone Saga', 1],
    ],
    lands: [
      ['Thriving Isle', 1],
      ['Island', 7],
    ],
  },
  {
    id: 'msh-jumpstart-masters',
    name: 'Masters of Evil',
    colors: ['B'],
    face: 'Crimson Cowl, Master of Evil',
    blurb: 'A villain team that rallies behind its leader',
    set: 'msh',
    source: 'arena',
    spells: [
      ['Boomerang, Blade Flinger', 1],
      ['Yellowjacket, Heartless Marauder', 1],
      ['Titania, Rugged Rumbler', 1],
      ['Klaw, Sonic Subjugator', 1],
      ['Crimson Cowl, Master of Evil', 1],
      ['Tiger Shark, Abyssal Hunter', 1],
      ['Radioactive Man', 1],
      ['The Masters of Evil', 1],
      ['Villainous Syndication', 1],
      ['Cruel Alliance', 1],
      ['Visions of Villainy', 1],
      ['Hour of Defeat', 1],
    ],
    lands: [
      ['Thriving Moor', 1],
      ['Swamp', 7],
    ],
  },
  {
    id: 'msh-jumpstart-thor',
    name: 'Thor',
    colors: ['R'],
    face: "Thor, Asgard's Avenger",
    blurb: 'Asgardians and lightning that strike from on high',
    set: 'msh',
    source: 'arena',
    spells: [
      ["K'un-Lun Warrior", 1],
      ['Loki Laufeyson', 1],
      ["Sif's Spearmaster", 1],
      ['Molten Lavamancer', 1],
      ['Crimson Operative', 1],
      ["Thor, Asgard's Avenger", 1],
      ['Kree Sentinel', 1],
      ['Asgardian Inspiration', 1],
      ['Lightning Bolt', 1],
      ['Lightning Strike', 1],
      ['Origin of Thor', 1],
      ["Mjölnir's Might", 1],
    ],
    lands: [
      ['Thriving Bluff', 1],
      ['Mountain', 7],
    ],
  },
  {
    id: 'msh-jumpstart-lethal',
    name: 'Lethal',
    colors: ['B'],
    face: 'Black Widow, Deadly Hunter',
    blurb: 'Deathtouch assassins and the Red Room',
    set: 'msh',
    source: 'arena',
    spells: [
      ['Red Room Recruit', 1],
      ['White Widow, Yelena Belova', 1],
      ['Ninja of the Hand', 1],
      ['Venomized Cat', 1],
      ['Black Widow, Deadly Hunter', 1],
      ['Titanium Man', 1],
      ['Venom, Evil Unleashed', 1],
      ['Stolen Stark Tech', 1],
      ["Widow's Bite", 1],
      ['Hour of Defeat', 1],
      ['Origin of Black Widow', 1],
      ['Infernal Rebirth', 1],
    ],
    lands: [
      ['Thriving Moor', 1],
      ['Swamp', 7],
    ],
  },
  {
    id: 'msh-jumpstart-soaring',
    name: 'Soaring',
    colors: ['U'],
    face: 'Falcon, Winged Wonder',
    blurb: 'Flyers that rule the skies',
    set: 'msh',
    source: 'arena',
    spells: [
      ['Aerial Doombot', 1],
      ['Rescue, Pepper Potts', 1],
      ['Flying Drone', 1],
      ['Namora, the Sea Queen', 1],
      ['S.H.I.E.L.D. Deployment Drone', 1],
      ['Justice, Vance Astrovik', 1],
      ['Vulture, Feathered Fiend', 1],
      ['Falcon, Winged Wonder', 1],
      ['Whoosh!', 1],
      ["Falcon's Wing Harness", 1],
      ['I Am Iron Man', 1],
      ['Dismissive Denial', 1],
    ],
    lands: [
      ['Thriving Isle', 1],
      ['Island', 7],
    ],
  },
  {
    id: 'msh-jumpstart-incredible',
    name: 'Incredible',
    colors: ['G'],
    face: 'Hulk, Strongest There Is',
    blurb: 'Gamma-powered heroes that keep getting bigger',
    set: 'msh',
    source: 'arena',
    spells: [
      ['Brawn, Amadeus Cho', 1],
      ['Guerrilla Gorilla', 1],
      ['She-Hulk, Attorney-at-Law', 1],
      ['Hulk, Strongest There Is', 1],
      ['Abomination, Terrifying Titan', 1],
      ['Doc Samson, Super Psychiatrist', 1],
      ['Savage Land Dinosaur', 1],
      ['Giant Growth', 1],
      ["Hulk's Thunderclap", 1],
      ['Origin of the Hulk', 1],
      ['Go Nuts!', 1],
      ['Super Strength', 1],
    ],
    lands: [
      ['Thriving Grove', 1],
      ['Forest', 7],
    ],
  },
  {
    id: 'msh-jumpstart-scarlet',
    name: 'Scarlet',
    colors: ['R'],
    face: 'The Vision and Scarlet Witch',
    blurb: 'Chaos magic and a flurry of spells',
    set: 'msh',
    source: 'arena',
    spells: [
      ['Stark Industries Executive', 1],
      ['Loki Laufeyson', 1],
      ['Speed, Young Avenger', 1],
      ['Molten Lavamancer', 1],
      ['Wiccan, Young Avenger', 1],
      ['The Vision and Scarlet Witch', 1],
      ['Kree Sentinel', 1],
      ['Lightning Bolt', 1],
      ['Vision of Love', 1],
      ['Grapeshot', 1],
      ['Hex Magic', 1],
      ["Wanda's Vision", 1],
    ],
    lands: [
      ['Thriving Bluff', 1],
      ['Mountain', 7],
    ],
  },
  {
    id: 'msh-jumpstart-wild',
    name: 'Wild',
    colors: ['G'],
    face: 'Ka-Zar of the Savage Land',
    blurb: 'Jungle heroes that grow with every land',
    set: 'msh',
    source: 'arena',
    spells: [
      ['Hellcat, Undying Vigilante', 1],
      ['White Tiger, Amulet Keeper', 1],
      ['The Fabulous Frog-Man', 1],
      ['Gert and Old Lace, Runaways', 1],
      ['Mole Man, Moloid Master', 1],
      ['Hit-Monkey', 1],
      ['Ka-Zar of the Savage Land', 1],
      ['Claim the Kingdom', 1],
      ['Accelerated Evolution', 1],
      ['Restorative Technique', 1],
      ['Colossal Collision', 1],
    ],
    lands: [
      ['Terramorphic Expanse', 1],
      ['Thriving Grove', 1],
      ['Forest', 7],
    ],
  },
  {
    id: 'msh-jumpstart-tenacious',
    name: 'Tenacious',
    colors: ['G'],
    face: 'Voracious Brood',
    blurb: 'Heroes that keep coming back for more',
    set: 'msh',
    source: 'arena',
    spells: [
      ['Undercover Skrull', 1],
      ['White Tiger, Amulet Keeper', 1],
      ['Hellcat, Undying Vigilante', 1],
      ['Gert and Old Lace, Runaways', 1],
      ['Voracious Brood', 1],
      ['Pet Avengers', 1],
      ['Savage Land Dinosaur', 1],
      ['Return of the Mole Man', 1],
      ['Scout the City', 1],
      ['Call Damage Control', 1],
      ['Accelerated Evolution', 1],
      ['Punishing Punch', 1],
    ],
    lands: [
      ['Thriving Grove', 1],
      ['Terramorphic Expanse', 1],
      ['Forest', 6],
    ],
  },
  {
    id: 'msh-jumpstart-rampaging',
    name: 'Rampaging',
    colors: ['G'],
    face: 'Rhino, Terrible Trampler',
    blurb: 'Huge villains that trample everything',
    set: 'msh',
    source: 'arena',
    spells: [
      ['Serpent Specialist', 1],
      ['Knight of Wundagore', 1],
      ['Bushmaster, Coiled Henchman', 1],
      ['Titania, Rugged Rumbler', 1],
      ['Powerful Broker', 1],
      ['Mister Hyde, Monster Within', 1],
      ['Atlas, Sizable Stooge', 1],
      ['Rhino, Terrible Trampler', 1],
      ["Rhino's Rampage", 1],
      ['Beast Mode', 1],
      ['Colossal Collision', 1],
      ['Claim the Kingdom', 1],
    ],
    lands: [
      ['Thriving Grove', 1],
      ['Forest', 7],
    ],
  },
  {
    id: 'msh-jumpstart-wakanda',
    name: 'Wakanda',
    colors: ['W'],
    face: 'Black Panther, Most Dangerous',
    blurb: 'Wakanda’s guard and its Vibranium tech',
    set: 'msh',
    source: 'arena',
    spells: [
      ['Wakandan Shield Guard', 1],
      ['Wakandan Tusker', 1],
      ['Black Panther, Most Dangerous', 1],
      ['Shuri, Vibranium Technologist', 1],
      ['Okoye, Dora Milaje Leader', 1],
      ['Wakandan Drone Flock', 1],
      ['Borough Backup', 1],
      ['Vibranium Energy Daggers', 1],
      ['Ultimate Alliance', 1],
      ['Panther Pounce', 1],
      ['Heroic Teamwork', 1],
      ['Secure Detention', 1],
    ],
    lands: [
      ['Thriving Heath', 1],
      ['Plains', 7],
    ],
  },
  {
    id: 'msh-jumpstart-atlantis',
    name: 'Atlantis',
    colors: ['U'],
    face: 'Namor, Scourge of the Seas',
    blurb: 'Merfolk that rise from the sea',
    set: 'msh',
    source: 'arena',
    spells: [
      ['Mist-Cloaked Herald', 1],
      ['Daughter of the Deep', 1],
      ['Atlantean Skirmisher', 1],
      ['Atlantean Cavalry', 1],
      ['Namora, the Sea Queen', 1],
      ['Attuma, Atlantean Warlord', 1],
      ['Shipwreck Patrol', 1],
      ['Namor, Scourge of the Seas', 1],
      ['Quantum Reduction', 1],
      ['Unstable Experiment', 1],
      ['Frozen in Ice', 1],
      ['Atlantis Attacks', 1],
    ],
    lands: [
      ['Thriving Isle', 1],
      ['Island', 7],
    ],
  },
  {
    id: 'msh-jumpstart-geniuses',
    name: 'Geniuses',
    colors: ['U'],
    face: 'Reed Richards, Smartest Man',
    blurb: 'The smartest minds, drawing ahead',
    set: 'msh',
    source: 'arena',
    spells: [
      ['Kid Loki', 1],
      ['Bold Biochemist', 1],
      ['Brawn, Amadeus Cho', 1],
      ['Shuri, Vibranium Technologist', 1],
      ['Ant-Man, Reformed Rogue', 1],
      ['Beast, Erudite Aerialist', 1],
      ['Blue Marvel, Adam Brashear', 1],
      ['Reed Richards, Smartest Man', 1],
      ['Super Intelligence', 1],
      ['Futurist Forge', 1],
      ['Frozen in Ice', 1],
      ['Fantastic Bounce', 1],
    ],
    lands: [
      ['Thriving Isle', 1],
      ['Island', 7],
    ],
  },
  {
    id: 'msh-jumpstart-marvelous',
    name: 'Marvelous',
    colors: ['W'],
    face: 'Captain Marvel, Shooting Star',
    blurb: 'Cosmic heroes who power up and strike',
    set: 'msh',
    source: 'arena',
    spells: [
      ['Wakandan Shield Guard', 1],
      ['Raft Security Officer', 1],
      ['Marvel Boy, Noh-Varr', 1],
      ['Hero in Training', 1],
      ['Ms. Marvel, Elastic Ally', 1],
      ['Photon, Lady of Light', 1],
      ['Captain Mar-Vell, Space-Born', 1],
      ['Captain Marvel, Shooting Star', 1],
      ['Helicarrier Strike', 1],
      ['Quantum Entanglement', 1],
      ['Super Villain Lockup', 1],
      ['Fall to Earth', 1],
    ],
    lands: [
      ['Thriving Heath', 1],
      ['Plains', 7],
    ],
  },
  {
    id: 'msh-jumpstart-young-avengers',
    name: 'Young Avengers',
    colors: ['R'],
    face: 'Hulkling, Young Avenger',
    blurb: 'The next generation of Avengers, spells and all',
    set: 'msh',
    source: 'arena',
    spells: [
      ['Stature, Young Avenger', 1],
      ['Speed, Young Avenger', 1],
      ['Patriot, Young Avenger', 1],
      ['Iron Lad, Young Avenger', 1],
      ['Wiccan, Young Avenger', 1],
      ['Hawkeye, Young Avenger', 1],
      ['Hulkling, Young Avenger', 1],
      ["Hawkeye's Bow", 1],
      ['Team Tactics', 1],
      ['Lightning Strike', 1],
      ['Crossover Collaboration', 1],
      ['Marvelous Melee', 1],
    ],
    lands: [
      ['Thriving Bluff', 1],
      ['Mountain', 7],
    ],
  },
  {
    id: 'msh-jumpstart-towering',
    name: 'Towering',
    colors: ['G'],
    face: 'Giant-Man, Gargantuan Genius',
    blurb: 'Giants that grow huge and reward big creatures',
    set: 'msh',
    source: 'arena',
    spells: [
      ['Reptil, Dinomorpher', 1],
      ['Stature, Young Avenger', 1],
      ['Goliath, Mass Manipulator', 1],
      ['Ms. Marvel, Elastic Ally', 1],
      ['Ant-Man, Reformed Rogue', 1],
      ['Atlas, Sizable Stooge', 1],
      ['Giant-Man, Gargantuan Genius', 1],
      ['Spider-Rex, Daring Dino', 1],
      ['Giant Growth', 1],
      ['Rapid Rescue', 1],
      ['Terrific Team-Up', 1],
      ['Colossal Collision', 1],
    ],
    lands: [
      ['Thriving Grove', 1],
      ['Forest', 7],
    ],
  },
  {
    id: 'msh-jumpstart-precise',
    name: 'Precise',
    colors: ['W'],
    face: 'Hawkeye, Bowslinger',
    blurb: 'Sharpshooters who never miss',
    set: 'msh',
    source: 'arena',
    spells: [
      ['Colleen Wing, Street Samurai', 1],
      ['Agent of Atlas', 1],
      ['Raft Security Officer', 1],
      ['Kree Commandos', 1],
      ['Hawkeye, Bowslinger', 1],
      ['Mockingbird, Ace Agent', 1],
      ['Valkyrior Skyrider', 1],
      ['Panther Pounce', 1],
      ['Stunning Shot', 1],
      ['Sudden Strike', 1],
      ['Heroic Teamwork', 1],
      ['Fall to Earth', 1],
    ],
    lands: [
      ['Thriving Heath', 1],
      ['Plains', 7],
    ],
  },
  {
    id: 'msh-jumpstart-kang',
    name: 'Kang Dynasty',
    colors: ['U'],
    face: 'Immortus, Master of Eternity',
    blurb: 'Time travellers who bend turns and spells',
    set: 'msh',
    source: 'arena',
    spells: [
      ['Bold Biochemist', 1],
      ['TVA Bureaucrat', 1],
      ['S.H.I.E.L.D. Deployment Drone', 1],
      ['Iron Lad, Young Avenger', 1],
      ['Immortus, Master of Eternity', 1],
      ['Victor Timely, Wily Tycoon', 1],
      ['Pharaoh Rama-Tut', 1],
      ['Think Twice', 1],
      ['Depower', 1],
      ['Timeline Inquiry', 1],
      ['Multiversal Recruitment', 1],
      ['Time Warp', 1],
    ],
    lands: [
      ['Thriving Isle', 1],
      ['Island', 7],
    ],
  },
  {
    id: 'msh-jumpstart-equipped',
    name: 'Equipped',
    colors: ['W'],
    face: 'Captain America, Liberator',
    blurb: 'Heroes who gear up with Equipment',
    set: 'msh',
    source: 'arena',
    spells: [
      ['Bucky Barnes, Eager Ally', 1],
      ['Peggy Carter, Secret Agent', 1],
      ['The Howling Commandos', 1],
      ['Agent 13, Sharon Carter', 1],
      ['Patriot, Young Avenger', 1],
      ['U.S.Agent, John Walker', 1],
      ['Captain America, Liberator', 1],
      ["Captain America's Shield", 1],
      ['Take Up the Shield', 1],
      ['Infinity Formula', 1],
      ['Origin of Captain America', 1],
      ['Secure Detention', 1],
    ],
    lands: [
      ['Thriving Heath', 1],
      ['Plains', 7],
    ],
  },
  {
    id: 'msh-jumpstart-squadron',
    name: 'Squadron',
    colors: ['W'],
    face: 'Hyperion, Supreme Hero',
    blurb: 'A super-team that fights as one',
    set: 'msh',
    source: 'arena',
    spells: [
      ['Agent of Atlas', 1],
      ['Brave Brawler', 1],
      ['Nighthawk, Dark Defender', 1],
      ['Hero in Training', 1],
      ['Zarda, the Power Princess', 1],
      ['Doctor Spectrum', 1],
      ['Borough Backup', 1],
      ['Hyperion, Supreme Hero', 1],
      ["Hyperion's Atomic Vision", 1],
      ['Heroic Teamwork', 1],
      ['Web Up', 1],
      ['Blur of Heroism', 1],
    ],
    lands: [
      ['Thriving Heath', 1],
      ['Plains', 7],
    ],
  },
  {
    id: 'msh-jumpstart-conniving',
    name: 'Conniving',
    colors: ['U'],
    face: 'Doc Ock, Sinister Scientist',
    blurb: 'Villains who connive and scheme',
    set: 'msh',
    source: 'arena',
    spells: [
      ['Kid Loki', 1],
      ['Mob Lookout', 1],
      ['Flying Octobot', 1],
      ['Graviton, Fundamental Force', 1],
      ["Doc Ock's Henchmen", 1],
      ['Tiger Shark, Abyssal Hunter', 1],
      ['Leader, Super-Genius', 1],
      ['Doc Ock, Sinister Scientist', 1],
      ['Unstable Experiment', 1],
      ["Mysterio's Mirage", 1],
      ["Trickster's Stratagem", 1],
      ['Dismissive Denial', 1],
    ],
    lands: [
      ['Thriving Isle', 1],
      ['Villainous Hideout', 1],
      ['Island', 6],
    ],
  },
  {
    id: 'msh-jumpstart-battalion',
    name: 'Battalion',
    colors: ['W'],
    face: 'Captain America, Skybound',
    blurb: 'Heroes who attack together, three or more at a time',
    set: 'msh',
    source: 'arena',
    spells: [
      ['General Thunderbolt Ross', 1],
      ['The Howling Commandos', 1],
      ['Wakandan Shield Guard', 1],
      ['Wild Pack Squad', 1],
      ['Falcon, Joaquin Torres', 1],
      ['War Machine, James Rhodes', 1],
      ['U.S.Agent, John Walker', 1],
      ['Captain America, Skybound', 1],
      ['Ultimate Alliance', 1],
      ['Helicarrier Strike', 1],
      ['Heroic Teamwork', 1],
      ['Fall to Earth', 1],
    ],
    lands: [
      ['Thriving Heath', 1],
      ['Plains', 7],
    ],
  },
  {
    id: 'msh-jumpstart-analyzed',
    name: 'Analyzed',
    colors: ['U'],
    face: 'Vision, Spectral Synthezoid',
    blurb: 'Synthezoids and robots that copy and recast',
    set: 'msh',
    source: 'arena',
    spells: [
      ['Virtual Assistant', 1],
      ['TVA Bureaucrat', 1],
      ['Viv Vision, Teen Synthezoid', 1],
      ['Echo, Perceptive Prodigy', 1],
      ['Machine Man, Model X-51', 1],
      ['Victor Mancha, Runaway', 1],
      ['Vision, Spectral Synthezoid', 1],
      ['We Say Thee Nay!', 1],
      ['Quantum Reduction', 1],
      ['Frozen in Ice', 1],
      ['Timeline Inquiry', 1],
      ['Atlantis Attacks', 1],
    ],
    lands: [
      ['Thriving Isle', 1],
      ['Island', 7],
    ],
  },
  {
    id: 'msh-jumpstart-blink',
    name: 'Blink',
    colors: ['U'],
    face: 'Silver Surfer, Cosmic Voyager',
    blurb: 'Flicker your permanents out and back',
    set: 'msh',
    source: 'arena',
    spells: [
      ["Shi'ar Soldier", 1],
      ['Mob Lookout', 1],
      ['Imperial Cosmographer', 1],
      ['S.H.I.E.L.D. Deployment Drone', 1],
      ['Justice, Vance Astrovik', 1],
      ['Victor Timely, Wily Tycoon', 1],
      ['Shipwreck Patrol', 1],
      ['Silver Surfer, Cosmic Voyager', 1],
      ['Spaceshift', 1],
      ['We Say Thee Nay!', 1],
      ["Collector's Case", 1],
      ['Dismissive Denial', 1],
    ],
    lands: [
      ['Thriving Isle', 1],
      ['Island', 7],
    ],
  },
];

export const PACKETS: Packet[] = [
  ...OWN_PACKETS,
  ...ARENA_BLB_PACKETS,
  ...ARENA_FDN_PACKETS,
  ...MARVEL_JUMPSTART_PACKETS,
];

const BASICS: Record<Color, string> = {
  W: 'Plains',
  U: 'Island',
  B: 'Swamp',
  R: 'Mountain',
  G: 'Forest',
};

/** A packet's full 20 cards: its spells and its basic lands. */
export function packetCards(p: Packet): [string, number][] {
  return [...p.spells, ...(p.lands ?? [[BASICS[p.colors[0]!], PACKET_LANDS]])];
}
