import { BLOOMBURROW_BEHAVIORS } from './bloomburrow.ts';
import { FOUNDATIONS_DRAFT_BEHAVIORS } from './foundations-draft.ts';
import { FOUNDATIONS_JUMP_IN_BEHAVIORS } from './foundations-jumpin.ts';
import { MARVEL_BEHAVIORS } from './marvel.ts';
import { MARVEL_BRAWL_BEHAVIORS } from './marvel-brawl.ts';
import { FINAL_FANTASY_BEHAVIORS } from './final-fantasy.ts';
import { STRIXHAVEN_BEHAVIORS } from './strixhaven.ts';
import { SECRETS_OF_STRIXHAVEN_BEHAVIORS } from './secrets-of-strixhaven.ts';
import { STRIXHAVEN_BRAWL_BEHAVIORS } from './strixhaven-brawl.ts';
import { FINAL_FANTASY_BRAWL_BEHAVIORS } from './final-fantasy-brawl.ts';
import { REALITY_FRACTURE_BEHAVIORS } from './reality-fracture.ts';

/**
 * Allowed sets, most preferred first: Foundations, then older core sets, then
 * Bloomburrow (late, so cards reprinted there keep their core-set printing).
 */
export const SET_PREFERENCE = [
  'fdn',
  'm21',
  'm20',
  'm19',
  'ori',
  'm15',
  'm14',
  'm13',
  'm12',
  'm11',
  'm10',
  '10e',
  '9ed',
  '8ed',
  '7ed',
  '6ed',
  '5ed',
  '4ed',
  'blb',
  'msh',
  // Marvel Super Heroes Commander: the Brawl precons (a few of their cards are only in msh or promos).
  'msc',
  'fin',
  // Final Fantasy Commander: the Brawl precons (phase 12).
  'fic',
  // Strixhaven: School of Mages and Secrets of Strixhaven (phases 13 and 14).
  'stx',
  'sos',
  // Secrets of Strixhaven Commander: the Brawl decks (phase 15).
  'soc',
  // Final Fantasy's Through the Ages reprints (draft trophy decks: Captain Lannery Storm, Vial Smasher).
  'fca',
  // Outlaws of Thunder Junction: Sterling Hound, in Arena's Bloomburrow Threshold packet.
  'otj',
  'pmei',
  'pw26',
  'sld',
  // Arena Beginner Set: Arena-only cards (last resort).
  'anb',
  // Final Fantasy Commander (phase 12): the Arena Store Brawl decks swap in cards from other sets
  // (last, so no earlier card changes printing). Arena-only Alchemy cards come from ymid and ywoe.
  'znr',
  'khm',
  'mid',
  'vow',
  'afr',
  'mkm',
  'dsk',
  'dft',
  'mom',
  'otj',
  'ktk',
  'som',
  'big',
  'j25',
  'ymid',
  'ywoe',
  // Strixhaven Brawl (15a): sets for the Brawl decks' reprints.
  'mh3',
  'hbg',
  'tdm',
  'rtr',
  'ybro',
  'soa',
  'mh1',
  'mh2',
  'akh',
  'mat',
  'bro',
  'dom',
  'c20',
  'rav',
  'grn',
  // Strixhaven Brawl (15b): sets for the other seven Brawl decks' reprints.
  'woe',
  'gtc',
  'war',
  'dmu',
  'aer',
  'thb',
  'bng',
  'ths',
  'neo',
  'eld',
  'isd',
  'one',
  'bfz',
  'lci',
  'ecl',
  'ydft',
  'yecl',
  'mbc',
  'ytdm',
  'eoe',
  'soi',
  'rna',
  'yneo',
  'nph',
  'j21',
  'ydsk',
  'xln',
  'roe',
  'c15',
  'iko',
  'kld',
  'snc',
  'jou',
  'ogw',
  'csp',
  'ydmu',
  // Strixhaven Brawl (15b, multi): Siege Rhino (conjured by Call the Crash), Ochre Jelly.
  // Mystical Archive (16): the Strixhaven Mystical Archive (a last resort: STA cards have older printings).
  'sta',
  // Reality Fracture (17a): last, so no earlier card changes printing.
  'fra',
];

export const RED_POOL = [
  'Volley Veteran',
  "Brass's Bounty",
  "Dragonlord's Servant",
  'Dragonmaster Outcast',
  'Goblin Oriflamme',
  'Goblin Smuggler',
  'Kargan Dragonrider',
  'Battle-Rattle Shaman',
  'Crackling Cyclops',
  'Impact Tremors',
  'Lathliss, Dragon Queen',
  'Rapacious Dragon',
  'Rite of the Dragoncaller',
  'Slagstorm',
  'Sower of Chaos',
  'Terror of Mount Velus',
  'Mountain',
  'Shock',
  'Lightning Strike',
  'Boltwave',
  'Kindled Fury',
  'Sure Strike',
  'Crash Through',
  'Dragon Fodder',
  'Seismic Rupture',
  'Fanatical Firebrand',
  'Viashino Pyromancer',
  'Heartfire Immolator',
  'Swab Goblin',
  'Firebrand Archer',
  'Searslicer Goblin',
  'Raging Redcap',
  'Brazen Scourge',
  'Guttersnipe',
  'Giant Cindermaw',
  'Spitfire Lagac',
  'Battlesong Berserker',
  'Skyraker Giant',
  'Ravenous Giant',
  'Ball Lightning',
  'Gorehorn Raider',
  'Fire Elemental',
  'Dragon Trainer',
  'Shivan Dragon',
  // Path of Power / Might of the Legion
  'Axgard Cavalry',
  'Frenzied Goblin',
  'Krenko, Mob Boss',
  'Burst Lightning',
  'Goblin Surprise',
  'Courageous Goblin',
  'Bulk Up',
  'Scorching Dragonfire',
  // Reckless Raid
  'Goblin Boarders',
  'Slumbering Cerberus',
  'Strongbox Raider',
  'Abrade',
  // Wondrous Wizardry
  'Ghitu Lavarunner',
  'Fiery Annihilation',
  // Color Challenge: Goblins Everywhere!
  'Tin Street Cadet',
  'Goblin Tunneler',
  'Nest Robber',
  'Molten Ravager',
  'Goblin Gang Leader',
  'Goblin Trashmaster',
  'Ogre Battledriver',
  'Immortal Phoenix',
  'Volcanic Dragon',
  'Siege Dragon',
  'Raid Bombardment',
  'Storm Strike',
  'Burn Bright',
  'Inescapable Blaze',
  'Goblin Gathering',
] as const;

export const GREEN_POOL = [
  'Sylvan Scavenging',
  'Dwynen, Gilt-Leaf Daen',
  'Ghalta, Primal Hunger',
  'Gnarlid Colony',
  'Inspiring Call',
  'Ambush Wolf',
  'Blanchwood Armor',
  'Elvish Regrower',
  'Fierce Empath',
  'Preposterous Proportions',
  'Reclamation Sage',
  'Thrashing Brontodon',
  'Forest',
  'Giant Growth',
  'Snakeskin Veil',
  'Bite Down',
  'Broken Wings',
  'Felling Blow',
  'Overrun',
  'Bear Cub',
  'Thornweald Archer',
  'Druid of the Cowl',
  "Dwynen's Elite",
  'Imperious Perfect',
  'Beast-Kin Ranger',
  'Magnigoth Sentry',
  'Treetop Snarespinner',
  'Gnarlback Rhino',
  'Wildheart Invoker',
  'Tajuru Pathwarden',
  'Elfsworn Giant',
  "Heroes' Bane",
  'Rampaging Baloths',
  'Affectionate Indrik',
  'Quakestrider Ceratops',
  'Pelakka Wurm',
  'Aggressive Mammoth',
  'Gigantosaurus',
  // Path of Power
  'Eager Trufflesnout',
  'Llanowar Elves',
  'Mild-Mannered Librarian',
  'Nessian Hornbeetle',
  'Spinner of Souls',
  'Vizier of the Menagerie',
  'Bushwhack',
  "Garruk's Uprising",
  // Cat Attack
  'Wary Thespian',
  // Morbid Machinations
  'Cackling Prowler',
  'Needletooth Pack',
  'Quilled Greatwurm',
  'Scavenging Ooze',
  // Learn From the Land
  'Apothecary Stomper',
  'Loot, Exuberant Explorer',
  'Mossborn Hydra',
  'Circuitous Route',
  'Primeval Bounty',
  // Color Challenge: Large and in Charge
  'Jungle Delver',
  'Ilysian Caryatid',
  'Woodland Mystic',
  'Wildwood Patrol',
  'Baloth Packhunter',
  'Prized Unicorn',
  'Rumbling Baloth',
  'World Shaper',
  'Sentinel Spider',
  'Rampaging Brontodon',
  'Colossal Majesty',
  'Epic Proportions',
  'Stony Strength',
  'Rabid Bite',
] as const;

export const WHITE_POOL = [
  'Armasaur Guide',
  'Felidar Retreat',
  'Linden, the Steadfast Queen',
  'Make Your Move',
  'Make a Stand',
  'Ancestor Dragon',
  'Archway Angel',
  'Ballyrush Banneret',
  'Hare Apparent',
  'Inspiring Paladin',
  'Jazal Goldmane',
  'Prayer of Binding',
  'Adamant Will',
  'Angel of Finality',
  'Angelic Edict',
  "Bishop's Soldier",
  'Cathar Commando',
  'Day of Judgment',
  'Deadly Riposte',
  'Disenchant',
  'Felidar Cub',
  'Guarded Heir',
  'Herald of Faith',
  'Joust Through',
  'Leonin Skyhunter',
  'Mentor of the Meek',
  'Mischievous Pup',
  'Prideful Parent',
  "Syr Alin, the Lion's Claw",
  'Twinblade Blessing',
  'Zetalpa, Primal Dawn',
  'Crusader of Odric',
  'Dauntless Veteran',
  'Dawnwing Marshal',
  'Resolute Reinforcements',
  'Serra Angel',
  'Valorous Stance',
  'Release the Dogs',
  'Celestial Armor',
  // Cat Attack / Vampiric Hunger
  'Arahbo, the First Fang',
  'Felidar Savior',
  'Helpful Hunter',
  'Leonin Vanguard',
  'Regal Caracal',
  'Savannah Lions',
  'Claws Out',
  'Angelic Destiny',
  'Banishing Light',
  "Ajani's Pridemate",
  'Cat Collector',
  'Dazzling Angel',
  "Healer's Hawk",
  'Hinterland Sanctifier',
  'Inspiring Overseer',
  'Sun-Blessed Healer',
  'Twinblade Paladin',
  'Moment of Triumph',
  // Arcane Aerialists
  'Giada, Font of Hope',
  'Lyra Dawnbringer',
  'Vanguard Seraph',
  'Youthful Valkyrie',
  'Stasis Snare',
  // Color Challenge: Keep the Peace
  'Charmed Stray',
  'Fencing Ace',
  'Hallowed Priest',
  'Impassioned Orator',
  'Moorland Inquisitor',
  'Angel of Vitality',
  'Leonin Warleader',
  'Spiritual Guardian',
  'Angelic Guardian',
  'Inspiring Commander',
  'Goring Ceratops',
  'Pacifism',
  'Angelic Reward',
  'Tactical Advantage',
  'Confront the Assault',
  'Bond of Discipline',
] as const;

export const BLUE_POOL = [
  'Mystical Teachings',
  'Voracious Greatshark',
  "An Offer You Can't Refuse",
  'Cephalid Inkmage',
  'Corsair Captain',
  'Flashfreeze',
  'Kitesail Corsair',
  "River's Rebuke",
  'Sphinx of the Final Word',
  'Starlight Snare',
  'Tempest Djinn',
  'Aetherize',
  'Burrog Befuddler',
  'Cancel',
  'Clinquant Skymage',
  'Elementalist Adept',
  'Erudite Wizard',
  'Fleeting Distraction',
  'Icewind Elemental',
  'Into the Roil',
  'Lightshell Duo',
  'Micromancer',
  'Mocking Sprite',
  'Mystic Archaeologist',
  'Negate',
  'Refute',
  'Rune-Sealed Wall',
  'Shipwreck Dowser',
  'Skyship Buccaneer',
  'Storm Fleet Spy',
  'Strix Lookout',
  'Think Twice',
  'Unsummon',
  // Learn From the Land / Arcane Aerialists
  'Aegis Turtle',
  'Fog Bank',
  'High Fae Trickster',
  'Spectral Sailor',
  'Faebloom Trick',
  'Chart a Course',
  'Bigfin Bouncer',
  'Exclusion Mage',
  'Mischievous Mystic',
  'Quick Study',
  'Curator of Destinies',
  // Wondrous Wizardry / Graveyard Gifts
  'Arcanis the Omnipotent',
  'Brineborn Cutthroat',
  'Kiora, the Rising Tide',
  'Essence Scatter',
  'Opt',
  'Inspiration from Beyond',
  'Archmage of Runes',
  'Drake Hatcher',
  'Tolarian Terror',
  'Arcane Epiphany',
  'Dive Down',
] as const;

export const BLACK_POOL = [
  'Maalfeld Twins',
  'Macabre Waltz',
  'Offer Immortality',
  'Death Baron',
  'Deathmark',
  'Driver of the Dead',
  'Revenge of the Rats',
  "Seeker's Folly",
  'Burglar Rat',
  'Crypt Feaster',
  'Highborn Vampire',
  'Hungry Ghoul',
  'Marauding Blight-Priest',
  'Nullpriest of Oblivion',
  'Pulse Tracker',
  'Rune-Scarred Demon',
  'Skeleton Archer',
  'Untamed Hunger',
  'Vampire Interloper',
  'Vampire Neonate',
  'Vampire Soulcaller',
  'Vampire Spawn',
  'Vile Entomber',
  'Sanguine Syphoner',
  'Vampire Nighthawk',
  'Vengeful Bloodwitch',
  'Moment of Craving',
  'Tribute to Hunger',
  'Phyrexian Arena',
  // Reckless Raid / Morbid Machinations
  'Infernal Vessel',
  'Infestation Sage',
  'Midnight Reaper',
  'Reassembling Skeleton',
  'Tragic Banshee',
  'Vampire Gourmand',
  'Undying Malice',
  'Eaten Alive',
  'Vampiric Rites',
  'Diregraf Ghoul',
  'High-Society Hunter',
  'Massacre Wurm',
  'Fake Your Own Death',
  "Hero's Downfall",
  // Graveyard Gifts
  'Abyssal Harvester',
  'Arbiter of Woe',
  'Billowing Shriekmass',
  'Crow of Dark Tidings',
  'Bake into a Pie',
  'Stab',
  'Rise of the Dark Realms',
  'Zombify',
] as const;

/** Bloomburrow cards: every card with Bloomburrow behaviour (vanilla ones have an empty entry). */
export const BLOOMBURROW_POOL = Object.keys(BLOOMBURROW_BEHAVIORS);
/** The Marvel Brawl precons' cards (not already in the pool above). */
export const MARVEL_BRAWL_POOL = Object.keys(MARVEL_BRAWL_BEHAVIORS);

/** Multicoloured and colourless cards. */
export const OTHER_POOL = [
  "Pirate's Cutlass",
  'Scrawling Crawler',
  'Soul-Guide Lantern',
  'Adventuring Gear',
  'Basilisk Collar',
  'Drogskol Reaver',
  'Expedition Map',
  'Fireshrieker',
  'Goblin Firebomb',
  'Meteor Golem',
  'Solemn Simulacrum',
  'Swiftblade Vindicator',
  'Swiftfoot Boots',
  'Aurelia, the Warleader',
  'Heroic Reinforcements',
  'Ashroot Animist',
  'Halana and Alena, Partners',
  'Ruby, Daring Tracker',
  'Goldvein Pick',
  // Cat Attack / Vampiric Hunger
  'Good-Fortune Unicorn',
  'Anthem of Champions',
  'Unflinching Courage',
  'Elenda, Saint of Dusk',
  'Fiendish Panda',
  'Mortify',
  // Reckless Raid / Morbid Machinations
  'Wardens of the Cycle',
  'Alesha, Who Laughs at Fate',
  'Perforating Artist',
  // Learn From the Land / Arcane Aerialists
  'Cloudblazer',
  'Empyrean Eagle',
  'Tatyova, Benthic Druid',
  // Wondrous Wizardry / Graveyard Gifts
  'Dreadwing Scavenger',
  'Balmor, Battlemage Captain',
  'Enigma Drake',
  'Niv-Mizzet, Visionary',
  'Ovika, Enigma Goliath',
  'Gleaming Barrier',
] as const;

/** Basics and the two-colour lands used by the Arena starter decks. */
export const LAND_POOL = [
  'Evolving Wilds',
  "Rogue's Passage",
  'Cryptic Caves',
  'Plains',
  'Island',
  'Swamp',
  ...[
    'Azorius',
    'Dimir',
    'Rakdos',
    'Gruul',
    'Selesnya',
    'Orzhov',
    'Izzet',
    'Golgari',
    'Boros',
    'Simic',
  ].map((guild) => `${guild} Guildgate`),
  'Tranquil Cove',
  'Dismal Backwater',
  'Bloodfell Caves',
  'Rugged Highlands',
  'Blossoming Sands',
  'Scoured Barrens',
  'Swiftwater Cliffs',
  'Jungle Hollow',
  'Wind-Scarred Crag',
  'Thornwood Falls',
  'Temple of Enlightenment',
  'Temple of Deceit',
  'Temple of Malice',
  'Temple of Abandon',
  'Temple of Plenty',
  'Temple of Silence',
  'Temple of Epiphany',
  'Temple of Malady',
  'Temple of Triumph',
  'Temple of Mystery',
];

/** Foundations cards from Arena's Foundations Jump In packets. */
export const FOUNDATIONS_JUMP_IN_POOL = Object.keys(FOUNDATIONS_JUMP_IN_BEHAVIORS);
/** Foundations cards for the draft trophy decks and the rest of Arena's Jump In packets. */
export const FOUNDATIONS_DRAFT_POOL = Object.keys(FOUNDATIONS_DRAFT_BEHAVIORS);

/** Marvel Super Heroes cards (fronts only: a double-faced card's back comes with it). */
export const MARVEL_POOL = Object.keys(MARVEL_BEHAVIORS);

/** Final Fantasy cards (fronts only). */
export const FINAL_FANTASY_POOL = Object.keys(FINAL_FANTASY_BEHAVIORS);

/** Strixhaven cards (fronts only). */
export const STRIXHAVEN_POOL = Object.keys(STRIXHAVEN_BEHAVIORS);

/** Secrets of Strixhaven cards (fronts only). */
export const SECRETS_OF_STRIXHAVEN_POOL = Object.keys(SECRETS_OF_STRIXHAVEN_BEHAVIORS);

/** The Strixhaven Brawl precons' cards (not already in the pool above). */
export const STRIXHAVEN_BRAWL_POOL = Object.keys(STRIXHAVEN_BRAWL_BEHAVIORS);

/** The Final Fantasy Commander Brawl decks' cards (not already in the pool above). */
export const FINAL_FANTASY_BRAWL_POOL = Object.keys(FINAL_FANTASY_BRAWL_BEHAVIORS);

/** Reality Fracture cards (fronts only). */
export const REALITY_FRACTURE_POOL = Object.keys(REALITY_FRACTURE_BEHAVIORS);

export const POOL: { name: string }[] = [
  ...RED_POOL,
  ...GREEN_POOL,
  ...WHITE_POOL,
  ...BLUE_POOL,
  ...BLACK_POOL,
  ...OTHER_POOL,
  ...FOUNDATIONS_JUMP_IN_POOL,
  ...FOUNDATIONS_DRAFT_POOL,
  ...LAND_POOL,
  ...BLOOMBURROW_POOL,
  ...MARVEL_POOL,
  ...MARVEL_BRAWL_POOL,
  ...FINAL_FANTASY_POOL,
  ...STRIXHAVEN_POOL,
  ...SECRETS_OF_STRIXHAVEN_POOL,
  ...STRIXHAVEN_BRAWL_POOL,
  ...FINAL_FANTASY_BRAWL_POOL,
  ...REALITY_FRACTURE_POOL,
].map((name) => ({
  name,
}));
