/** Allowed sets, most preferred first: Foundations, then older core sets. */
export const SET_PREFERENCE = [
  'fdn',
  'm21',
  'm20',
  'm19',
  'ori',
  'm15',
  'm14',
  'm13',
  'm12',
  'm11',
  'm10',
  '10e',
  '9ed',
  '8ed',
  '7ed',
  '6ed',
  '5ed',
  '4ed',
];

export const RED_POOL = [
  'Mountain',
  'Shock',
  'Lightning Strike',
  'Boltwave',
  'Kindled Fury',
  'Sure Strike',
  'Crash Through',
  'Dragon Fodder',
  'Seismic Rupture',
  'Fanatical Firebrand',
  'Viashino Pyromancer',
  'Heartfire Immolator',
  'Swab Goblin',
  'Firebrand Archer',
  'Searslicer Goblin',
  'Raging Redcap',
  'Brazen Scourge',
  'Guttersnipe',
  'Giant Cindermaw',
  'Spitfire Lagac',
  'Battlesong Berserker',
  'Skyraker Giant',
  'Ravenous Giant',
  'Ball Lightning',
  'Gorehorn Raider',
  'Fire Elemental',
  'Dragon Trainer',
  'Shivan Dragon',
] as const;

export const GREEN_POOL = [
  'Forest',
  'Giant Growth',
  'Snakeskin Veil',
  'Bite Down',
  'Broken Wings',
  'Felling Blow',
  'Overrun',
  'Bear Cub',
  'Thornweald Archer',
  'Druid of the Cowl',
  "Dwynen's Elite",
  'Imperious Perfect',
  'Beast-Kin Ranger',
  'Magnigoth Sentry',
  'Treetop Snarespinner',
  'Gnarlback Rhino',
  'Wildheart Invoker',
  'Tajuru Pathwarden',
  'Elfsworn Giant',
  "Heroes' Bane",
  'Rampaging Baloths',
  'Affectionate Indrik',
  'Quakestrider Ceratops',
  'Pelakka Wurm',
  'Aggressive Mammoth',
  'Gigantosaurus',
] as const;

export const POOL: { name: string }[] = [...RED_POOL, ...GREEN_POOL].map((name) => ({ name }));
