import type { Decklist } from '../decks.ts';

/** Reality Fracture decks (17b), part 2: our own two-colour 60-card decks. See docs/reality-fracture-plan.md. */
export const FRA_DECKS_2: Decklist[] = [
  {
    id: 'fra-drowned-archive',
    name: 'Drowned Archive',
    colors: ['U', 'B'],
    face: 'Uldaros Theorix',
    source: 'custom',
    series: 'starter',
    set: 'fra',
    cards: [
      ['Dark Matter Manipulator', 1],
      ['Void Extrapolator', 2],
      ['Paradox Shaper', 2],
      ['Theorix Metamage', 2],
      ['Rank Rat', 1],
      ['Tinybones, Pocket Nuisance', 1],
      ['Cryotheory Adept', 1],
      ['Divining Duelist', 1],
      ['Surveillance Phantasm', 1],
      ['Liliana the Repentant', 1],
      ['Seasoned Cryomancer', 1],
      ['Null Summoner', 1],
      ['Sphinx of False Conclusions', 1],
      ['Undulating Witness', 1],
      ['Screeching Soulbreaker', 1],
      ['Rampart Hunter', 1],
      ['Apex Witchstalker', 1],
      ['Uldaros Theorix', 1],
      ['Theorix Charm', 2],
      ['Last Gasp', 2],
      ['Recursive Recruitment', 1],
      ['Silence the Echo', 1],
      ['Rise of the Deathbringer', 1],
      ["Lich's Relic", 1],
      ['Mindseeker Oculus', 2],
      ['Solve for Disappointment', 1],
      ['Way of the Deathbringer', 1],
      ['Sanctum Lurker', 1],
      ['Countersculpt', 1],
      ['Rewrite Regrets', 1],
      ['Shipwreck Marsh', 1],
      ['Theorix Annex', 1],
      ['Island', 10],
      ['Swamp', 12],
    ],
  },
  {
    id: 'fra-stingerquill-barrage',
    name: 'Stingerquill Barrage',
    colors: ['B', 'R'],
    face: 'Ingris Stingerquill',
    source: 'custom',
    series: 'starter',
    set: 'fra',
    cards: [
      ['Pompous Battlemage', 1],
      ['Stingerquill Voxmancer', 2],
      ['Grim Repriser', 1],
      ['Master of Barbs', 1],
      ['Tomik, Izzet Sparkmage', 1],
      ['Screeching Soulbreaker', 1],
      ['Tinybones, Pocket Nuisance', 1],
      ['Rank Rat', 1],
      ['Koth, the Geomancer', 1],
      ["Chandra's Emberling", 1],
      ['Hallway Heckler', 1],
      ['Whiplash Wordsmith', 1],
      ['Pyre Rhymer', 1],
      ['Heartstring Puller', 1],
      ['Massacre Girl, Most Wanted', 1],
      ['Ingris Stingerquill', 1],
      ['Curse-Marred Demon', 1],
      ['Tether Technician', 1],
      ['Kiora of Fire and Ashes', 1],
      ['Stingerquill Charm', 2],
      ['Last Gasp', 1],
      ['Wrath of the Bloodmane', 2],
      ['Extended Absence', 1],
      ["Ajani's Anguish", 1],
      ['Awaken the Inferno', 1],
      ["Lich's Relic", 1],
      ['No Admittance', 2],
      ['Violent Echoes', 1],
      ['Way of the Warlord', 1],
      ['Solve for Disappointment', 1],
      ["Vraska's Final Mercy", 1],
      ['Gideon the Oathless', 1],
      ['Haunted Ridge', 1],
      ['Stingerquill Annex', 1],
      ['Mountain', 11],
      ['Swamp', 11],
    ],
  },
  {
    id: 'fra-vigorbloom-grove',
    name: 'Vigorbloom Grove',
    colors: ['G', 'W'],
    face: 'Kwia Vigorbloom',
    source: 'custom',
    series: 'starter',
    set: 'fra',
    cards: [
      ['Emergency Phytomedic', 1],
      ['Vigorbloom Vanguard', 2],
      ['Solarium Sentry', 1],
      ['Unflinching Hortimancer', 2],
      ['Enlightened Confidant', 1],
      ['Graft Surgeon', 1],
      ['Greenhouse Propagator', 1],
      ['Koth of the Homestead', 1],
      ['Lyra, Archangel of Dawn', 1],
      ['Bloombrute', 1],
      ['Blossom-Blessed Angel', 1],
      ['Titanbones, Towering Heart', 1],
      ['Yoshimaru, Beloved Companion', 1],
      ['Yoshimaru, Scrappy Stray', 1],
      ['Shatterwing Pegasus', 1],
      ['Thalia, the Survivor', 1],
      ['Guiding Hydra', 1],
      ['Simulacrum Shaper', 1],
      ['Vinelasher Adept', 1],
      ['Budding Insurgent', 1],
      ['Kwia Vigorbloom', 1],
      ['Vigorbloom Charm', 2],
      ['Prophesied End', 1],
      ['Your Fate Ends Here', 1],
      ['Flourishing Grapple', 1],
      ['Ajani Resolute', 1],
      ['Way of the Mentor', 1],
      ['Way of the Healer', 1],
      ['Teyo, Lightshield Expert', 1],
      ['Tomik, Orzhov Lawmage', 1],
      ['Academic Ascent', 1],
      ['Arcane Amphisbaena', 1],
      ['Inspired Tethermage', 1],
      ['Overgrown Farmland', 1],
      ['Vigorbloom Annex', 1],
      ['Forest', 11],
      ['Plains', 11],
    ],
  },
  {
    id: 'fra-bloodline-requiem',
    name: 'Bloodline Requiem',
    colors: ['W', 'B'],
    face: 'Edgar, Ancient Bloodlord',
    source: 'custom',
    series: 'starter',
    set: 'fra',
    cards: [
      ['Blessed Ghoul', 2],
      ['Edgar, Ancient Bloodlord', 1],
      ['Liliana the Faultless', 1],
      ['Mabel, Bitter Recluse', 1],
      ['Rank Rat', 1],
      ['Graft Surgeon', 2],
      ['Gallia, Tragic Host', 1],
      ['Theoretical Necromancer', 1],
      ['Darklight Phoenix', 1],
      ['Bloodline Recollector', 1],
      ['Massacre Girl, Most Wanted', 1],
      ['Winter, Tormented Loner', 1],
      ['Danitha, Spear of Agony', 1],
      ['Rampart Hunter', 1],
      ['Screeching Soulbreaker', 1],
      ['Thalia, the Survivor', 1],
      ['Shatterwing Pegasus', 1],
      ['Apex Witchstalker', 1],
      ['Fateshaper Aspirant', 1],
      ['Liliana the Repentant', 1],
      ['Vindictive Triumph', 1],
      ['Twisted Fates', 1],
      ['Last Gasp', 1],
      ['Prophesied End', 1],
      ['Your Fate Ends Here', 1],
      ['Extended Absence', 1],
      ['Rise of the Deathbringer', 1],
      ['Way of the Necromancer', 1],
      ['Way of the Deathbringer', 1],
      ['Teyo, Lightshield Expert', 1],
      ['Rewrite Regrets', 1],
      ['Repurposed Enforcer', 1],
      ['Surgical Precision', 1],
      ['Break Under Pressure', 1],
      ['Meticulous Commons', 1],
      ['Plains', 11],
      ['Swamp', 12],
    ],
  },
];
