import type { Decklist } from '../decks.ts';

/** Reality Fracture decks (17b), part 3: our own two-colour 60-card decks. See docs/reality-fracture-plan.md. */
export const FRA_DECKS_3: Decklist[] = [
  {
    // U/R: noncreature spells (prowess, Saheeli, Chandra's Emberling) and Thopters (Pia, Saheeli, Draconic Visitor).
    id: 'fra-clockwork-spellslingers',
    name: 'Clockwork Spellslingers',
    colors: ['U', 'R'],
    face: 'Saheeli, Jewel of Avishkar',
    source: 'custom',
    series: 'starter',
    set: 'fra',
    cards: [
      ['Pompous Battlemage', 1],
      ['Tomik, Izzet Sparkmage', 2],
      ['Cryotheory Adept', 2],
      ['Geist of Saint Thalia', 1],
      ["Chandra's Emberling", 2],
      ['Pia, Determined Rebuilder', 2],
      ['Variable Chaser', 1],
      ['Saheeli, Jewel of Avishkar', 1],
      ['Traxos, Academy Guardian', 1],
      ['Tetsuko Umezawa, Pursuer', 1],
      ['Sphinx of False Conclusions', 1],
      ['Curse-Marred Demon', 1],
      ['Draconic Visitor', 1],
      ['Hallway Heckler', 1],
      ['Divining Duelist', 1],
      ['Hapatra, the Desert Frost', 1],
      ['Kiora of Fire and Ashes', 1],
      ['Heartstring Puller', 1],
      ['Fulminous Forte', 2],
      ['Wrath of the Bloodmane', 2],
      ['Awaken the Inferno', 1],
      ['Icy Reception', 1],
      ['Unsummon', 1],
      ['Clash of Elements', 1],
      ['Twinned Vision', 1],
      ['Blazing Crescendo', 1],
      ['Command the Stage', 1],
      ["Medic's Kitesail", 1],
      ["Ajani's Anguish", 1],
      ['Infinite Coursework', 1],
      ['Innovative Commons', 2],
      ['Island', 11],
      ['Mountain', 11],
    ],
  },
  {
    // B/G: lands in the graveyard (Primal Witchstalker, Carnivorous Cultivator, Marwyn, Something Worth Saving).
    id: 'fra-grave-harvest',
    name: 'Grave Harvest',
    colors: ['B', 'G'],
    face: 'Primal Witchstalker',
    source: 'custom',
    series: 'starter',
    set: 'fra',
    cards: [
      ['Primal Witchstalker', 2],
      ['Carnivorous Cultivator', 2],
      ['Marwyn, the Preserver', 1],
      ['Rank Rat', 1],
      ['Greenhouse Propagator', 1],
      ['Budding Insurgent', 2],
      ['Sureshot Sower', 1],
      ['Rampart Hunter', 1],
      ['Apex Witchstalker', 2],
      ['Simulacrum Shaper', 1],
      ['Tarmogoyf', 1],
      ['Titanbones, Towering Heart', 1],
      ['Vraska, the Cutting Glare', 1],
      ['Hapatra, the Desert Fang', 1],
      ['Wrecking Gecko', 1],
      ['Vinelasher Adept', 1],
      ['Verdant Kraken', 1],
      ['Liliana the Repentant', 1],
      ['Screeching Soulbreaker', 1],
      ['Tinybones, Pocket Nuisance', 1],
      ['Mabel, Bitter Recluse', 1],
      ['Something Worth Saving', 2],
      ['Restore with Empathy', 1],
      ['Last Gasp', 2],
      ['Extended Absence', 1],
      ['Silence the Echo', 1],
      ['Break Under Pressure', 1],
      ['Bestial Incursion', 1],
      ['Cast Away Doubt', 1],
      ["Hunter's Axe", 1],
      ['Formidable Commons', 2],
      ['Swamp', 11],
      ['Forest', 11],
    ],
  },
  {
    // R/W: creatures entering (Mabel, Arni, Koth, Gallia) and +1/+1 counters (Warrior's Blades, Charge the Sanctum).
    id: 'fra-rallying-blades',
    name: 'Rallying Blades',
    colors: ['R', 'W'],
    face: 'Mabel, Valley Hero',
    source: 'custom',
    series: 'starter',
    set: 'fra',
    cards: [
      ['Gallia, the Merrymaker', 1],
      ['Mabel, Valley Hero', 2],
      ['Yoshimaru, Beloved Companion', 1],
      ['Graft Surgeon', 2],
      ['Skilled Battlecarver', 1],
      ['Heartstring Puller', 2],
      ['Pia, Determined Rebuilder', 1],
      ['Koth, the Geomancer', 1],
      ['Koth of the Homestead', 1],
      ['Shatterwing Pegasus', 2],
      ['Lyra, Archangel of Dawn', 1],
      ['Thalia, the Survivor', 1],
      ['Arni, Renowned Champion', 1],
      ['Master of Barbs', 1],
      ['Danitha, Sword of Hope', 1],
      ['Pyre Rhymer', 1],
      ['Tetsuko Umezawa, Pursuer', 1],
      ['Curse-Marred Demon', 1],
      ['Draconic Visitor', 1],
      ['Jiang Yanggu, Alone', 1],
      ['Kiora of Fire and Ashes', 1],
      ["Warrior's Blades", 1],
      ['Charge the Sanctum', 2],
      ['Memory Trap', 1],
      ['Wrath of the Bloodmane', 2],
      ['Prophesied End', 1],
      ['Awaken the Inferno', 1],
      ['Fulminous Forte', 1],
      ['Surgical Precision', 1],
      ['Your Fate Ends Here', 1],
      ['Dedicated Commons', 1],
      ['Mountain', 11],
      ['Plains', 12],
    ],
  },
  {
    // G/U: landfall-style ramp (lands put onto the battlefield, land recursion) into big creatures.
    id: 'fra-tidal-terrain',
    name: 'Tidal Terrain',
    colors: ['G', 'U'],
    face: 'Simulacrum Shaper',
    source: 'custom',
    series: 'starter',
    set: 'fra',
    cards: [
      ['Greenhouse Propagator', 2],
      ['Sureshot Sower', 2],
      ['Budding Insurgent', 2],
      ['Simulacrum Shaper', 1],
      ['Marwyn, the Preserver', 1],
      ['Carnivorous Cultivator', 2],
      ['Divining Duelist', 2],
      ['Undulating Witness', 1],
      ['Fblthp, Knows the Way', 1],
      ['Hapatra, the Desert Frost', 1],
      ['Tam, the Possibility', 1],
      ['Titanbones, Towering Heart', 1],
      ['Jiang Yanggu, Never Alone', 1],
      ['Edgar, Moonlit Sovereign', 1],
      ['Lyra, Tolarian Archangel', 1],
      ['Sphinx of False Conclusions', 1],
      ['Ruric Thar, Biomagus', 1],
      ['Ruric Thar, Magecrusher', 1],
      ['Verdant Kraken', 1],
      ['Seasoned Cryomancer', 1],
      ['Yoshimaru, Scrappy Stray', 1],
      ['Wrecking Gecko', 1],
      ['Vinelasher Adept', 1],
      ['Tarmogoyf', 1],
      ['Bestial Incursion', 2],
      ['Flourishing Grapple', 1],
      ['Something Worth Saving', 1],
      ['Icy Reception', 1],
      ['Unsummon', 1],
      ['Infinite Coursework', 1],
      ['Transformative Commons', 1],
      ['Roiling Canopy', 1],
      ['Forest', 11],
      ['Island', 11],
    ],
  },
];
