import type { Decklist } from '../decks.ts';

/** Reality Fracture decks (17b), part 1: our own two-colour 60-card decks. See docs/reality-fracture-plan.md. */
export const FRA_DECKS_1: Decklist[] = [
  {
    id: 'fra-foresight-and-flight',
    name: 'Foresight and Flight',
    colors: ['W', 'U'],
    face: 'Denzilore Fatehold',
    source: 'custom',
    series: 'starter',
    set: 'fra',
    cards: [
      ['Surveillance Phantasm', 2],
      ['Proft, Consulting Detective', 1],
      ['Geist of Saint Thalia', 1],
      ['Proctor of Potential', 1],
      ['Divining Duelist', 1],
      ['Graft Surgeon', 1],
      ['Prudent Fateseer', 2],
      ['Shatterwing Pegasus', 2],
      ['Desperate Futurescribe', 2],
      ['Denzilore Fatehold', 1],
      ['Saheeli, Consul of Oversight', 1],
      ['Sphinx of False Conclusions', 1],
      ['Undulating Witness', 2],
      ['Archive Arbiter', 1],
      ['Yuriko, Hope from the Shadows', 1],
      ['Thalia, the Survivor', 1],
      ['Fateshaper Aspirant', 1],
      ['Prophesied End', 2],
      ['Your Fate Ends Here', 2],
      ['Refute Destiny', 1],
      ['Surgical Precision', 2],
      ['Memory Trap', 2],
      ['Eye of Jace', 1],
      ["Medic's Kitesail", 1],
      ['Predictive Preparations', 1],
      ['Icy Reception', 1],
      ['Generous Revival', 1],
      ['Plains', 11],
      ['Island', 11],
      ['Deserted Beach', 1],
      ['Fatehold Annex', 1],
    ],
  },
  {
    id: 'fra-heartwood-forge',
    name: 'Heartwood Forge',
    colors: ['R', 'G'],
    face: 'Aerid Konstrari',
    source: 'custom',
    series: 'starter',
    set: 'fra',
    cards: [
      ['Tenured Tethermage', 1],
      ['Aerid Konstrari', 1],
      ['Hungering Puppetbeast', 1],
      ['Craftwork Crusher', 1],
      ['Pia, Determined Rebuilder', 1],
      ['Wrecking Gecko', 2],
      ['Heartstring Puller', 2],
      ['Afterthought Sentry', 2],
      ['Greenhouse Propagator', 2],
      ['Budding Insurgent', 2],
      ['Sureshot Sower', 1],
      ['Simulacrum Shaper', 1],
      ['Tether Technician', 2],
      ['Skilled Battlecarver', 2],
      ['Draconic Visitor', 1],
      ['Craterclaw Colossus', 1],
      ['Vinelasher Adept', 1],
      ['Yoshimaru, Scrappy Stray', 1],
      ['Jiang Yanggu, Never Alone', 1],
      ['Fulminous Forte', 2],
      ['Wrath of the Bloodmane', 2],
      ['Awaken the Inferno', 2],
      ['Konstrari Charm', 1],
      ["Hunter's Axe", 1],
      ['Bestial Incursion', 1],
      ['Flourishing Grapple', 1],
      ['Forest', 11],
      ['Mountain', 11],
      ['Rockfall Vale', 1],
      ['Konstrari Annex', 1],
    ],
  },
];
