/**
 * Writes src/<set>/booster-list.ts: every card in a set's booster packs with
 * its rarity in that set. The generated scryfall.json keeps one printing per
 * card, so cards reprinted in a preferred set lose their `set`; this list doesn't.
 * Run from packages/cards: node scripts/fetch-booster-list.ts stx|sos|fra|ecl|tdm|hob
 *
 * STX: Scryfall `is:booster`. SOS: Scryfall marks no card `is:booster`, so it is
 * the main-set cards (numeric collector numbers up to 280), basics left out.
 * FRA: the same (collector numbers 1 to 280 are the 280 nonbasic main-set cards).
 * ECL: the same, collector numbers 1 to 268 (basics are 269 to 283).
 * TDM: Scryfall `is:booster` (271 cards, collector numbers 1 to 271).
 * HOB: Scryfall marks no card `is:booster`: collector numbers 1 to 188 (189 to 198 are basics).
 */
import { writeFileSync } from 'node:fs';

const set = process.argv[2];
if (
  set !== 'stx' &&
  set !== 'sos' &&
  set !== 'fra' &&
  set !== 'ecl' &&
  set !== 'tdm' &&
  set !== 'hob'
)
  throw new Error('usage: fetch-booster-list.ts stx|sos|fra|ecl|tdm|hob');
const query =
  set === 'stx' || set === 'tdm'
    ? `set:${set} is:booster`
    : `set:${set} cn>=1 cn<=${set === 'ecl' ? 268 : set === 'hob' ? 188 : 280} -t:basic -is:promo`;

const headers = { 'User-Agent': 'mtg-personal-client/0.1', Accept: 'application/json' };
interface C {
  name: string;
  rarity: string;
}
const rows: [string, string][] = [];
let url: string | undefined =
  `https://api.scryfall.com/cards/search?q=${encodeURIComponent(query)}&unique=prints&order=name`;
while (url) {
  const page = (await (await fetch(url, { headers })).json()) as {
    data: C[];
    has_more: boolean;
    next_page?: string;
  };
  for (const c of page.data) rows.push([c.name.split(' // ')[0]!, c.rarity]);
  url = page.has_more ? page.next_page : undefined;
  await new Promise((r) => setTimeout(r, 120));
}
const seen = new Set<string>();
rows.splice(0, rows.length, ...rows.filter(([n]) => !seen.has(n) && seen.add(n)));
rows.sort((a, b) => a[0].localeCompare(b[0]));
const body = rows.map(([n, r]) => `  [${JSON.stringify(n)}, '${r}'],`).join('\n');
writeFileSync(
  new URL(`../src/${set}/booster-list.ts`, import.meta.url),
  `// Generated by scripts/fetch-booster-list.ts (${query}). Front-face names.
export const ${set.toUpperCase()}_BOOSTER_LIST: readonly [
  name: string,
  rarity: 'common' | 'uncommon' | 'rare' | 'mythic',
][] = [
${body}
];
`,
);
const tally = (r: string) => rows.filter(([, x]) => x === r).length;
console.log(rows.length, ['common', 'uncommon', 'rare', 'mythic'].map(tally));
