/**
 * Writes src/<stx|sos>/archive-list.ts: every Mystical Archive card (STA for
 * Strixhaven, SOA for Secrets of Strixhaven) with its archive rarity. Reads the
 * local Scryfall bulk cache (no API calls). The Japanese alternate-art prints
 * share a name with the English card, so each card counts once.
 * Run from packages/cards: node scripts/fetch-archive-list.ts sta|soa
 */
import { createReadStream, writeFileSync } from 'node:fs';
import { createInterface } from 'node:readline';
import { createGunzip } from 'node:zlib';

const arg = process.argv[2];
if (arg !== 'sta' && arg !== 'soa') throw new Error('usage: fetch-archive-list.ts sta|soa');
const dir = arg === 'sta' ? 'stx' : 'sos';
const rows = new Map<string, string>();
const rl = createInterface({
  input: createReadStream(new URL('../.cache/default-cards.jsonl.gz', import.meta.url)).pipe(
    createGunzip(),
  ),
});
for await (const line of rl) {
  if (!line.includes(`"set":"${arg}"`)) continue;
  const c = JSON.parse(line) as { set: string; name: string; rarity: string; lang: string };
  if (c.set !== arg) continue;
  if (!rows.has(c.name) || c.lang === 'en') rows.set(c.name, c.rarity);
}
const sorted = [...rows].sort((a, b) => a[0].localeCompare(b[0]));
const body = sorted.map(([n, r]) => `  [${JSON.stringify(n)}, '${r}'],`).join('\n');
writeFileSync(
  new URL(`../src/${dir}/archive-list.ts`, import.meta.url),
  `// Generated by scripts/fetch-archive-list.ts (set ${arg}, from the bulk cache). Each card once, English name.
export const ${arg.toUpperCase()}_ARCHIVE_LIST: readonly [name: string, rarity: 'uncommon' | 'rare' | 'mythic'][] = [
${body}
];
`,
);
console.log(
  sorted.length,
  ['uncommon', 'rare', 'mythic'].map((r) => sorted.filter(([, x]) => x === r).length),
);
