/**
 * Writes src/stx/booster-list.ts: every card in Strixhaven booster packs with
 * its STX rarity. The generated scryfall.json keeps one printing per card, so
 * STX cards reprinted in a preferred set lose `set === 'stx'`; this list doesn't.
 * Run from packages/cards: node scripts/fetch-stx-booster-list.ts
 */
import { writeFileSync } from 'node:fs';

const headers = { 'User-Agent': 'mtg-personal-client/0.1', Accept: 'application/json' };
interface C {
  name: string;
  rarity: string;
}
const rows: [string, string][] = [];
let url: string | undefined =
  'https://api.scryfall.com/cards/search?q=set%3Astx+is%3Abooster&unique=prints&order=name';
while (url) {
  const page = (await (await fetch(url, { headers })).json()) as {
    data: C[];
    has_more: boolean;
    next_page?: string;
  };
  for (const c of page.data) rows.push([c.name.split(' // ')[0]!, c.rarity]);
  url = page.has_more ? page.next_page : undefined;
  await new Promise((r) => setTimeout(r, 120));
}
const seen = new Set<string>();
rows.splice(0, rows.length, ...rows.filter(([n]) => !seen.has(n) && seen.add(n)));
rows.sort((a, b) => a[0].localeCompare(b[0]));
const body = rows.map(([n, r]) => `  [${JSON.stringify(n)}, '${r}'],`).join('\n');
writeFileSync(
  new URL('../src/stx/booster-list.ts', import.meta.url),
  `// Generated by scripts/fetch-stx-booster-list.ts (Scryfall set:stx is:booster). Front-face names.
export const STX_BOOSTER_LIST: readonly [
  name: string,
  rarity: 'common' | 'uncommon' | 'rare' | 'mythic',
][] = [
${body}
];
`,
);
console.log(rows.length);
